PRACK sip:cbcd92dc-db6f-4aea-a207-e26b95efb9f2@10.46.0.8:41989 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKANWYZ2YDOTLOK5E65KHLCMDYQS
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKEYJVU3M5JEM5SBXS2XQ2OFOXXA
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKS46RQ5DPQEABSG3FLSQEINF2T6
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKGAXT5XR5ERGT5TODCIOMWLV66D
Via: SIP/2.0/UDP 10.46.0.7:6600;branch=z9hG4bK-524287-1---1476aabb1ee49439;rport=6600;transport=UDP;received=10.46.0.7
Max-Forwards: 66
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=100319479
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=89465902
Call-ID: u_J0EuKkKtGg8_4krDbN1g..@10.46.0.7
CSeq: 2 PRACK
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
RAck: 1 1 INVITE
Content-Length: 0

