PRACK sip:cbcd92dc-db6f-4aea-a207-e26b95efb9f2@10.46.0.8:41989 SIP/2.0
Via: SIP/2.0/UDP 10.46.0.7:6600;branch=z9hG4bK-524287-1---80f236ef929a9ad4;rport;transport=UDP
Max-Forwards: 70
Route: <sip:3iqp554vb5dijnjmjo2u3xbt2t@10.80.0.5:5063;transport=tcp;lr;r2=on;did=IWPS44BH35RETB3G;ue>
Route: <sip:3iqp554vb5dijnjmjo2u3xbt2t@10.80.0.5:5060;lr;r2=on;did=IWPS44BH35RETB3G>
Route: <sip:mo@10.80.0.5:5080;lr;did=VENQN7E3JGGY36BT>
Route: <sip:mt@10.80.0.5:5080;lr;did=TDFZP5D4FBP6QJJR>
Route: <sip:75xi5p5r4lmyujqtijnkhr24d7@10.80.0.5:5060;lr;r2=on;did=2BAVT3L3NFJ6FVKB>
Route: <sip:75xi5p5r4lmyujqtijnkhr24d7@10.80.0.5:5063;transport=tcp;lr;r2=on;did=2BAVT3L3NFJ6FVKB;ue>
Proxy-Require: sec-agree
Require: sec-agree
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=100319479
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=89465902
Call-ID: u_J0EuKkKtGg8_4krDbN1g..@10.46.0.7
CSeq: 4 PRACK
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=167591435;spi-s=140386225;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
RAck: 2 1 INVITE
P-Preferred-Identity: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=9990100000100066c000
Content-Length: 0

