PRACK sip:cbcd92dc-db6f-4aea-a207-e26b95efb9f2@10.46.0.8:41989 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bK6TYONHYJJPEG2OMJV7QBEMEV3R
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKKWJEPMKWQAHLCLDH2BVVRDOBNE
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKCD632HZPA6N3I4YLQV5ZBHBQVF
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKHVZ52NKTH6NC3JJRDM2FSARG6L
Via: SIP/2.0/UDP 10.46.0.7:6600;branch=z9hG4bK-524287-1---80f236ef929a9ad4;rport=6600;transport=UDP;received=10.46.0.7
Max-Forwards: 66
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=100319479
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=89465902
Call-ID: u_J0EuKkKtGg8_4krDbN1g..@10.46.0.7
CSeq: 4 PRACK
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
RAck: 2 1 INVITE
Content-Length: 0

