CANCEL sip:cbcd92dc-db6f-4aea-a207-e26b95efb9f2@10.46.0.8:41989 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bK6QY6OTGJDIDHFROPTAPDO4XBJN
Max-Forwards: 70
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=89465902
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>
Call-ID: u_J0EuKkKtGg8_4krDbN1g..@10.46.0.7
CSeq: 1 CANCEL
Content-Length: 0

