ACK sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone SIP/2.0
Via: SIP/2.0/TCP 10.46.0.7:6600;branch=z9hG4bK-524287-1---ea79a4bc285f365c;rport;transport=TCP
Max-Forwards: 70
Route: <sip:10.80.0.5:5063;lr>
Route: <sip:orig-3@scscf.ims.mnc001.mcc999.3gppnetwork.org:5080;lr>
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=100319479
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=89465902
Call-ID: u_J0EuKkKtGg8_4krDbN1g..@10.46.0.7
CSeq: 1 ACK
Content-Length: 0

