PRACK sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKPVEMJA7FOXTKWDKZ2CNTRCEFH6
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKOJYU36ON7P3BSARJERC3PG4IDN
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK3VQKXXJMDUFPRGZWRY66WBHHC6
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKLIBMGPDBOTWU7KLWD6YWTCO56K
RAck: 1 1 INVITE
To: <tel:+15550000004>;tag=2129068
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=PhHy2mVm74
Call-ID: 6X2v53NtZZwAowLkKtybtmGk
Session-ID: 4d85ae1797ba81f1f20ab74d84f7d260
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 2 PRACK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKyUmAYd7CKHIjxbx;rport=57130;received=10.46.0.17
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

