SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bK0nRbxbHqiUAFlI9;rport=57130;received=10.46.0.17
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=PhHy2mVm74
To: <tel:+15550000004>;tag=2129068
Call-ID: 6X2v53NtZZwAowLkKtybtmGk
Session-ID: 4d85ae1797ba81f1f20ab74d84f7d260
CSeq: 1 INVITE
Record-Route: <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;transport=tcp;lr;r2=on;did=43F67AKWDG4B6IJA;ue>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;lr;r2=on;did=43F67AKWDG4B6IJA>,<sip:mt@10.80.0.5:5080;lr;did=76C6OH5IQ24DUNSA>,<sip:mo@10.80.0.5:5080;lr;did=ANJ22NL7SCMD4MAX>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;lr;r2=on;did=6ADWKX7IFITQURD2>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;transport=tcp;lr;r2=on;did=6ADWKX7IFITQURD2;ue>
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
Require: timer,100rel
Contact: <sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Supported: timer,100rel,from-change,tdialog
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
Session-Expires: 1800;refresher=uac
P-Asserted-Identity: <tel:+15550000004>
P-Asserted-Identity: <sip:+15550000004@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

