ACK sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435 SIP/2.0
To: <tel:+15550000004>;tag=2129068
Route: <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=6ADWKX7IFITQURD2;lr;r2=on;transport=tcp;ue>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=6ADWKX7IFITQURD2;lr;r2=on>, <sip:mo@10.80.0.5:5080;did=ANJ22NL7SCMD4MAX;lr>, <sip:mt@10.80.0.5:5080;did=76C6OH5IQ24DUNSA;lr>, <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;did=43F67AKWDG4B6IJA;lr;r2=on>, <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;did=43F67AKWDG4B6IJA;lr;r2=on;transport=tcp;ue>
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=PhHy2mVm74
Call-ID: 6X2v53NtZZwAowLkKtybtmGk
Session-ID: 4d85ae1797ba81f1f20ab74d84f7d260
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 1 ACK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKdQ50NQMPrPg0nA8;rport
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5064;port-s=5063;prot=esp;q=0.1;spi-c=189860270;spi-s=88237557
Require: sec-agree
Proxy-Require: sec-agree
Content-Length: 0

