BYE sip:10.46.0.17:61189 SIP/2.0
To: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=PhHy2mVm74
From: <tel:+15550000004>;tag=2129068
Call-ID: 6X2v53NtZZwAowLkKtybtmGk
CSeq: 2 BYE
Via: SIP/2.0/TCP 10.46.0.15:43435;branch=z9hG4bK1104443053
Max-Forwards: 70
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015EE0000
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=113224940;spi-s=105724704;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Route: <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;transport=tcp;lr;r2=on;did=43F67AKWDG4B6IJA;ue>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;lr;r2=on;did=43F67AKWDG4B6IJA>,<sip:mt@10.80.0.5:5080;lr;did=76C6OH5IQ24DUNSA>,<sip:mo@10.80.0.5:5080;lr;did=ANJ22NL7SCMD4MAX>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;lr;r2=on;did=6ADWKX7IFITQURD2>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;transport=tcp;lr;r2=on;did=6ADWKX7IFITQURD2;ue>
P-Preferred-Identity: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>
Require: sec-agree
Proxy-Require: sec-agree
Reason: RELEASE_CAUSE ;cause=1 ;text="User ends call"
User-Agent: Core-Z5 N1982U.6.02.09.FR00
Session-ID: 4d85ae1797ba81f1f20ab74d84f7d260
Content-Length: 0

