SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.15:43435;branch=z9hG4bK1104443053
To: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=PhHy2mVm74
From: <tel:+15550000004>;tag=2129068
Call-ID: 6X2v53NtZZwAowLkKtybtmGk
CSeq: 2 BYE
Session-ID: 4d85ae1797ba81f1f20ab74d84f7d260
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

