REGISTER sip:ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
From: <sip:001010000000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=6b27fedc
To: <sip:001010000000002@ims.mnc001.mcc001.3gppnetwork.org>
Contact: <sip:45a6a166-7a26-94f7-8e36-9e4dd6bdef7c@10.46.0.23:5060>;audio;+g.3gpp.nw-init-ussi;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";video;+g.3gpp.accesstype="cellular2";+g.3gpp.smsip;reg-id=1;+sip.instance="<urn:gsma:imei:00000000-000006-0>"
Call-ID: 4e61f18221ea2db@10.46.0.23
CSeq: 1 REGISTER
Max-Forwards: 70
Via: SIP/2.0/TCP 10.46.0.23:5060;branch=z9hG4bK8b9e92904cc15c0339ec2abe
Expires: 600000
Allow: INVITE,CANCEL,UPDATE,PRACK,BYE,ACK,MESSAGE,SUBSCRIBE,NOTIFY,PUBLISH,REFER,INFO,OPTIONS
Content-Length: 0
User-Agent: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Authorization: Digest username="001010000000002@ims.mnc001.mcc001.3gppnetwork.org",realm="ims.mnc001.mcc001.3gppnetwork.org",uri="sip:ims.mnc001.mcc001.3gppnetwork.org",nonce="",response=""
Privacy: none
Require: sec-agree
Proxy-Require: sec-agree
Security-Client: ipsec-3gpp;alg=hmac-md5-96;prot=esp;mod=trans;ealg=aes-cbc;spi-c=2308;spi-s=2309;port-c=49166;port-s=49167,ipsec-3gpp;alg=hmac-md5-96;prot=esp;mod=trans;ealg=des-ede3-cbc;spi-c=2308;spi-s=2309;port-c=49166;port-s=49167,ipsec-3gpp;alg=hmac-md5-96;prot=esp;mod=trans;ealg=null;spi-c=2308;spi-s=2309;port-c=49166;port-s=49167,ipsec-3gpp;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=aes-cbc;spi-c=2308;spi-s=2309;port-c=49166;port-s=49167,ipsec-3gpp;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=des-ede3-cbc;spi-c=2308;spi-s=2309;port-c=49166;port-s=49167,ipsec-3gpp;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=null;spi-c=2308;spi-s=2309;port-c=49166;port-s=49167
Supported: path,sec-agree

