SIP/2.0 401 Unauthorized
From: <sip:001010000000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=6b27fedc
To: <sip:001010000000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=ZQIKIX75JYNTMDKWIUH5H2EA6P
Call-ID: 4e61f18221ea2db@10.46.0.23
CSeq: 1 REGISTER
Via: SIP/2.0/TCP 10.46.0.23:5060;branch=z9hG4bK8b9e92904cc15c0339ec2abe
Content-Length: 0
WWW-Authenticate: Digest realm="ims.mnc001.mcc001.3gppnetwork.org", nonce="XbyUteSHzd6J+sVPYaZRsoFkRELx54AAH/gTxD0/q/g=", algorithm=AKAv1-MD5, qop="auth"
Security-Server: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=134404440;spi-s=122744594;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Supported: sec-agree

