REGISTER sip:ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
From: <sip:001010000000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=6b27fedc
To: <sip:001010000000002@ims.mnc001.mcc001.3gppnetwork.org>
Contact: <sip:45a6a166-7a26-94f7-8e36-9e4dd6bdef7c@10.46.0.23:49167>;audio;+g.3gpp.nw-init-ussi;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";video;+g.3gpp.accesstype="cellular2";+g.3gpp.smsip;reg-id=1;+sip.instance="<urn:gsma:imei:00000000-000006-0>"
Call-ID: 4e61f18221ea2db@10.46.0.23
CSeq: 2 REGISTER
Max-Forwards: 70
Via: SIP/2.0/TCP 10.46.0.23:49167;branch=z9hG4bKd574750a36c10c55cba4e62b
Expires: 600000
Allow: INVITE,CANCEL,UPDATE,PRACK,BYE,ACK,MESSAGE,SUBSCRIBE,NOTIFY,PUBLISH,REFER,INFO,OPTIONS
Content-Length: 0
User-Agent: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Authorization: Digest username="001010000000002@ims.mnc001.mcc001.3gppnetwork.org",realm="ims.mnc001.mcc001.3gppnetwork.org",algorithm=AKAv1-MD5,uri="sip:ims.mnc001.mcc001.3gppnetwork.org",nonce="XbyUteSHzd6J+sVPYaZRsoFkRELx54AAH/gTxD0/q/g=",response="66c8efe9fd283bf2200eff2e84106dca",qop=auth,nc=00000001,cnonce="1c5bf1a56a874fa19dbad94db20bbfb5"
Privacy: none
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010019b01
Require: sec-agree
Proxy-Require: sec-agree
Security-Client: ipsec-3gpp;alg=hmac-md5-96;prot=esp;mod=trans;ealg=aes-cbc;spi-c=2308;spi-s=2309;port-c=49166;port-s=49167,ipsec-3gpp;alg=hmac-md5-96;prot=esp;mod=trans;ealg=des-ede3-cbc;spi-c=2308;spi-s=2309;port-c=49166;port-s=49167,ipsec-3gpp;alg=hmac-md5-96;prot=esp;mod=trans;ealg=null;spi-c=2308;spi-s=2309;port-c=49166;port-s=49167,ipsec-3gpp;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=aes-cbc;spi-c=2308;spi-s=2309;port-c=49166;port-s=49167,ipsec-3gpp;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=des-ede3-cbc;spi-c=2308;spi-s=2309;port-c=49166;port-s=49167,ipsec-3gpp;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=null;spi-c=2308;spi-s=2309;port-c=49166;port-s=49167
Supported: path,sec-agree
Security-Verify: ipsec-3gpp;q=0.1;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=null;spi-c=134404440;spi-s=122744594;port-c=5064;port-s=5063

