SUBSCRIBE sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=dabae0ed
To: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>
Contact: <sip:45a6a166-7a26-94f7-8e36-9e4dd6bdef7c@10.46.0.23:49167>;audio;+g.3gpp.nw-init-ussi;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";video;+g.3gpp.smsip;+sip.instance="<urn:gsma:imei:00000000-000006-0>"
Call-ID: 607d0cbf9e163710@10.46.0.23
CSeq: 1 SUBSCRIBE
Max-Forwards: 70
Via: SIP/2.0/TCP 10.46.0.23:49167;branch=z9hG4bK995efcb67b3f53aab164e6d8
Expires: 600000
Content-Length: 0
Allow: INVITE,CANCEL,UPDATE,PRACK,BYE,ACK,MESSAGE,SUBSCRIBE,NOTIFY,PUBLISH,REFER,INFO,OPTIONS
P-Preferred-Identity: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>
User-Agent: Google_Pixel10a_Android 16_BD6A.251031.001.A4
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010019b01
Require: sec-agree
Proxy-Require: sec-agree
Event: reg
Route: <sip:10.80.0.5:5063;lr>,<sip:orig-42@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
Security-Verify: ipsec-3gpp;q=0.1;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=null;spi-c=134404440;spi-s=122744594;port-c=5064;port-s=5063
Accept: application/reginfo+xml

