SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.46.0.3:49165;branch=z9hG4bKf46b14eb951ec6c8a19e6a0
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=582401df
To: <tel:15550000005;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=103005316
Call-ID: 597b5d5e874d752d@10.46.0.3
CSeq: 1 INVITE
Record-Route: <sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5063;transport=tcp;lr;r2=on;did=T7SHDVRJGHLDOKVN;ue>,<sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5060;lr;r2=on;did=T7SHDVRJGHLDOKVN>,<sip:mt@10.80.0.5:5080;lr;did=XERJQUZ6JZLW2PV7>,<sip:mo@10.80.0.5:5080;lr;did=3VYFCAB5PBCJ7SMI>,<sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5060;lr;r2=on;did=ICMM4EZXN4VRLZSX>,<sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5063;transport=tcp;lr;r2=on;did=ICMM4EZXN4VRLZSX;ue>
Content-Length: 0
Session-ID: 16f020d7f8d4504b9c6ef39d63c03de4
Server: Core-Z5 N1982U.6.02.09.FR00
RSeq: 2
Contact: <sip:b394eba0-c3ed-4e54-adf4-83d317ca2979@10.46.0.2:43300>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
P-Asserted-Identity: <tel:+15550000005>
P-Asserted-Identity: <sip:+15550000005@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

