SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bK6ERZALGTYLEDG3ZGDBMUCWF75Q,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKKOOSNZPSUGDMRKPADBSAYUFQLQ,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bKNC3JV6RX3MKWM6V3EAI2MYGPKK,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKB7OMFWSBKLSCWJPQUMBOXLD52I,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKQJQJWCOK2VRNSTTD22NEBN6YOS,SIP/2.0/TCP 10.46.0.14:40265;branch=z9hG4bK3637598337
From: <sip:15550000001@ims.mnc001.mcc001.3gppnetwork.org>;tag=877628
To: <sip:15550000004;phone-context=ims.mnc001.mcc001.3gppnetwork.org@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=877916
CSeq: 877621 INVITE
Call-ID: 877621_4111242528@10.46.0.14
Record-Route: <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;transport=tcp;lr;r2=on;did=SDDNIER5RJ7WQSTR;ue>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;lr;r2=on;did=SDDNIER5RJ7WQSTR>,<sip:mt@10.80.0.5:5080;lr;did=4JPO4OY5BD5KRJD2>,<sip:mo@10.80.0.5:5080;lr;did=T45IOCLIMXJ7ZJJC>,<sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5060;lr;r2=on;did=MEC3I4VACMXMXODM>,<sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5063;transport=tcp;lr;r2=on;did=MEC3I4VACMXMXODM;ue>
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
RSeq: 2
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015EE0000
Contact: <sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

