SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.46.0.8:42225;branch=z9hG4bK449680059
From: <sip:15550000005@ims.mnc001.mcc001.3gppnetwork.org>;tag=111227338
To: <tel:15550000008;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=111227617
CSeq: 111227331 INVITE
Call-ID: 111227331_1761235264@10.46.0.8
Record-Route: <sip:nsbgwhufa64gwwi7ngbk7jry6d@10.80.0.5:5063;transport=tcp;lr;r2=on;did=MWLT43YCLCK6R2XV;ue>,<sip:nsbgwhufa64gwwi7ngbk7jry6d@10.80.0.5:5060;lr;r2=on;did=MWLT43YCLCK6R2XV>,<sip:mt@10.80.0.5:5080;lr;did=3AXXJPBTDDIYAIF7>,<sip:mo@10.80.0.5:5080;lr;did=SVRAV3EN7G2CGUU2>,<sip:l2aykhrmqrls3wwcj6g7e6j3yy@10.80.0.5:5060;lr;r2=on;did=ZVKFOBV3FEVOSXZN>,<sip:l2aykhrmqrls3wwcj6g7e6j3yy@10.80.0.5:5063;transport=tcp;lr;r2=on;did=ZVKFOBV3FEVOSXZN;ue>
Content-Length: 0
Server: PRD-IR92/12 term-Motorola/XT2417-1-V1UFN35H.193-20 device-type/smart-phone
RSeq: 2
Contact: <sip:a87a2e9a-4c32-439f-afc0-825ea2f8b236@10.46.0.9:43885>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
P-Asserted-Identity: <tel:+15550000008>
P-Asserted-Identity: <sip:+15550000008@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

