SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.46.0.15:43435;branch=z9hG4bK4289813359
From: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>;tag=1081653
To: <tel:15550000001;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=1082012
CSeq: 1081648 INVITE
Call-ID: 1081648_3070637664@10.46.0.15
Record-Route: <sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5063;transport=tcp;lr;r2=on;did=2UMOUCFMC5ZDMWNV;ue>,<sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5060;lr;r2=on;did=2UMOUCFMC5ZDMWNV>,<sip:mt@10.80.0.5:5080;lr;did=NVJIYNISUBJNVM6T>,<sip:mo@10.80.0.5:5080;lr;did=F5ZMBW5OX6DMYV43>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;lr;r2=on;did=ELPHFW53K3TWHBU5>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;transport=tcp;lr;r2=on;did=ELPHFW53K3TWHBU5;ue>
Content-Length: 0
Server: PRD-IR92/12 term-Motorola/XT2417-1-V1UFN35H.193-20 device-type/smart-phone
RSeq: 2
Privacy: id
Contact: <sip:59ca0608-182c-4e87-aed8-aa1e2a898c87@10.46.0.14:40265>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

