SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.46.0.7:49171;branch=z9hG4bK792f55e2971d4a685376e1e4
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=4adeb09b
To: <tel:15550000005;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=112583285
Call-ID: 4f22af16a24cc6@10.46.0.7
CSeq: 1 INVITE
Record-Route: <sip:l2aykhrmqrls3wwcj6g7e6j3yy@10.80.0.5:5063;transport=tcp;lr;r2=on;did=XRD7U2VCTPNTUUZG;ue>,<sip:l2aykhrmqrls3wwcj6g7e6j3yy@10.80.0.5:5060;lr;r2=on;did=XRD7U2VCTPNTUUZG>,<sip:mt@10.80.0.5:5080;lr;did=5ZTFK5NBWEG5AMWQ>,<sip:mo@10.80.0.5:5080;lr;did=R4U4EG3J7F7VKVMW>,<sip:t7kgpikxbisiecwrwzojjcbryu@10.80.0.5:5060;lr;r2=on;did=W6MQZ3OSVOAPPCMC>,<sip:t7kgpikxbisiecwrwzojjcbryu@10.80.0.5:5063;transport=tcp;lr;r2=on;did=W6MQZ3OSVOAPPCMC;ue>
Content-Length: 0
Session-ID: d22826c3284554e6a99141f3b92263d2
Server: Core-Z5 N1982U.6.02.09.FR00
RSeq: 2
Contact: <sip:2da86196-c8f7-4939-af8b-fbdac4e983f2@10.46.0.8:42225>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
P-Asserted-Identity: <tel:+15550000005>
P-Asserted-Identity: <sip:+15550000005@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

