BYE sip:15550000002@10.46.0.7:49171 SIP/2.0
To: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=4adeb09b
From: <tel:15550000005;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=112583285
Call-ID: 4f22af16a24cc6@10.46.0.7
CSeq: 2 BYE
Via: SIP/2.0/TCP 10.46.0.8:42225;branch=z9hG4bK4190770178
Max-Forwards: 70
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=0010100000100066C000
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=154382768;spi-s=92741926;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Route: <sip:l2aykhrmqrls3wwcj6g7e6j3yy@10.80.0.5:5063;transport=tcp;lr;r2=on;did=XRD7U2VCTPNTUUZG;ue>,<sip:l2aykhrmqrls3wwcj6g7e6j3yy@10.80.0.5:5060;lr;r2=on;did=XRD7U2VCTPNTUUZG>,<sip:mt@10.80.0.5:5080;lr;did=5ZTFK5NBWEG5AMWQ>,<sip:mo@10.80.0.5:5080;lr;did=R4U4EG3J7F7VKVMW>,<sip:t7kgpikxbisiecwrwzojjcbryu@10.80.0.5:5060;lr;r2=on;did=W6MQZ3OSVOAPPCMC>,<sip:t7kgpikxbisiecwrwzojjcbryu@10.80.0.5:5063;transport=tcp;lr;r2=on;did=W6MQZ3OSVOAPPCMC;ue>
P-Preferred-Identity: <sip:15550000005@ims.mnc001.mcc001.3gppnetwork.org>
Require: sec-agree
Proxy-Require: sec-agree
Reason: RELEASE_CAUSE ;cause=1 ;text="User ends call"
User-Agent: Core-Z5 N1982U.6.02.09.FR00
Session-ID: d22826c3284554e6a99141f3b92263d2
Content-Length: 0

