SIP/2.0 200 OK
From: <tel:15550000005;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=112583285
To: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=4adeb09b
Contact: <sip:15550000002@10.46.0.7:49171>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting
Call-ID: 4f22af16a24cc6@10.46.0.7
CSeq: 2 BYE
Max-Forwards: 70
Via: SIP/2.0/TCP 10.46.0.8:42225;branch=z9hG4bK4190770178
Accept-Contact: *;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";video
Content-Length: 0
Server: Google_Pixel10a_Android 16_BD6A.251031.001.A4

