SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.24:49165;branch=z9hG4bKb815b8f5a47684b14a908ee8
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=c93814d0
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=gZHTxRMICy
Call-ID: 69b05bfa9481269b@10.46.0.24
CSeq: 2 PRACK
Session-ID: 38c5cf5883ac542794dc32dc9e2067c0
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

