SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKUG6F6VJYPIQSKJZJJAM7CZSURW,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKC4NQMHWGFMKF7ENVT4V56QU7IN,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bKR3O5K3575IRQXKZZIWMCFQ6M5U,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKJ6P5AP2IIVTQSF2MP3EAHATSU2,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKGWFMBHCJWP7L4WHOPIZ7BV33P2,SIP/2.0/TCP 10.46.0.24:49165;branch=z9hG4bK77b9679f66e2dbb1b1a44e21
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=c93814d0
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=gZHTxRMICy
Call-ID: 69b05bfa9481269b@10.46.0.24
CSeq: 1 INVITE
Record-Route: <sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;did=G7NW3CV263564C77;lr;r2=on;transport=tcp;ue>, <sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;did=G7NW3CV263564C77;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=GE2MWKHJ675X3E6S;lr>, <sip:mo@10.80.0.5:5080;did=NUVZHBQMUKZQHLUU;lr>, <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;did=KLBKX475MTBLA2XK;lr;r2=on>, <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;did=KLBKX475MTBLA2XK;lr;r2=on;transport=tcp;ue>
Session-ID: 38c5cf5883ac542794dc32dc9e2067c0
Contact: <sip:10.46.0.25:63507>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.srvcc-alerting;audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Content-Length: 0

