CANCEL tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=c93814d0
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>
Contact: <sip:15550000002@10.46.0.24:49165>;+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video
Call-ID: 69b05bfa9481269b@10.46.0.24
CSeq: 1 CANCEL
Max-Forwards: 70
Via: SIP/2.0/TCP 10.46.0.24:49165;branch=z9hG4bK77b9679f66e2dbb1b1a44e21
Accept-Contact: *;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel"
Content-Length: 0
P-Preferred-Service: urn:urn-7:3gpp-service.ims.icsi.mmtel
Min-SE: 90
P-Preferred-Identity: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010019b01
User-Agent: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Route: <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;transport=tcp;lr;did=KLBKX475MTBLA2XK;r2=on;ue>,<sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;lr;did=KLBKX475MTBLA2XK;r2=on>,<sip:mo@10.80.0.5:5080;lr;did=NUVZHBQMUKZQHLUU>,<sip:mt@10.80.0.5:5080;lr;did=GE2MWKHJ675X3E6S>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;lr;did=G7NW3CV263564C77;r2=on>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;transport=tcp;lr;did=G7NW3CV263564C77;r2=on;ue>
Session-ID: 38c5cf5883ac542794dc32dc9e2067c0
Security-Verify: ipsec-3gpp;q=0.1;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=null;spi-c=259322710;spi-s=69633574;port-c=5064;port-s=5063

