SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKYUVX52X2PAOWLF2UECDFGWPJ7U,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK5XAGMDG7DCSDP4EY37FXMWZIB2,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bKYNARQRVRQMAVIN55H2SAPL3YVD,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKI3C3WGNKSWFUOKNJAMNDJ6SEXJ,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bK6FJAMB6IP3EEDI2J5GWFI2JHFE,SIP/2.0/TCP 10.46.0.13:40279;branch=z9hG4bK2497008001
From: <sip:15550000005@ims.mnc001.mcc001.3gppnetwork.org>;tag=194782
To: <tel:15550000004;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=194988
CSeq: 194775 INVITE
Call-ID: 194775_1760061488@10.46.0.13
Record-Route: <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;transport=tcp;lr;r2=on;did=HJK2HADAP5QEYTHG;ue>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;lr;r2=on;did=HJK2HADAP5QEYTHG>,<sip:mt@10.80.0.5:5080;lr;did=WKWWPFMDML32JVYA>,<sip:mo@10.80.0.5:5080;lr;did=YWBH6GTYVJ5VQAZV>,<sip:mwfvpmdjn5gmmwmnbhkzroke5x@10.80.0.5:5060;lr;r2=on;did=I3VEOOSXBXWVRD4B>,<sip:mwfvpmdjn5gmmwmnbhkzroke5x@10.80.0.5:5063;transport=tcp;lr;r2=on;did=I3VEOOSXBXWVRD4B;ue>
Content-Length: 0
Session-Expires: 1800;refresher=uac
Server: Core-Z5 N1982U.6.02.09.FR00
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015EE0000
Require: timer,100rel
Contact: <sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Supported: 100rel,from-change,tdialog
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

