BYE sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435 SIP/2.0
To: <tel:15550000004;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=194988
From: <sip:15550000005@ims.mnc001.mcc001.3gppnetwork.org>;tag=194782
Call-ID: 194775_1760061488@10.46.0.13
CSeq: 194779 BYE
Via: SIP/2.0/TCP 10.46.0.13:40279;branch=z9hG4bK712161981
Max-Forwards: 70
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015EE0000
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=51912239;spi-s=169938931;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Content-Length: 0
Route: <sip:mwfvpmdjn5gmmwmnbhkzroke5x@10.80.0.5:5063;transport=tcp;lr;r2=on;did=I3VEOOSXBXWVRD4B;ue>,<sip:mwfvpmdjn5gmmwmnbhkzroke5x@10.80.0.5:5060;lr;r2=on;did=I3VEOOSXBXWVRD4B>,<sip:mo@10.80.0.5:5080;lr;did=YWBH6GTYVJ5VQAZV>,<sip:mt@10.80.0.5:5080;lr;did=WKWWPFMDML32JVYA>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;lr;r2=on;did=HJK2HADAP5QEYTHG>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;transport=tcp;lr;r2=on;did=HJK2HADAP5QEYTHG;ue>
P-Preferred-Identity: <sip:15550000005@ims.mnc001.mcc001.3gppnetwork.org>
Reason: RELEASE_CAUSE ;cause=1 ;text="User ends call"
User-Agent: Core-Z5 N1982U.6.02.09.FR00
Require: sec-agree
Proxy-Require: sec-agree

