SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.10:44417;branch=z9hG4bK2376332341
Max-Forwards: 70
Record-Route: <sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5063;transport=tcp;lr;r2=on;did=T6ASTG76EWMGTP4J;ue>
Record-Route: <sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5060;lr;r2=on;did=T6ASTG76EWMGTP4J>
Record-Route: <sip:mt@10.80.0.5:5080;lr;did=HXRZLRZ4VCLXZYMC>
Record-Route: <sip:mo@10.80.0.5:5080;lr;did=HREBAURAXEW2Z6G7>
Record-Route: <sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5060;lr;r2=on;did=NARA3RU62ALLI6BX>
Record-Route: <sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5063;transport=tcp;lr;r2=on;did=NARA3RU62ALLI6BX;ue>
Require: timer
Contact: <sip:15550000007@10.46.0.5:6100>;+sip.instance="<urn:gsma:imei:00000000-000007-0>";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting
To: <tel:15550000007;phone-context=ims.mnc001.mcc999.3gppnetwork.org>;tag=65496c41
From: <sip:15550000008@ims.mnc001.mcc999.3gppnetwork.org>;tag=6695658
Call-ID: 6695652_3070641088@10.46.0.10
CSeq: 6695652 INVITE
Session-Expires: 1800;refresher=uac
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: timer, 100rel, precondition
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
Content-Length: 0
P-Asserted-Identity: <tel:+15550000007>
P-Asserted-Identity: <sip:+15550000007@ims.mnc001.mcc999.3gppnetwork.org;user=phone>

