BYE sip:8476f6db-5c6a-4256-a0dd-69db67bd85bd@10.46.0.10:44417 SIP/2.0
Via: SIP/2.0/UDP 10.46.0.5:6100;branch=z9hG4bK-524287-1---0917b79b85850cc3;rport;transport=UDP
Max-Forwards: 70
Route: <sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5063;transport=tcp;lr;r2=on;did=T6ASTG76EWMGTP4J;ue>
Route: <sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5060;lr;r2=on;did=T6ASTG76EWMGTP4J>
Route: <sip:mt@10.80.0.5:5080;lr;did=HXRZLRZ4VCLXZYMC>
Route: <sip:mo@10.80.0.5:5080;lr;did=HREBAURAXEW2Z6G7>
Route: <sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5060;lr;r2=on;did=NARA3RU62ALLI6BX>
Route: <sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5063;transport=tcp;lr;r2=on;did=NARA3RU62ALLI6BX;ue>
Proxy-Require: sec-agree
Require: sec-agree
To: <sip:15550000008@ims.mnc001.mcc999.3gppnetwork.org>;tag=6695658
From: <tel:15550000007;phone-context=ims.mnc001.mcc999.3gppnetwork.org>;tag=65496c41
Call-ID: 6695652_3070641088@10.46.0.10
CSeq: 2 BYE
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=132102118;spi-s=104856785;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
P-Preferred-Identity: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=9990100010019b01
Content-Length: 0

