SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.46.0.15:43435;branch=z9hG4bK1901442183
From: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>;tag=2787081
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=Mr4KdCcCUm
CSeq: 2787074 INVITE
Call-ID: 2787074_3068573712@10.46.0.15
Record-Route: <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=YSYJBROUP5HBIBLA;lr;r2=on;transport=tcp;ue>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=YSYJBROUP5HBIBLA;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=F2H4B4YNCB4BXZTH;lr>, <sip:mo@10.80.0.5:5080;did=GPBN5ZBRAMU4CUDB;lr>, <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;did=4AXIAFQSPSW2IW6L;lr;r2=on>, <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;did=4AXIAFQSPSW2IW6L;lr;r2=on;transport=tcp;ue>
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.srvcc-alerting;audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0
P-Asserted-Identity: <tel:+15550000006>
P-Asserted-Identity: <sip:+15550000006@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

