SIP/2.0 486 Busy Here
Via: SIP/2.0/TCP 10.46.0.10:44417;branch=z9hG4bK32412383
Max-Forwards: 70
Record-Route: <sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5063;transport=tcp;lr;r2=on;did=RECGJJSC6J6YKNJ7;ue>
Record-Route: <sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5060;lr;r2=on;did=RECGJJSC6J6YKNJ7>
Record-Route: <sip:mt@10.80.0.5:5080;lr;did=3ENOBYBBU7EFN3OG>
Record-Route: <sip:mo@10.80.0.5:5080;lr;did=44AXFMFDT2AQ3R54>
Record-Route: <sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5060;lr;r2=on;did=5YSDZ32Z5G3ZWLQ3>
Record-Route: <sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5063;transport=tcp;lr;r2=on;did=5YSDZ32Z5G3ZWLQ3;ue>
Contact: <sip:15550000007@10.46.0.5:6100>;+sip.instance="<urn:gsma:imei:00000000-000007-0>";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting
To: <tel:15550000007;phone-context=ims.mnc001.mcc999.3gppnetwork.org>;tag=e623af5f
From: <sip:15550000008@ims.mnc001.mcc999.3gppnetwork.org>;tag=6943448
Call-ID: 6943441_3070962960@10.46.0.10
CSeq: 6943441 INVITE
Supported: timer, 100rel, precondition
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
Content-Length: 0

