PRACK sip:656c296f-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.3:46761 SIP/2.0
Via: SIP/2.0/TCP 10.0.0.2:38889;branch=z9hG4bK2UPRPA2DBIVTP644F5RZOWFZRG;rport
Route: <sip:fch555hos5mgc3rtk3lovlciov@10.0.0.1:5063;transport=tcp;lr;r2=on;did=FZSWJSYQHNKIQKTE;ue>, <sip:fch555hos5mgc3rtk3lovlciov@10.0.0.1:5060;lr;r2=on;did=FZSWJSYQHNKIQKTE>, <sip:mo@10.0.0.1:5080;lr;did=N7LFTNTPC2NXBI26>, <sip:mt@10.0.0.1:5080;lr;did=A2I3SFIQA6ZE4743>, <sip:zfh2lgtqhm5cnong5mbtqesooq@10.0.0.1:5060;lr;r2=on;did=3L4C4RBGABTKH2QV>, <sip:zfh2lgtqhm5cnong5mbtqesooq@10.0.0.1:5063;transport=tcp;lr;r2=on;did=3L4C4RBGABTKH2QV;ue>
Max-Forwards: 70
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=2HF5ZK5D4KAQRZ6JB3PGHZITU7
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=E5IHXRG3A5NFRORBJATW6BB25N
Call-ID: 65b27b31-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.2
CSeq: 2 PRACK
RAck: 55886427 1 INVITE
Content-Length: 0
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=239075227;spi-s=42329523;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Require: sec-agree
Proxy-Require: sec-agree
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010000001

