SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.0.0.2:38873;branch=z9hG4bKLRWYEUC4NQH6PVNXVBM3VB3QBM;rport=45067;received=10.0.0.2
Record-Route: <sip:dmigbowgjhlyfhiyff53dy5zs3@10.0.0.1:5063;transport=tcp;lr;r2=on;did=FEYKJQXXSNVWCP2S;ue>
Record-Route: <sip:dmigbowgjhlyfhiyff53dy5zs3@10.0.0.1:5060;lr;r2=on;did=FEYKJQXXSNVWCP2S>
Record-Route: <sip:mt@10.0.0.1:5080;lr;did=M2AXKKAWOOTF57UT>
Record-Route: <sip:mo@10.0.0.1:5080;lr;did=LT3U4N66E27HNAHE>
Record-Route: <sip:7qi7n3eiqts4aak3xd3aop3cjh@10.0.0.1:5060;lr;r2=on;did=5VQT5XXRKLQRRCPG>
Record-Route: <sip:7qi7n3eiqts4aak3xd3aop3cjh@10.0.0.1:5063;transport=tcp;lr;r2=on;did=5VQT5XXRKLQRRCPG;ue>
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=HSE7SBOTEW6WSVPZ2JIJ4LBU6T
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=VCRNG4IJLZ23I4SOC25ITGEEZQ
Call-ID: 45731f74-bf70-11f1-81ff-2bcf73babbc9@10.0.0.2
CSeq: 1 INVITE
Content-Length: 0
Contact: <sip:4542e7f2-bf70-11f1-81ff-2bcf73babbc9@10.0.0.3:35047>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, PRACK, NOTIFY, MESSAGE
Supported: 100rel, timer
Session-Expires: 1800;refresher=uac
Require: timer
P-Asserted-Identity: <tel:+15550002>
P-Asserted-Identity: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

