UPDATE sip:4540d1d8-bf70-11f1-81ff-2bcf73babbc9@10.0.0.2:38873 SIP/2.0
Via: SIP/2.0/TCP 10.0.0.1:5063;branch=z9hG4bK6QXIWV6BCVHGYJJ2CO3M7ZUBL3
Via: SIP/2.0/UDP 10.0.0.1:5080;branch=z9hG4bKP4ZHNNXDNW4URVGSHZQ6OK7J4E
Via: SIP/2.0/UDP 10.0.0.1:5080;branch=z9hG4bK7V4QP6OFWIZDR7BWZZA3JAHZV5
Via: SIP/2.0/UDP 10.0.0.1:5060;branch=z9hG4bKKFZIZVQBYYAYDWGPQHVLFKIPQT
Via: SIP/2.0/TCP 10.0.0.3:35047;branch=z9hG4bKYQPRT4COUKJGQJNFDI7ZNELOCP;rport=38647;received=10.0.0.3
Record-Route: <sip:mo@10.0.0.1:5080;lr;did=LT3U4N66E27HNAHE>
Record-Route: <sip:mt@10.0.0.1:5080;lr;did=M2AXKKAWOOTF57UT>
Max-Forwards: 66
From: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=VCRNG4IJLZ23I4SOC25ITGEEZQ
To: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=HSE7SBOTEW6WSVPZ2JIJ4LBU6T
Call-ID: 45731f74-bf70-11f1-81ff-2bcf73babbc9@10.0.0.2
CSeq: 654186006 UPDATE
Content-Length: 0
Contact: <sip:4542e7f2-bf70-11f1-81ff-2bcf73babbc9@10.0.0.3:35047>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, PRACK, NOTIFY, MESSAGE
Supported: 100rel, timer
Session-Expires: 1800;refresher=uas

