SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.0.0.1:5063;branch=z9hG4bKFLV7RKYWPTED3XPX6W5WVJ22CC
Via: SIP/2.0/UDP 10.0.0.1:5080;branch=z9hG4bK4TINGWMOCNZ4NUIA3XRVDB6PGG
Via: SIP/2.0/UDP 10.0.0.1:5080;branch=z9hG4bKMSZ4TJK6IDHJTZ4LD3MT6GANTD
Via: SIP/2.0/UDP 10.0.0.1:5060;branch=z9hG4bKEKGCYI2MBNXSEQXEBITTJ5U5HD
Via: SIP/2.0/TCP 10.0.0.3:46761;branch=z9hG4bKZ4SD76ZRMTAKRGVKWFY6H4IDJ6;rport=36435;received=10.0.0.3
Record-Route: <sip:fch555hos5mgc3rtk3lovlciov@10.0.0.1:5063;transport=tcp;lr;r2=on;did=FZSWJSYQHNKIQKTE;ue>
Record-Route: <sip:fch555hos5mgc3rtk3lovlciov@10.0.0.1:5060;lr;r2=on;did=FZSWJSYQHNKIQKTE>
Record-Route: <sip:mo@10.0.0.1:5080;lr;did=N7LFTNTPC2NXBI26>
Record-Route: <sip:mt@10.0.0.1:5080;lr;did=A2I3SFIQA6ZE4743>
Record-Route: <sip:zfh2lgtqhm5cnong5mbtqesooq@10.0.0.1:5060;lr;r2=on;did=3L4C4RBGABTKH2QV>
Record-Route: <sip:zfh2lgtqhm5cnong5mbtqesooq@10.0.0.1:5063;transport=tcp;lr;r2=on;did=3L4C4RBGABTKH2QV;ue>
From: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=E5IHXRG3A5NFRORBJATW6BB25N
To: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=2HF5ZK5D4KAQRZ6JB3PGHZITU7
Call-ID: 65b27b31-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.2
CSeq: 931649229 UPDATE
Content-Length: 0
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010000001
Contact: <sip:656a56a9-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.2:38889>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, PRACK, NOTIFY, MESSAGE
Session-Expires: 1800;refresher=uas
Require: timer

