BYE sip:4540d1d8-bf70-11f1-81ff-2bcf73babbc9@10.0.0.2:38873 SIP/2.0
Via: SIP/2.0/UDP 10.0.0.3:35047;branch=z9hG4bKU2HQEASAEFKLWXPMJVIYE3VQRQ;rport
Route: <sip:dmigbowgjhlyfhiyff53dy5zs3@10.0.0.1:5063;transport=tcp;lr;r2=on;did=FEYKJQXXSNVWCP2S;ue>, <sip:dmigbowgjhlyfhiyff53dy5zs3@10.0.0.1:5060;lr;r2=on;did=FEYKJQXXSNVWCP2S>, <sip:mt@10.0.0.1:5080;lr;did=M2AXKKAWOOTF57UT>, <sip:mo@10.0.0.1:5080;lr;did=LT3U4N66E27HNAHE>, <sip:7qi7n3eiqts4aak3xd3aop3cjh@10.0.0.1:5060;lr;r2=on;did=5VQT5XXRKLQRRCPG>, <sip:7qi7n3eiqts4aak3xd3aop3cjh@10.0.0.1:5063;transport=tcp;lr;r2=on;did=5VQT5XXRKLQRRCPG;ue>
Max-Forwards: 70
From: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=VCRNG4IJLZ23I4SOC25ITGEEZQ
To: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=HSE7SBOTEW6WSVPZ2JIJ4LBU6T
Call-ID: 45731f74-bf70-11f1-81ff-2bcf73babbc9@10.0.0.2
CSeq: 654186007 BYE
Content-Length: 0
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=114928989;spi-s=167805447;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Require: sec-agree
Proxy-Require: sec-agree
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010000001

