PRACK sip:10.46.0.17:61189 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bK47NIVTOXUFZSANZ7HP3SIC5O2C
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKR4U7ZCCCOVSG2U5SYDSNJHI5FQ
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKFZ7VH7YAH7AWK7YG77FDBSM262
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bK2FDYWVI4WT4SFNHEZCAPIKIKDR
RAck: 1 1 INVITE
To: <tel:+15550000006>;tag=hCj5citYZC
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=qFoDhZ8t3I
Call-ID: CbGVybVmwugZ5NcE1udfVl2Z
Session-ID: 214e9273547593d0a7821e7caa4e266d
Contact: <sip:10.46.0.19:54286>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 2 PRACK
Via: SIP/2.0/UDP 10.46.0.19:54286;branch=z9hG4bKSLxwpCqNVNLhFLj;rport=54286;received=10.46.0.19
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

