SIP/2.0 200 OK
Via: SIP/2.0/UDP 10.46.0.19:54286;branch=z9hG4bKSLxwpCqNVNLhFLj;received=10.46.0.19;rport=54286
To: <tel:+15550000006>;tag=hCj5citYZC
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=qFoDhZ8t3I
Call-ID: CbGVybVmwugZ5NcE1udfVl2Z
Session-ID: 214e9273547593d0a7821e7caa4e266d
CSeq: 2 PRACK
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

