BYE sip:10.46.0.19:54286 SIP/2.0
Via: SIP/2.0/UDP 10.80.0.5:5063;branch=z9hG4bKHKNVSIVCITUOJ2DRJYNKEMVKQY
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKW3JC4727BM7T3EPKVOFM2WPQLE
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKBPGA6PJE33MCB2JDCDZEJ3TKT7
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKVN6ZYUOTWFMJA3MCTPOMP3FGSF
Reason: SIP;cause=200;text="User Triggered"
To: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=qFoDhZ8t3I
From: <tel:+15550000006>;tag=hCj5citYZC
Call-ID: CbGVybVmwugZ5NcE1udfVl2Z
Session-ID: 214e9273547593d0a7821e7caa4e266d
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 1 BYE
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKXrvRakFOWRkvpzK;rport=57130;received=10.46.0.17
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

