BYE sip:2da86196-c8f7-4939-af8b-fbdac4e983f2@10.46.0.8:42225 SIP/2.0
To: <sip:15550000005@ims.mnc001.mcc001.3gppnetwork.org>;tag=111129102
From: <tel:15550000008;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=111129380
Call-ID: 111129095_1760121744@10.46.0.8
CSeq: 111129096 BYE
Via: SIP/2.0/TCP 10.46.0.9:43885;branch=z9hG4bK2312982919
Max-Forwards: 70
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=0010100000100066C000
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=90814459;spi-s=59532002;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Route: <sip:nsbgwhufa64gwwi7ngbk7jry6d@10.80.0.5:5063;transport=tcp;lr;r2=on;did=UADNKONHYWGY3ZQG;ue>,<sip:nsbgwhufa64gwwi7ngbk7jry6d@10.80.0.5:5060;lr;r2=on;did=UADNKONHYWGY3ZQG>,<sip:mt@10.80.0.5:5080;lr;did=XI53LLJHEXYGXJ7S>,<sip:mo@10.80.0.5:5080;lr;did=BLJOGDFGWN6KFWQH>,<sip:l2aykhrmqrls3wwcj6g7e6j3yy@10.80.0.5:5060;lr;r2=on;did=LL6SDLDVCSAJDYPS>,<sip:l2aykhrmqrls3wwcj6g7e6j3yy@10.80.0.5:5063;transport=tcp;lr;r2=on;did=LL6SDLDVCSAJDYPS;ue>
P-Preferred-Identity: <sip:15550000008@ims.mnc001.mcc001.3gppnetwork.org>
Require: sec-agree
Proxy-Require: sec-agree
Reason: RELEASE_CAUSE ;cause=1 ;text="User ends call"
User-Agent: PRD-IR92/12 term-Motorola/XT2417-1-V1UFN35H.193-20 device-type/smart-phone
Content-Length: 0

