PRACK sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435 SIP/2.0
RAck: 1 1 INVITE
To: <tel:+15550000004>;tag=2174542
Route: <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=MBJR2L6DI2TMOCR3;lr;r2=on;transport=tcp;ue>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=MBJR2L6DI2TMOCR3;lr;r2=on>, <sip:mo@10.80.0.5:5080;did=F2W6SLKFQSUXMEJP;lr>, <sip:mt@10.80.0.5:5080;did=4Q4IZ4EGPM2LPYDR;lr>, <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;did=SUIG74YXVNE7TLHS;lr;r2=on>, <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;did=SUIG74YXVNE7TLHS;lr;r2=on;transport=tcp;ue>
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=jSRKFYfs1s
Call-ID: Nsgc5oCtKjgMI5fk2MHu6AqX
Session-ID: 028701512bb6973064df15a13a42ee46
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 2 PRACK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKyDgk1Lm5mCCLUrg;rport
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5064;port-s=5063;prot=esp;q=0.1;spi-c=189860270;spi-s=88237557
Require: sec-agree
Proxy-Require: sec-agree
Content-Length: 0

