SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKyDgk1Lm5mCCLUrg;rport=57130;received=10.46.0.17
To: <tel:+15550000004>;tag=2174542
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=jSRKFYfs1s
Call-ID: Nsgc5oCtKjgMI5fk2MHu6AqX
Session-ID: 028701512bb6973064df15a13a42ee46
CSeq: 2 PRACK
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
Supported: 100rel,from-change,tdialog
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

