SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bK5COQUIWRGAFHSSSL7B6LZDTQNO,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKMCOIUSR2AQ3FNIYJGJHKEN6CLJ,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bKDKJIWSRMRIOBARYUSXNYJLAOHR,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKCOS5LFUFB7U2XX2ZTKQZW3I6WC,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKS7LY2V6YJPDU2464FGNSXV4X2D,SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKcg0amJ6bzf7S3kj;rport=57130;received=10.46.0.17
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=jSRKFYfs1s
To: <tel:+15550000004>;tag=2174542
Call-ID: Nsgc5oCtKjgMI5fk2MHu6AqX
Session-ID: 028701512bb6973064df15a13a42ee46
CSeq: 1 INVITE
Record-Route: <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;transport=tcp;lr;r2=on;did=SUIG74YXVNE7TLHS;ue>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;lr;r2=on;did=SUIG74YXVNE7TLHS>,<sip:mt@10.80.0.5:5080;lr;did=4Q4IZ4EGPM2LPYDR>,<sip:mo@10.80.0.5:5080;lr;did=F2W6SLKFQSUXMEJP>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;lr;r2=on;did=MBJR2L6DI2TMOCR3>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;transport=tcp;lr;r2=on;did=MBJR2L6DI2TMOCR3;ue>
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
RSeq: 2
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015EE0000
Contact: <sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

