ACK tel:+15550000004 SIP/2.0
Call-ID: Nsgc5oCtKjgMI5fk2MHu6AqX
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=jSRKFYfs1s
Route: <sip:10.80.0.5:5063;lr>, <sip:orig-26@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
CSeq: 1 ACK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKcg0amJ6bzf7S3kj;rport
To: <tel:+15550000004>;tag=2174542
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5064;port-s=5063;prot=esp;q=0.1;spi-c=189860270;spi-s=88237557
Require: sec-agree
Proxy-Require: sec-agree
Content-Length: 0

