PRACK sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKGXIRHZ6TEF5J3UTMBQKIIC4BYL
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKTEOL7NP4VOQKGAKPHO5DKUT3OT
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKYR2J7BD32NUENCART5OL7HIKI7
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKNOZWJU7P7RWI35KV3BFGBIYP6N
RAck: 2 1 INVITE
To: <tel:+15550000004>;tag=2029281
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=phGRFFh1Oz
Call-ID: XLSDSgMpObRgVituc0pOtPU2
Session-ID: b9ef98e3980320464cdc5f1eb9bf4d05
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 4 PRACK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKi1zOHUdYCesVRzx;rport=57130;received=10.46.0.17
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

