BYE sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKATJHYSGDEZ7KECXGCAJW37HW2L
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKEXNHZOC4EUZIV46AAZEUTCTNND
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKHXPGBBMWA3622BNWRVP35C2RSV
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKTZ3NPUGPJVYOU55HY2XAI5363H
Reason: SIP;cause=200;text="User Triggered"
To: <tel:+15550000004>;tag=2029281
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=phGRFFh1Oz
Call-ID: XLSDSgMpObRgVituc0pOtPU2
Session-ID: b9ef98e3980320464cdc5f1eb9bf4d05
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 5 BYE
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKOjrGE6V1PC1ms8a;rport=57130;received=10.46.0.17
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

