SIP/2.0 200 OK
From: <sip:15550000005@ims.mnc001.mcc001.3gppnetwork.org>;tag=103310767
To: <tel:15550000002;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=b3bbc289
Contact: <sip:15550000002@10.46.0.3:49165>;+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video
Call-ID: 103310760_1760534736@10.46.0.2
CSeq: 103310761 PRACK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKJNXE7II4UQOCMXIU6XUNIHXTAL,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK4YZF64KO4L4XEGIIRKHLSDDFX7,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKQ772PON42G5LGER7S3376MW6GF,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bK6GPHRIDKHRQXCPIFZUWVGURNQO,SIP/2.0/TCP 10.46.0.2:43300;branch=z9hG4bK1756472131
Content-Length: 0
Allow: INVITE,CANCEL,UPDATE,PRACK,BYE,ACK,MESSAGE,SUBSCRIBE,NOTIFY,PUBLISH,REFER,INFO,OPTIONS
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=0010100000100066c000
Server: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Require: precondition
Record-Route: <sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5063;transport=tcp;lr;r2=on;ob;did=P3M3RQZAT22TNGN3;ue>,<sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5060;lr;r2=on;ob;did=P3M3RQZAT22TNGN3>,<sip:mt@10.80.0.5:5080;lr;did=I74XPGSQO32BRJPH>,<sip:mo@10.80.0.5:5080;lr;did=YHNIGHXT5KSXB5PT>,<sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5060;lr;r2=on;did=KRJRUFGOJHVZWXI2>,<sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5063;transport=tcp;lr;r2=on;did=KRJRUFGOJHVZWXI2;ue>

