PRACK sip:10.46.0.17:61189 SIP/2.0
From: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>;tag=2285999
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=xlYCbExxPl
CSeq: 2285994 PRACK
Call-ID: 2285993_3069112144@10.46.0.15
Content-Length: 0
Via: SIP/2.0/TCP 10.46.0.15:43435;branch=z9hG4bK888926082
Max-Forwards: 70
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015EE0000
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=113224940;spi-s=105724704;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
RAck: 1 2285993 INVITE
Route: <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;did=D3QLDSGEZTLKUJJE;lr;r2=on;transport=tcp;ue>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;did=D3QLDSGEZTLKUJJE;lr;r2=on>,<sip:mo@10.80.0.5:5080;did=GBN5MJRLAQ7OKFUP;lr>,<sip:mt@10.80.0.5:5080;did=WDR4TWYSLKD4FGVV;lr>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=OZ5L5WPXEWEZT5DE;lr;r2=on>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=OZ5L5WPXEWEZT5DE;lr;r2=on;transport=tcp;ue>
User-Agent: Core-Z5 N1982U.6.02.09.FR00
Proxy-Require: sec-agree
Require: sec-agree
Supported: timer

