SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKFR7RT5XSHS6GFLSXFINNNUJLB2,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKBR5X2K7QHZW6G3ZIATTUYS7D46,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bKUQSETJKE7RJM3RR7SUTY7SSGUN,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKNILFBP4UE7DG53CENYPPQTNLRK,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKFNTMA2G4X5OJ7JYMEATKQXJNE4,SIP/2.0/TCP 10.46.0.15:43435;branch=z9hG4bK815309176
From: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>;tag=2285999
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=xlYCbExxPl
CSeq: 2285993 INVITE
Call-ID: 2285993_3069112144@10.46.0.15
Record-Route: <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=OZ5L5WPXEWEZT5DE;lr;r2=on;transport=tcp;ue>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=OZ5L5WPXEWEZT5DE;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=WDR4TWYSLKD4FGVV;lr>, <sip:mo@10.80.0.5:5080;did=GBN5MJRLAQ7OKFUP;lr>, <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;did=D3QLDSGEZTLKUJJE;lr;r2=on>, <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;did=D3QLDSGEZTLKUJJE;lr;r2=on;transport=tcp;ue>
Supported: 100rel,path,replaces,timer
Session-Expires: 1800;refresher=uac
Require: timer
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Content-Length: 0

