BYE sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKSTTOROMAUMUURBWP3QBZWAGZCA
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKESKB6COLBTOOVGIXEKWMIROT6U
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKAOZW5NKXGNEDP2N5GQMUINJ2J4
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKAIJQAKY2T5E3DDLXATRMVOX2FI
Reason: SIP;cause=200;text="User Triggered"
To: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>;tag=2285999
From: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=xlYCbExxPl
Call-ID: 2285993_3069112144@10.46.0.15
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 1 BYE
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bK8dXxzk52a4cc3iX;rport=57130;received=10.46.0.17
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

