PRACK sip:10.46.0.20:53718 SIP/2.0
Via: SIP/2.0/UDP 10.80.0.5:5063;branch=z9hG4bK5342TFH7COGYYEZF2FHCE27TN5
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK6CZEC3CJQWN3PZ5WNUKWIQK756
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKSFXNWSQJ2BJHO2N5KA5I7NUQ3Q
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bK53S3LP4T4XFZLD2T5VZSVV47Q7
RAck: 1 1 INVITE
To: <tel:+15550000003>;tag=WggUN1Zgez
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=QpGE5TQdRl
Call-ID: 7AYWxgGuWtCDMe2swNwRLn0O
Session-ID: e0b84dc8daec4660b4ba3b9aac28b3ea
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 2 PRACK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKLybdRTEWPcJjeJG;rport=57130;received=10.46.0.17
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

