SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKpCO1EWzkOkOA9SC;received=10.46.0.17;rport=57130
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=QpGE5TQdRl
To: <tel:+15550000003>;tag=WggUN1Zgez
Call-ID: 7AYWxgGuWtCDMe2swNwRLn0O
Session-ID: e0b84dc8daec4660b4ba3b9aac28b3ea
CSeq: 1 INVITE
Record-Route: <sip:yxlpwprxmpbiklyoarggpjtb5s@10.80.0.5:5063;did=X4DXWDQSXPCZTKXY;lr;r2=on;ue>, <sip:yxlpwprxmpbiklyoarggpjtb5s@10.80.0.5:5060;did=X4DXWDQSXPCZTKXY;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=RUUS54IDH4PXEBYQ;lr>, <sip:mo@10.80.0.5:5080;did=ZZUFNMQ2CX6GKUJL;lr>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=YYUA6UBAVLV4MUSX;lr;r2=on>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=YYUA6UBAVLV4MUSX;lr;r2=on;transport=tcp;ue>
Require: 100rel
RSeq: 2
Contact: <sip:10.46.0.20:53718>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.srvcc-alerting;audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0
P-Asserted-Identity: <tel:+15550000003>
P-Asserted-Identity: <sip:+15550000003@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

