ACK sip:10.46.0.20:53718 SIP/2.0
To: <tel:+15550000003>;tag=WggUN1Zgez
Route: <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=YYUA6UBAVLV4MUSX;lr;r2=on;transport=tcp;ue>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=YYUA6UBAVLV4MUSX;lr;r2=on>, <sip:mo@10.80.0.5:5080;did=ZZUFNMQ2CX6GKUJL;lr>, <sip:mt@10.80.0.5:5080;did=RUUS54IDH4PXEBYQ;lr>, <sip:yxlpwprxmpbiklyoarggpjtb5s@10.80.0.5:5060;did=X4DXWDQSXPCZTKXY;lr;r2=on>, <sip:yxlpwprxmpbiklyoarggpjtb5s@10.80.0.5:5063;did=X4DXWDQSXPCZTKXY;lr;r2=on;ue>
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=QpGE5TQdRl
Call-ID: 7AYWxgGuWtCDMe2swNwRLn0O
Session-ID: e0b84dc8daec4660b4ba3b9aac28b3ea
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 1 ACK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKAYwrLbbr3CIYnbb;rport
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5064;port-s=5063;prot=esp;q=0.1;spi-c=189860270;spi-s=88237557
Require: sec-agree
Proxy-Require: sec-agree
Content-Length: 0

