BYE sip:10.46.0.20:53718 SIP/2.0
Via: SIP/2.0/UDP 10.80.0.5:5063;branch=z9hG4bKAUAWO76RST7TM5HLDGD2XYZVS2
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKTYBERD7GY6FC2RWJ4LXQGQWGBU
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKQ5HALCXE7RBXFNQSXOXPYBIAKU
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKLXPDSSRZKEOOH53A4NO3Y2OPOL
Reason: SIP;cause=200;text="User Triggered"
To: <tel:+15550000003>;tag=WggUN1Zgez
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=QpGE5TQdRl
Call-ID: 7AYWxgGuWtCDMe2swNwRLn0O
Session-ID: e0b84dc8daec4660b4ba3b9aac28b3ea
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 5 BYE
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bK2Tx7r551dP89f6h;rport=57130;received=10.46.0.17
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

