SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.46.0.8:42225;branch=z9hG4bK735318805
From: <sip:15550000005@ims.mnc001.mcc001.3gppnetwork.org>;tag=111319409
To: <tel:15550000008;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=111319698
CSeq: 111319402 INVITE
Call-ID: 111319402_1761473040@10.46.0.8
Record-Route: <sip:nsbgwhufa64gwwi7ngbk7jry6d@10.80.0.5:5063;transport=tcp;lr;r2=on;did=KEIQ7AUMVIAEI7KE;ue>,<sip:nsbgwhufa64gwwi7ngbk7jry6d@10.80.0.5:5060;lr;r2=on;did=KEIQ7AUMVIAEI7KE>,<sip:mt@10.80.0.5:5080;lr;did=XFM6GZDIASPZJWPX>,<sip:mo@10.80.0.5:5080;lr;did=4BHLROODLRCP3SS5>,<sip:l2aykhrmqrls3wwcj6g7e6j3yy@10.80.0.5:5060;lr;r2=on;did=6ELVBEC7G6227QEB>,<sip:l2aykhrmqrls3wwcj6g7e6j3yy@10.80.0.5:5063;transport=tcp;lr;r2=on;did=6ELVBEC7G6227QEB;ue>
Content-Length: 0
Server: PRD-IR92/12 term-Motorola/XT2417-1-V1UFN35H.193-20 device-type/smart-phone
RSeq: 2
Contact: <sip:a87a2e9a-4c32-439f-afc0-825ea2f8b236@10.46.0.9:43885>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
P-Asserted-Identity: <tel:+15550000008>
P-Asserted-Identity: <sip:+15550000008@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

