SIP/2.0 200 OK
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=N9VFxKYIi7
To: <tel:+15550000002>;tag=10f68f23
Contact: <sip:15550000002@10.46.0.24:49165>;+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video
Call-ID: Vp5lvr2fZa3rj8x005nYYEPM
CSeq: 2 PRACK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKKG3FRCQ7LPA465B6ZLC6FQ37VR,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKQ6CRMG443KQUWYBU4PDZBRWQUF,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKGIQLSS3PBTUNABDBDAY2PPOGQ6,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKZGJRKLD65P2AO4RXJPKULCIUAT,SIP/2.0/TCP 10.46.0.25:63507;received=10.46.0.25;branch=z9hG4bK2Vnxoy04h3Zzx7H;rport=64105
Content-Length: 0
Allow: INVITE,CANCEL,UPDATE,PRACK,BYE,ACK,MESSAGE,SUBSCRIBE,NOTIFY,PUBLISH,REFER,INFO,OPTIONS
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010019b01
Server: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Require: precondition
Record-Route: <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;transport=tcp;lr;r2=on;ob;did=5FM5CGBUFV4OODSU;ue>,<sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;lr;r2=on;ob;did=5FM5CGBUFV4OODSU>,<sip:mt@10.80.0.5:5080;lr;did=NW5S4KKIPFQWPQUA>,<sip:mo@10.80.0.5:5080;lr;did=KACYVEHWOAQWQUXS>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;lr;r2=on;did=HWFAUINCWZVHSK4D>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;transport=tcp;lr;r2=on;did=HWFAUINCWZVHSK4D;ue>
Session-ID: 81ea83e819dd815b4cc760f421299969

