SIP/2.0 487 Request Terminated
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=N9VFxKYIi7
To: <tel:+15550000002>;tag=10f68f23
Call-ID: Vp5lvr2fZa3rj8x005nYYEPM
CSeq: 1 INVITE
Via: SIP/2.0/TCP 10.46.0.25:63507;received=10.46.0.25;branch=z9hG4bKpJ8Du7v3SmDc1Cp;rport=64105
Content-Length: 0
Server: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Record-Route: <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;transport=tcp;lr;did=5FM5CGBUFV4OODSU;ob;r2=on;ue>,<sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;lr;did=5FM5CGBUFV4OODSU;ob;r2=on>,<sip:mt@10.80.0.5:5080;lr;did=NW5S4KKIPFQWPQUA>,<sip:mo@10.80.0.5:5080;lr;did=KACYVEHWOAQWQUXS>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;lr;did=HWFAUINCWZVHSK4D;r2=on>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;transport=tcp;lr;did=HWFAUINCWZVHSK4D;r2=on;ue>
Session-ID: 81ea83e819dd815b4cc760f421299969

