PRACK sip:3b7d83d2-0108-4629-a2dd-0f4c6e59a52d@10.46.0.6:40117 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bK2QZRX3HOKPDFH4FHJUBDFMSGSY
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKZMCQL6EQFJFP2AQNT3QV55WWDC
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKVIAVMHQD32HRC4AO5RJRETDBC3
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKAFM6JOBNHSNUDD3YIXANYD3Q4G
Via: SIP/2.0/UDP 10.46.0.5:6500;branch=z9hG4bK-524287-1---3619d168ae93ea9e;rport=6500;transport=UDP;received=10.46.0.5
Max-Forwards: 66
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=99052249
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=551cef53
Call-ID: cq2bdNGeGUuZz-QZvV6utw..@10.46.0.5
CSeq: 4 PRACK
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
RAck: 2 1 INVITE
Content-Length: 0

