SIP/2.0 200 OK
Via: SIP/2.0/UDP 10.46.0.5:6500;branch=z9hG4bK-524287-1---3619d168ae93ea9e;rport=6500;transport=UDP;received=10.46.0.5
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=99052249
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=551cef53
Call-ID: cq2bdNGeGUuZz-QZvV6utw..@10.46.0.5
CSeq: 4 PRACK
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
Supported: 100rel,from-change,tdialog
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

