BYE sip:15550000007@10.46.0.5:6500 SIP/2.0
To: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=551cef53
From: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=99052249
Call-ID: cq2bdNGeGUuZz-QZvV6utw..@10.46.0.5
CSeq: 2 BYE
Via: SIP/2.0/TCP 10.46.0.6:40117;branch=z9hG4bK1501031775
Max-Forwards: 70
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=9990100000100066C000
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=93934172;spi-s=126429968;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Route: <sip:a4jyxqxxrkgzk5gcxwc37cj5mu@10.80.0.5:5063;transport=tcp;lr;r2=on;did=YKQTOSJSBY5MM6SY;ue>,<sip:a4jyxqxxrkgzk5gcxwc37cj5mu@10.80.0.5:5060;lr;r2=on;did=YKQTOSJSBY5MM6SY>,<sip:mt@10.80.0.5:5080;lr;did=ECKPY734NSIBAK5Q>,<sip:mo@10.80.0.5:5080;lr;did=YLRXN2OJ2SHUOG4S>,<sip:yuvey7vgymc2aajptku4giz3c7@10.80.0.5:5060;lr;r2=on;did=BGW57IAEJAAWUT2W>,<sip:yuvey7vgymc2aajptku4giz3c7@10.80.0.5:5063;transport=tcp;lr;r2=on;did=BGW57IAEJAAWUT2W;ue>
P-Preferred-Identity: <sip:15550000008@ims.mnc001.mcc999.3gppnetwork.org>
Require: sec-agree
Proxy-Require: sec-agree
Reason: RELEASE_CAUSE ;cause=1 ;text="User ends call"
User-Agent: Core-Z5 N1982U.6.02.09.FR00
Content-Length: 0

