SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKOOAXUWP73L7I4EQHZ77OLOQ6H3
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKKFWBFSMEATPMYBUPGYJW7LWVSB
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKQP5WUDW7HO3Q5BZSOQCFZNGM7F
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKST5N5K2W4W234MFHWUVBDS7VK4
Via: SIP/2.0/TCP 10.46.0.6:40117;branch=z9hG4bK1501031775
Max-Forwards: 70
Contact: <sip:15550000007@10.46.0.5:6500>;+sip.instance="<urn:gsma:imei:00000000-000007-0>";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting
To: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=551cef53
From: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=99052249
Call-ID: cq2bdNGeGUuZz-QZvV6utw..@10.46.0.5
CSeq: 2 BYE
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=9990100000100066c000
Content-Length: 0

