SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.46.0.14:40265;branch=z9hG4bK433122552
From: <sip:15550000001@ims.mnc001.mcc001.3gppnetwork.org>;tag=714593
To: <sip:15550000004;phone-context=ims.mnc001.mcc001.3gppnetwork.org@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=715026
CSeq: 714586 INVITE
Call-ID: 714586_4111201712@10.46.0.14
Record-Route: <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;transport=tcp;lr;r2=on;did=WBHZ5CXBTNINNCXK;ue>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;lr;r2=on;did=WBHZ5CXBTNINNCXK>,<sip:mt@10.80.0.5:5080;lr;did=CN5VYNJ7TIKGNMSI>,<sip:mo@10.80.0.5:5080;lr;did=7OAQAI477SM3ORMU>,<sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5060;lr;r2=on;did=5NBGRQBGJZQUKTP2>,<sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5063;transport=tcp;lr;r2=on;did=5NBGRQBGJZQUKTP2;ue>
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
RSeq: 2
Contact: <sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
P-Asserted-Identity: <tel:+15550000004>
P-Asserted-Identity: <sip:+15550000004@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

