BYE sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435 SIP/2.0
To: <sip:15550000004;phone-context=ims.mnc001.mcc001.3gppnetwork.org@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=715026
From: <sip:15550000001@ims.mnc001.mcc001.3gppnetwork.org>;tag=714593
Call-ID: 714586_4111201712@10.46.0.14
CSeq: 714590 BYE
Via: SIP/2.0/TCP 10.46.0.14:40265;branch=z9hG4bK3246409931
Max-Forwards: 70
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015EE0000
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=165898036;spi-s=190332794;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Content-Length: 0
Route: <sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5063;transport=tcp;lr;r2=on;did=5NBGRQBGJZQUKTP2;ue>,<sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5060;lr;r2=on;did=5NBGRQBGJZQUKTP2>,<sip:mo@10.80.0.5:5080;lr;did=7OAQAI477SM3ORMU>,<sip:mt@10.80.0.5:5080;lr;did=CN5VYNJ7TIKGNMSI>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;lr;r2=on;did=WBHZ5CXBTNINNCXK>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;transport=tcp;lr;r2=on;did=WBHZ5CXBTNINNCXK;ue>
P-Preferred-Identity: <sip:15550000001@ims.mnc001.mcc001.3gppnetwork.org>
Reason: RELEASE_CAUSE ;cause=1 ;text="User ends call"
User-Agent: PRD-IR92/12 term-Motorola/XT2417-1-V1UFN35H.193-20 device-type/smart-phone
Require: sec-agree
Proxy-Require: sec-agree

