REGISTER sip:ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
From: <sip:001010000000001@ims.mnc001.mcc001.3gppnetwork.org>;tag=3049359
To: <sip:001010000000001@ims.mnc001.mcc001.3gppnetwork.org>
CSeq: 49937 REGISTER
Call-ID: 49935_4109409888@10.46.0.14
Via: SIP/2.0/TCP 10.46.0.14:40265;branch=z9hG4bK1689010201
Max-Forwards: 70
Contact: <sip:59ca0608-182c-4e87-aed8-aa1e2a898c87@10.46.0.14:40265>;+g.3gpp.accesstype="cellular2";+sip.instance="<urn:gsma:imei:00000000-000001-0>";+g.3gpp.ps-data-off="inactive";audio;+g.3gpp.nw-init-ussi;+g.3gpp.smsip;video;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel"
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015EE0000
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=165898036;spi-s=190332794;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Expires: 600000
Require: sec-agree
Proxy-Require: sec-agree
Supported: path,sec-agree
Allow: INVITE,BYE,CANCEL,ACK,NOTIFY,UPDATE,PRACK,INFO,MESSAGE,OPTIONS
Authorization: Digest username="001010000000001@ims.mnc001.mcc001.3gppnetwork.org",realm="ims.mnc001.mcc001.3gppnetwork.org",uri="sip:ims.mnc001.mcc001.3gppnetwork.org",qop=auth,nonce="ldMNPh9Cr6oxjMl7SJoH2YvgOZi/CoAAg9gIlp6IS5I=",nc=00000002,cnonce="49917",algorithm=AKAv1-MD5,response="feceb7ee13705c87d9c8717cb58a9b2f"
User-Agent: PRD-IR92/12 term-Motorola/XT2417-1-V1UFN35H.193-20 device-type/smart-phone
Security-Client: ipsec-3gpp; alg=hmac-md5-96; ealg=des-ede3-cbc; spi-c=4089712216; spi-s=940743540; port-c=42947; port-s=40265,ipsec-3gpp; alg=hmac-md5-96; ealg=aes-cbc; spi-c=4089712216; spi-s=940743540; port-c=42947; port-s=40265,ipsec-3gpp; alg=hmac-md5-96; ealg=null; spi-c=4089712216; spi-s=940743540; port-c=42947; port-s=40265,ipsec-3gpp; alg=hmac-sha-1-96; ealg=des-ede3-cbc; spi-c=4089712216; spi-s=940743540; port-c=42947; port-s=40265,ipsec-3gpp; alg=hmac-sha-1-96; ealg=aes-cbc; spi-c=4089712216; spi-s=940743540; port-c=42947; port-s=40265,ipsec-3gpp; alg=hmac-sha-1-96; ealg=null; spi-c=4089712216; spi-s=940743540; port-c=42947; port-s=40265
Content-Length: 0

