PRACK sip:10.46.0.20:53718 SIP/2.0
Via: SIP/2.0/UDP 10.80.0.5:5063;branch=z9hG4bKNDRUDNB4WCDDTYLW34ZO3ICGKR
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKEB5R6IULZ6GKMIEDLKCSPDLO6G
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKNTG57OEHH34U4NUZS2MOO2BY2M
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKTZNUDSMZSPF4URYUGBZBHVHPBL
RAck: 1 1 INVITE
To: <tel:+15550000003>;tag=6M2cC6shoR
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=JfQdEX0VUc
Call-ID: gUiVFxQ4a0Ah6UrdbS8lTcmy
Session-ID: 5fbc98a363d0ccc4ad24641f83c911c7
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 2 PRACK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKCjP9UC2sFFD6AiK;rport=57130;received=10.46.0.17
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

