SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bK5KQVHPARSLW6MJR2XXMAHMXAC4,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK76VPCTSPG2I53XAEDNYCLL4RHR,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bK2RNVCURWYZTDVC4DYS3NVCTJY6,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKYIGL2GKC6P62U3WZAQ5ICVKRWA,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKBUWD2NWUQCDKNHGDZCXMFDEHAF,SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKAERWfGEXGQdwEk5;received=10.46.0.17;rport=57130
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=JfQdEX0VUc
To: <tel:+15550000003>;tag=6M2cC6shoR
Call-ID: gUiVFxQ4a0Ah6UrdbS8lTcmy
Session-ID: 5fbc98a363d0ccc4ad24641f83c911c7
CSeq: 1 INVITE
Record-Route: <sip:yxlpwprxmpbiklyoarggpjtb5s@10.80.0.5:5063;did=ZB25FCIOS5KMME6C;lr;r2=on;ue>, <sip:yxlpwprxmpbiklyoarggpjtb5s@10.80.0.5:5060;did=ZB25FCIOS5KMME6C;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=XK5SSXCAFFQYR3Z6;lr>, <sip:mo@10.80.0.5:5080;did=PWN32BO6FZUKSXZO;lr>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=QQGC5BFXP6ZX3JKD;lr;r2=on>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=QQGC5BFXP6ZX3JKD;lr;r2=on;transport=tcp;ue>
Require: 100rel
RSeq: 2
Contact: <sip:10.46.0.20:53718>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.srvcc-alerting;audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Content-Length: 0

