SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKLoDpgVud6wirNvj;received=10.46.0.17;rport=57130
To: <tel:+15550000003>;tag=6M2cC6shoR
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=JfQdEX0VUc
Call-ID: gUiVFxQ4a0Ah6UrdbS8lTcmy
Session-ID: 5fbc98a363d0ccc4ad24641f83c911c7
CSeq: 4 PRACK
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

