SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKX3BWSFG6WLPGUO4MK7P7PIWTMD,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKKVDNHBPOSVRNCUWGQD4PEF27VQ,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bK7KEYHUXPCKGUBOTKUQXZ7MV4HY,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKBW7GOCYDD7SXMHRTYARXDZTVQ6,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKYFEGGAINWCL5HW66RMCX2K7VXX,SIP/2.0/TCP 10.46.0.3:49165;branch=z9hG4bK4c12767fc5935e36063883b
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=d3af300a
To: <tel:15550000005;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=102798606
Call-ID: 14d10c0fa0cb4772@10.46.0.3
CSeq: 1 INVITE
Record-Route: <sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5063;transport=tcp;lr;r2=on;did=XRAF5LQK2ICZBR3O;ue>,<sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5060;lr;r2=on;did=XRAF5LQK2ICZBR3O>,<sip:mt@10.80.0.5:5080;lr;did=NWZPA7PWVDCOMWGI>,<sip:mo@10.80.0.5:5080;lr;did=TWUH23YUJAVZHAUB>,<sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5060;lr;r2=on;did=NA2NUYJQ6NIKNRVJ>,<sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5063;transport=tcp;lr;r2=on;did=NA2NUYJQ6NIKNRVJ;ue>
Content-Length: 0
Session-ID: 225ec9f5ff30530a90edeb2fc05d8e50
Server: Core-Z5 N1982U.6.02.09.FR00
RSeq: 2
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=0010100000100066C000
Contact: <sip:b394eba0-c3ed-4e54-adf4-83d317ca2979@10.46.0.2:43300>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

