PRACK sip:8476f6db-5c6a-4256-a0dd-69db67bd85bd@10.46.0.10:44417 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKBD6V5523HOSJOPGHAOIV5S6SR2
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKBUPRTCNQMM5U5GIB5RMWCDM5VK
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKNKKBY7RXLCKJ4UALJ5WOINPP6K
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKBXGBWYSR7Q7W7UI5S5ARBDKES2
Via: SIP/2.0/UDP 10.46.0.5:6100;branch=z9hG4bK-524287-1---9a7f0968a1bef79a;rport=6100;transport=UDP;received=10.46.0.5
Max-Forwards: 66
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=5939484
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=579fff3c
Call-ID: idFuruxAN21AThXOdDJ0zQ..@10.46.0.5
CSeq: 2 PRACK
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
RAck: 1 1 INVITE
Content-Length: 0

