PRACK sip:8476f6db-5c6a-4256-a0dd-69db67bd85bd@10.46.0.10:44417 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKCP7CITKCPR5COVECTAJQMUXQ7E
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK7DCAOGUKATBY6AU247ENBSR733
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKOMZDZ2IS4I7RBTFMONN2TB7OUK
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKW4QGHPDCZCRNFA6DUUOW2DQTVK
Via: SIP/2.0/UDP 10.46.0.5:6100;branch=z9hG4bK-524287-1---f61e09a2e20cba34;rport=6100;transport=UDP;received=10.46.0.5
Max-Forwards: 66
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=5939484
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=579fff3c
Call-ID: idFuruxAN21AThXOdDJ0zQ..@10.46.0.5
CSeq: 4 PRACK
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
RAck: 2 1 INVITE
Content-Length: 0

