SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKCP7CITKCPR5COVECTAJQMUXQ7E,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK7DCAOGUKATBY6AU247ENBSR733,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKOMZDZ2IS4I7RBTFMONN2TB7OUK,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKW4QGHPDCZCRNFA6DUUOW2DQTVK,SIP/2.0/UDP 10.46.0.5:6100;branch=z9hG4bK-524287-1---f61e09a2e20cba34;rport=6100;transport=UDP;received=10.46.0.5
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=5939484
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=579fff3c
Call-ID: idFuruxAN21AThXOdDJ0zQ..@10.46.0.5
CSeq: 4 PRACK
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=9990100010019B01
Supported: 100rel,from-change,tdialog
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

