SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKAW4R73PBWIBM3KEVJS6FJWHBWL,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKGHIB27E2L2YSZ7WSJUP3MKFLTP,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bKXEKOEPFHX5ZAWREVKWQ365VEQS,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKVLPYPTXTA2SUYDM2TVQJHJ2UES,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKIVFVWQTFAQ27ZMT5PJHHSBFIQC,SIP/2.0/TCP 10.46.0.5:6100;branch=z9hG4bK-524287-1---4dcc4e82d7f2352b;rport=6101;transport=TCP;received=10.46.0.5
Record-Route: <sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5063;transport=tcp;lr;r2=on;did=BVHJA3NCOISW3VSJ;ue>,<sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5060;lr;r2=on;did=BVHJA3NCOISW3VSJ>,<sip:mt@10.80.0.5:5080;lr;did=AXKXF3F4BJY7PTUM>,<sip:mo@10.80.0.5:5080;lr;did=5TPKOWGUUW6Y4JQP>,<sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5060;lr;r2=on;did=RVC3TBNKMWVETGSR>,<sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5063;transport=tcp;lr;r2=on;did=RVC3TBNKMWVETGSR;ue>
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=5939484
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=579fff3c
Call-ID: idFuruxAN21AThXOdDJ0zQ..@10.46.0.5
CSeq: 1 INVITE
Session-Expires: 1800;refresher=uac
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=9990100010019B01
Require: timer,100rel
Contact: <sip:8476f6db-5c6a-4256-a0dd-69db67bd85bd@10.46.0.10:44417>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Supported: 100rel,from-change,tdialog
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

