BYE sip:8476f6db-5c6a-4256-a0dd-69db67bd85bd@10.46.0.10:44417 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKOXUXAKOJCNOZZW26MKW64DTF6G
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKDJVSOORTSCQTONCJ6QHFOQPTYU
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKJLZYKMRAWTPNUYGVJG5BMZLONE
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKKD7MOM5KAHEV6JC5T5QPQB3ZPJ
Via: SIP/2.0/UDP 10.46.0.5:6100;branch=z9hG4bK-524287-1---4067fab1618912ca;rport=6100;transport=UDP;received=10.46.0.5
Max-Forwards: 66
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=5939484
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=579fff3c
Call-ID: idFuruxAN21AThXOdDJ0zQ..@10.46.0.5
CSeq: 5 BYE
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
Content-Length: 0

