SIP/2.0 481 Call Does Not Exist
Via: SIP/2.0/UDP 10.46.0.19:54286;branch=z9hG4bKCKndfLCEn9AjJu7;received=10.46.0.19;rport=54286
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=21m1JIvy5M
To: <tel:+15550000003>;tag=QwFCggBVsy
Call-ID: OAMpjVpqF2TE8Fj4Q0LH4lpK
Session-ID: 6fa769bd9f136c112378cfbc781a3ef1
CSeq: 1 INVITE
Record-Route: <sip:x32syljhtyphttpzlk7ukklwna@10.80.0.5:5063;did=NEBAMOMDCKUPII6G;lr;r2=on;ue>, <sip:x32syljhtyphttpzlk7ukklwna@10.80.0.5:5060;did=NEBAMOMDCKUPII6G;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=COVVVZKF6YUG3BOJ;lr>, <sip:mo@10.80.0.5:5080;did=XW66SSURMDSEPTTR;lr>, <sip:x32syljhtyphttpzlk7ukklwna@10.80.0.5:5060;did=T2A4Z5RBAIJA7HWB;lr;r2=on>, <sip:x32syljhtyphttpzlk7ukklwna@10.80.0.5:5063;did=T2A4Z5RBAIJA7HWB;lr;r2=on;ue>
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

