ACK tel:+15550000003 SIP/2.0
Call-ID: OAMpjVpqF2TE8Fj4Q0LH4lpK
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=21m1JIvy5M
Route: <sip:10.80.0.5:5063;lr>, <sip:orig-32@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
CSeq: 1 ACK
Via: SIP/2.0/UDP 10.46.0.19:54286;branch=z9hG4bKCKndfLCEn9AjJu7;rport
To: <tel:+15550000003>;tag=QwFCggBVsy
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5064;port-s=5063;prot=esp;q=0.1;spi-c=227428419;spi-s=59663401
Require: sec-agree
Proxy-Require: sec-agree
Content-Length: 0

