PRACK sip:10.46.0.17:61189 SIP/2.0
From: <sip:15550000001@ims.mnc001.mcc001.3gppnetwork.org>;tag=1927058
To: <sip:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=zFJEGVPSyo
CSeq: 1927054 PRACK
Call-ID: 1927053_4111230880@10.46.0.14
Content-Length: 0
Via: SIP/2.0/TCP 10.46.0.14:40265;branch=z9hG4bK1630436099
Max-Forwards: 70
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015EE0000
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=165898036;spi-s=190332794;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
RAck: 1 1927053 INVITE
Route: <sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5063;did=YVJ2GKBMFEHHVT57;lr;r2=on;transport=tcp;ue>,<sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5060;did=YVJ2GKBMFEHHVT57;lr;r2=on>,<sip:mo@10.80.0.5:5080;did=6LG66HU6EAC2ZD2C;lr>,<sip:mt@10.80.0.5:5080;did=CAVDO2FD46F6RGJT;lr>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=URACXRURYM4GEOMA;lr;r2=on>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=URACXRURYM4GEOMA;lr;r2=on;transport=tcp;ue>
User-Agent: PRD-IR92/12 term-Motorola/XT2417-1-V1UFN35H.193-20 device-type/smart-phone
Proxy-Require: sec-agree
Require: sec-agree
Supported: timer

