SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKUPQ4B4EDFJCCFTWJVPUYFQ5V32,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKMXOYQUX47OHP77CY3A3ZYZ7557,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bK7YH62FZEHY6MTSD2XIVXTX2WBC,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKTD5WQIMSCEXN2R6ZHMPY56SOC7,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKPPKCRCMUAYURU7DLHYI6TUN673,SIP/2.0/TCP 10.46.0.14:40265;branch=z9hG4bK1444696567
From: <sip:15550000001@ims.mnc001.mcc001.3gppnetwork.org>;tag=1927058
To: <sip:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=zFJEGVPSyo
CSeq: 1927053 INVITE
Call-ID: 1927053_4111230880@10.46.0.14
Record-Route: <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=URACXRURYM4GEOMA;lr;r2=on;transport=tcp;ue>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=URACXRURYM4GEOMA;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=CAVDO2FD46F6RGJT;lr>, <sip:mo@10.80.0.5:5080;did=6LG66HU6EAC2ZD2C;lr>, <sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5060;did=YVJ2GKBMFEHHVT57;lr;r2=on>, <sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5063;did=YVJ2GKBMFEHHVT57;lr;r2=on;transport=tcp;ue>
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.srvcc-alerting;audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Content-Length: 0

