BYE sip:59ca0608-182c-4e87-aed8-aa1e2a898c87@10.46.0.14:40265 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKG6VHAXCISBV4EXHTXTI2QHGLEH
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKFPLUGCMZ3YCW5MJA4EUAO6AXP3
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKFGTM446D2B6UYQT6QNKIIQ6UL7
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKWGYZ7IFYCP4PF6IM4VZ2I42INP
Reason: SIP;cause=200;text="User Triggered"
To: <sip:15550000001@ims.mnc001.mcc001.3gppnetwork.org>;tag=1927058
From: <sip:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=zFJEGVPSyo
Call-ID: 1927053_4111230880@10.46.0.14
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 1 BYE
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKQe4rR26Bj2JfgbZ;rport=57130;received=10.46.0.17
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

