SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.46.0.10:44417;branch=z9hG4bK3550691292
Max-Forwards: 70
Record-Route: <sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5063;transport=tcp;lr;r2=on;did=MIMAOHYYMLGW3HWO;ue>
Record-Route: <sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5060;lr;r2=on;did=MIMAOHYYMLGW3HWO>
Record-Route: <sip:mt@10.80.0.5:5080;lr;did=PAJEAODRYRU4WCLV>
Record-Route: <sip:mo@10.80.0.5:5080;lr;did=WKFEAAXSOHIFOTX2>
Record-Route: <sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5060;lr;r2=on;did=6MZTY7B6SYMJA37E>
Record-Route: <sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5063;transport=tcp;lr;r2=on;did=6MZTY7B6SYMJA37E;ue>
Require: 100rel
Contact: <sip:15550000007@10.46.0.5:6100>;+sip.instance="<urn:gsma:imei:00000000-000007-0>";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting
To: <tel:15550000007;phone-context=ims.mnc001.mcc999.3gppnetwork.org>;tag=0542ad56
From: <sip:15550000008@ims.mnc001.mcc999.3gppnetwork.org>;tag=7022197
Call-ID: 7022189_3071011792@10.46.0.10
CSeq: 7022189 INVITE
Supported: timer, 100rel, precondition
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
RSeq: 2
Content-Length: 0
P-Asserted-Identity: <tel:+15550000007>
P-Asserted-Identity: <sip:+15550000007@ims.mnc001.mcc999.3gppnetwork.org;user=phone>

