PRACK sip:10.46.0.17:61189 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKYR7YKDVDAOFDSTOIFGDPAKSEQF
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKYD3F7TXKQU7W3DBVRY7GE6ZGMW
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKQT4ZOCJG3GFXO2AON5HMYVD4M6
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKTXLAMNVHXLM4DZKNKRHHAFJWJ6
RAck: 1 1 INVITE
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=pkLYHCuiXI
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=eNVkIOuHGB
Call-ID: Dsw8Vtijvn0c0hE6F0v58hyU
Session-ID: 79ef0028a761b50ffe7180b37b4aa165
Contact: <sip:10.46.0.19:54286>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 2 PRACK
Via: SIP/2.0/UDP 10.46.0.19:54286;branch=z9hG4bKeCdipVVCmcdjTIY;rport=54286;received=10.46.0.19
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

