SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKQGV2IVQZLDCIUVITHXOBNF3MSW,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKYEMLIZPTTPYEANY7A6F2QRXFIF,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bKH4LBKWAXUK6PDVGJDX7HSJL36N,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKIZ2J25XVECXZV7PM4IKHULVHDK,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKUBUEDHCV5K35F6JBBGGUH6MKA7,SIP/2.0/UDP 10.46.0.19:54286;branch=z9hG4bK3KR0jxaURNfv1Pw;received=10.46.0.19;rport=54286
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=eNVkIOuHGB
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=pkLYHCuiXI
Call-ID: Dsw8Vtijvn0c0hE6F0v58hyU
Session-ID: 79ef0028a761b50ffe7180b37b4aa165
CSeq: 1 INVITE
Record-Route: <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=N4RDXIYQXEFFAK2M;lr;r2=on;transport=tcp;ue>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=N4RDXIYQXEFFAK2M;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=JGIC5KBB7YZ42PXE;lr>, <sip:mo@10.80.0.5:5080;did=XJ6RHQS4NQEPHKU7;lr>, <sip:x32syljhtyphttpzlk7ukklwna@10.80.0.5:5060;did=QKEOJVTHMQZBMM6H;lr;r2=on>, <sip:x32syljhtyphttpzlk7ukklwna@10.80.0.5:5063;did=QKEOJVTHMQZBMM6H;lr;r2=on;ue>
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.srvcc-alerting;audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Content-Length: 0

