SIP/2.0 200 OK
Via: SIP/2.0/UDP 10.46.0.19:54286;branch=z9hG4bK3KR0jxaURNfv1Pw;received=10.46.0.19;rport=54286
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=eNVkIOuHGB
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=pkLYHCuiXI
Call-ID: Dsw8Vtijvn0c0hE6F0v58hyU
Session-ID: 79ef0028a761b50ffe7180b37b4aa165
CSeq: 1 INVITE
Record-Route: <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=N4RDXIYQXEFFAK2M;lr;r2=on;transport=tcp;ue>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=N4RDXIYQXEFFAK2M;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=JGIC5KBB7YZ42PXE;lr>, <sip:mo@10.80.0.5:5080;did=XJ6RHQS4NQEPHKU7;lr>, <sip:x32syljhtyphttpzlk7ukklwna@10.80.0.5:5060;did=QKEOJVTHMQZBMM6H;lr;r2=on>, <sip:x32syljhtyphttpzlk7ukklwna@10.80.0.5:5063;did=QKEOJVTHMQZBMM6H;lr;r2=on;ue>
Supported: 100rel,path,replaces,timer
Session-Expires: 1800;refresher=uas
Require: timer
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
User-Agent: iOS/27.0 iPhone
Content-Length: 0
P-Asserted-Identity: <tel:+15550000006>
P-Asserted-Identity: <sip:+15550000006@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

