ACK sip:10.46.0.17:61189 SIP/2.0
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=pkLYHCuiXI
Route: <sip:x32syljhtyphttpzlk7ukklwna@10.80.0.5:5063;did=QKEOJVTHMQZBMM6H;lr;r2=on;ue>, <sip:x32syljhtyphttpzlk7ukklwna@10.80.0.5:5060;did=QKEOJVTHMQZBMM6H;lr;r2=on>, <sip:mo@10.80.0.5:5080;did=XJ6RHQS4NQEPHKU7;lr>, <sip:mt@10.80.0.5:5080;did=JGIC5KBB7YZ42PXE;lr>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=N4RDXIYQXEFFAK2M;lr;r2=on>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=N4RDXIYQXEFFAK2M;lr;r2=on;transport=tcp;ue>
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=eNVkIOuHGB
Call-ID: Dsw8Vtijvn0c0hE6F0v58hyU
Session-ID: 79ef0028a761b50ffe7180b37b4aa165
Contact: <sip:10.46.0.19:54286>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 1 ACK
Via: SIP/2.0/UDP 10.46.0.19:54286;branch=z9hG4bKghYKLkxdS5TUADP;rport
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5064;port-s=5063;prot=esp;q=0.1;spi-c=227428419;spi-s=59663401
Require: sec-agree
Proxy-Require: sec-agree
Content-Length: 0

