SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKBLFL3CA44UMCMFQSKF4PNSWGIP,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKLQGG56OPRDGRFMRO5HKHS3S42D,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKGA4WVCDIE7U3QP2T5UHJWUGQ55,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKH4VEYHJYIOSVALBVT2GIQUERHI,SIP/2.0/UDP 10.46.0.19:54286;branch=z9hG4bK50rU8dACxtx3wYk;received=10.46.0.19;rport=54286
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=pkLYHCuiXI
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=eNVkIOuHGB
Call-ID: Dsw8Vtijvn0c0hE6F0v58hyU
Session-ID: 79ef0028a761b50ffe7180b37b4aa165
CSeq: 4 BYE
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Content-Length: 0

