SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.0.0.1:5063;branch=z9hG4bK7AJ4U5W4YGYDPO5FJ2CD254DV6
Via: SIP/2.0/UDP 10.0.0.1:5080;branch=z9hG4bKOUTABYRQUSVEDJYMO5YJF3ORD6
Via: SIP/2.0/UDP 10.0.0.1:5070;branch=z9hG4bKAPUEEGBHGLWW4I6TA2UOA7ENNQ
Via: SIP/2.0/UDP 10.0.0.1:5080;branch=z9hG4bKRE5L7XEMLJNGZOA43U4YEYCDNB
Via: SIP/2.0/UDP 10.0.0.1:5060;branch=z9hG4bKR4KZXOHWONBWEW364YVAF4ZF5J
Via: SIP/2.0/TCP 10.0.0.2:38889;branch=z9hG4bKN2W5RLM7OASABZ6SP32GPA23SA;rport=44803;received=10.0.0.2
Record-Route: <sip:zfh2lgtqhm5cnong5mbtqesooq@10.0.0.1:5063;transport=tcp;lr;r2=on;did=OEMTOR2JHJYATYM3;ue>
Record-Route: <sip:zfh2lgtqhm5cnong5mbtqesooq@10.0.0.1:5060;lr;r2=on;did=OEMTOR2JHJYATYM3>
Record-Route: <sip:mt@10.0.0.1:5080;lr;did=HIBKNCKAGBRTF3WP>
Record-Route: <sip:mo@10.0.0.1:5080;lr;did=UDWTBO5ZV72KW7J2>
Record-Route: <sip:fch555hos5mgc3rtk3lovlciov@10.0.0.1:5060;lr;r2=on;did=3WVWD42GP5R4HKAL>
Record-Route: <sip:fch555hos5mgc3rtk3lovlciov@10.0.0.1:5063;transport=tcp;lr;r2=on;did=3WVWD42GP5R4HKAL;ue>
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=PW7SQXHCQTXO6C5IMA73U6MNJA
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=DLT2KVKAMKLPY4ILHK37GIPRQX
Call-ID: 657c1234-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.2
CSeq: 1 INVITE
Content-Length: 0
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010000001
Contact: <sip:656c296f-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.3:46761>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, PRACK, NOTIFY, MESSAGE
Supported: 100rel, timer
Session-Expires: 1800;refresher=uac
Require: timer

