ACK sip:4542e7f2-bf70-11f1-81ff-2bcf73babbc9@10.0.0.3:35047 SIP/2.0
Via: SIP/2.0/UDP 10.0.0.2:38873;branch=z9hG4bK5HKX3QW7FIRNIKWCZS67UW6O62;rport
Route: <sip:7qi7n3eiqts4aak3xd3aop3cjh@10.0.0.1:5063;transport=tcp;lr;r2=on;did=YRUSJYMQF73FRANU;ue>, <sip:7qi7n3eiqts4aak3xd3aop3cjh@10.0.0.1:5060;lr;r2=on;did=YRUSJYMQF73FRANU>, <sip:mo@10.0.0.1:5080;lr;did=4NIXFEQLROT7M6HP>, <sip:mt@10.0.0.1:5080;lr;did=PZJ7LAPP47A5KB7T>, <sip:dmigbowgjhlyfhiyff53dy5zs3@10.0.0.1:5060;lr;r2=on;did=AREWF3EVUTIQZAPC>, <sip:dmigbowgjhlyfhiyff53dy5zs3@10.0.0.1:5063;transport=tcp;lr;r2=on;did=AREWF3EVUTIQZAPC;ue>
Max-Forwards: 70
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=B4GII4SE6BTWFZPJVJCHLBPG24
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=CSL6GIEWFVT6NIDLWWEAISEMIL
Call-ID: 4552e3a2-bf70-11f1-81ff-2bcf73babbc9@10.0.0.2
CSeq: 1 ACK
Content-Length: 0
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=62156179;spi-s=149231997;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Require: sec-agree
Proxy-Require: sec-agree

