SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.0.0.1:5063;branch=z9hG4bKY6QJSLEKEANBVGUGCEBUSWC6OL
Via: SIP/2.0/UDP 10.0.0.1:5080;branch=z9hG4bKPF72IYIRQG4FF4OOCTMWG73BZU
Via: SIP/2.0/UDP 10.0.0.1:5080;branch=z9hG4bKNIYMHILM5OY3V5QXVVRAKN77A5
Via: SIP/2.0/UDP 10.0.0.1:5060;branch=z9hG4bKODK6EX5GUPBPR5RGNRNXV4INKS
Via: SIP/2.0/TCP 10.0.0.2:38873;branch=z9hG4bKMAIFG2YU4MZFJCHAFFBAV3ITUR;rport=45067;received=10.0.0.2
Record-Route: <sip:mt@10.0.0.1:5080;lr;did=PZJ7LAPP47A5KB7T>
Record-Route: <sip:mo@10.0.0.1:5080;lr;did=4NIXFEQLROT7M6HP>
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=B4GII4SE6BTWFZPJVJCHLBPG24
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=CSL6GIEWFVT6NIDLWWEAISEMIL
Call-ID: 4552e3a2-bf70-11f1-81ff-2bcf73babbc9@10.0.0.2
CSeq: 3 UPDATE
Content-Length: 0
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010000001
Contact: <sip:4542e7f2-bf70-11f1-81ff-2bcf73babbc9@10.0.0.3:35047>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, PRACK, NOTIFY, MESSAGE
Session-Expires: 1800;refresher=uac
Require: timer

