SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.0.0.2:38889;branch=z9hG4bKUSHU2KQTMVKIGL5KHWNMZBUR7C;rport=44803;received=10.0.0.2
Record-Route: <sip:zfh2lgtqhm5cnong5mbtqesooq@10.0.0.1:5063;transport=tcp;lr;r2=on;did=OEMTOR2JHJYATYM3;ue>
Record-Route: <sip:zfh2lgtqhm5cnong5mbtqesooq@10.0.0.1:5060;lr;r2=on;did=OEMTOR2JHJYATYM3>
Record-Route: <sip:mt@10.0.0.1:5080;lr;did=HIBKNCKAGBRTF3WP>
Record-Route: <sip:mo@10.0.0.1:5080;lr;did=UDWTBO5ZV72KW7J2>
Record-Route: <sip:fch555hos5mgc3rtk3lovlciov@10.0.0.1:5060;lr;r2=on;did=3WVWD42GP5R4HKAL>
Record-Route: <sip:fch555hos5mgc3rtk3lovlciov@10.0.0.1:5063;transport=tcp;lr;r2=on;did=3WVWD42GP5R4HKAL;ue>
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=PW7SQXHCQTXO6C5IMA73U6MNJA
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=DLT2KVKAMKLPY4ILHK37GIPRQX
Call-ID: 657c1234-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.2
CSeq: 3 UPDATE
Content-Length: 0
Contact: <sip:656c296f-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.3:46761>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, PRACK, NOTIFY, MESSAGE
Session-Expires: 1800;refresher=uac
Require: timer

