SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.15:43435;branch=z9hG4bK227042174
From: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>;tag=956055
To: <tel:15550000001;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=956312
CSeq: 956051 PRACK
Call-ID: 956048_3070404240@10.46.0.15
Content-Length: 0
Server: PRD-IR92/12 term-Motorola/XT2417-1-V1UFN35H.193-20 device-type/smart-phone
Supported: 100rel,from-change,tdialog
Privacy: id
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

