SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKMNA6NUKWNWOJLB4XBD6FA7LEIL,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK57H2I624GAKFA275PJ5PTDWUOV,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bK5ZS7U3FSY3GLM5FCYI4DSO4LDC,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKIHRXOW5P3ZYVD6B4HLWPOAUDZL,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKRHF4KM3UQFMWYKDK5QNPMX2ABL,SIP/2.0/TCP 10.46.0.15:43435;branch=z9hG4bK2770294180
From: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>;tag=956055
To: <tel:15550000001;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=956312
CSeq: 956048 INVITE
Call-ID: 956048_3070404240@10.46.0.15
Record-Route: <sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5063;transport=tcp;lr;r2=on;did=2K6RPNQ77TYFOPHJ;ue>,<sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5060;lr;r2=on;did=2K6RPNQ77TYFOPHJ>,<sip:mt@10.80.0.5:5080;lr;did=HTNEZOIG3W7NPTNH>,<sip:mo@10.80.0.5:5080;lr;did=GWICAY2QGKOEVK47>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;lr;r2=on;did=TLHZAYZAOS2BJJTQ>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;transport=tcp;lr;r2=on;did=TLHZAYZAOS2BJJTQ;ue>
Content-Length: 0
Session-Expires: 1800;refresher=uac
Server: PRD-IR92/12 term-Motorola/XT2417-1-V1UFN35H.193-20 device-type/smart-phone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015EE0000
Require: timer,100rel
Contact: <sip:59ca0608-182c-4e87-aed8-aa1e2a898c87@10.46.0.14:40265>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Supported: 100rel,from-change,tdialog
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

