BYE sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435 SIP/2.0
To: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>;tag=956055
From: <tel:15550000001;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=956312
Call-ID: 956048_3070404240@10.46.0.15
CSeq: 956049 BYE
Via: SIP/2.0/TCP 10.46.0.14:40265;branch=z9hG4bK1555598670
Max-Forwards: 70
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015EE0000
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=165898036;spi-s=190332794;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Route: <sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5063;transport=tcp;lr;r2=on;did=2K6RPNQ77TYFOPHJ;ue>,<sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5060;lr;r2=on;did=2K6RPNQ77TYFOPHJ>,<sip:mt@10.80.0.5:5080;lr;did=HTNEZOIG3W7NPTNH>,<sip:mo@10.80.0.5:5080;lr;did=GWICAY2QGKOEVK47>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;lr;r2=on;did=TLHZAYZAOS2BJJTQ>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;transport=tcp;lr;r2=on;did=TLHZAYZAOS2BJJTQ;ue>
P-Preferred-Identity: <sip:15550000001@ims.mnc001.mcc001.3gppnetwork.org>
Require: sec-agree
Proxy-Require: sec-agree
Reason: RELEASE_CAUSE ;cause=1 ;text="User ends call"
User-Agent: PRD-IR92/12 term-Motorola/XT2417-1-V1UFN35H.193-20 device-type/smart-phone
Content-Length: 0

