PRACK sip:8476f6db-5c6a-4256-a0dd-69db67bd85bd@10.46.0.10:44417 SIP/2.0
Via: SIP/2.0/UDP 10.46.0.5:6100;branch=z9hG4bK-524287-1---b4663a048a369f57;rport;transport=UDP
Max-Forwards: 70
Route: <sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5063;transport=tcp;lr;r2=on;did=LRN2CU4SKJFAP5AG;ue>
Route: <sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5060;lr;r2=on;did=LRN2CU4SKJFAP5AG>
Route: <sip:mo@10.80.0.5:5080;lr;did=XW2GSNKCROYJZMJF>
Route: <sip:mt@10.80.0.5:5080;lr;did=KEXY5BRVIXVY4EYD>
Route: <sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5060;lr;r2=on;did=NGLDXIEZ5OALAYA7>
Route: <sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5063;transport=tcp;lr;r2=on;did=NGLDXIEZ5OALAYA7;ue>
Proxy-Require: sec-agree
Require: sec-agree
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=6286761
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=1c84d201
Call-ID: bml0BhpQjnxykIBoUSLWdg..@10.46.0.5
CSeq: 2 PRACK
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=132102118;spi-s=104856785;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
RAck: 1 1 INVITE
P-Preferred-Identity: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=9990100010019b01
Content-Length: 0

