PRACK sip:8476f6db-5c6a-4256-a0dd-69db67bd85bd@10.46.0.10:44417 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKTS7KCIHAWGGB675POYXKTT75DC
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK7TXEMFYY3WK7Y36DDIEMW3ICIJ
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKZGNY66FIV2CEZCWFFTCENRK2UK
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKPGM2YIRXICYILS3TPUAMILIVCP
Via: SIP/2.0/UDP 10.46.0.5:6100;branch=z9hG4bK-524287-1---b4663a048a369f57;rport=6100;transport=UDP;received=10.46.0.5
Max-Forwards: 66
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=6286761
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=1c84d201
Call-ID: bml0BhpQjnxykIBoUSLWdg..@10.46.0.5
CSeq: 2 PRACK
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
RAck: 1 1 INVITE
Content-Length: 0

