SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKRRCLLQBQYQY74C73VVUYOR7UZS,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKIL2A3E2MBDAIP56SEJKOWLYBJ4,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKFJTAOJUWFVZMRKDVR6YKPJX3EK,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKHNWDOIHG4Z6ZKII3J2JB5YIQ2F,SIP/2.0/UDP 10.46.0.5:6100;branch=z9hG4bK-524287-1---b497598d45cf5b6a;rport=6100;transport=UDP;received=10.46.0.5
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=6286761
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=1c84d201
Call-ID: bml0BhpQjnxykIBoUSLWdg..@10.46.0.5
CSeq: 4 PRACK
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=9990100010019B01
Supported: 100rel,from-change,tdialog
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

