SIP/2.0 486 Busy Here
Via: SIP/2.0/TCP 10.46.0.5:6100;branch=z9hG4bK-524287-1---42779705c362ff5f;rport=6101;transport=TCP;received=10.46.0.5
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=6286761
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=1c84d201
Call-ID: bml0BhpQjnxykIBoUSLWdg..@10.46.0.5
CSeq: 1 INVITE
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

