SIP/2.0 487 Request Terminated
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKBNUM7UHYBYFID37OOR4YWB3JLV
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKWS5YHAGP65CMU3LO2OLE5E7H5A
Via: SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bKBL3JVSUQCQPDGMXCI6TJ62CESG
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKTFDNNO3PBWICCJUKFHFVC7ESAC
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKIOVCT33LVAJKYZHBNRIW2YRWTQ
Via: SIP/2.0/TCP 10.46.0.8:41989;branch=z9hG4bK1853593200
Max-Forwards: 70
Record-Route: <sip:3iqp554vb5dijnjmjo2u3xbt2t@10.80.0.5:5063;transport=tcp;lr;r2=on;did=M5SM2HEFRGAHI36A;ue>
Record-Route: <sip:3iqp554vb5dijnjmjo2u3xbt2t@10.80.0.5:5060;lr;r2=on;did=M5SM2HEFRGAHI36A>
Record-Route: <sip:mt@10.80.0.5:5080;lr;did=Z4QDMBAGCXEEIS3F>
Record-Route: <sip:mo@10.80.0.5:5080;lr;did=WXYOJWTZ4LBBKHVN>
Record-Route: <sip:75xi5p5r4lmyujqtijnkhr24d7@10.80.0.5:5060;lr;r2=on;did=752RRKDPKX56IKFN>
Record-Route: <sip:75xi5p5r4lmyujqtijnkhr24d7@10.80.0.5:5063;transport=tcp;lr;r2=on;did=752RRKDPKX56IKFN;ue>
Contact: <sip:15550000007@10.46.0.7:6600>;+sip.instance="<urn:gsma:imei:00000000-000007-0>";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting
To: <tel:15550000007;phone-context=ims.mnc001.mcc999.3gppnetwork.org>;tag=182a5d7a
From: <sip:15550000008@ims.mnc001.mcc999.3gppnetwork.org>;tag=100791154
Call-ID: 100791148_3068993808@10.46.0.8
CSeq: 100791147 INVITE
Supported: timer, 100rel, precondition
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=9990100000100066c000
Content-Length: 0

