PRACK sip:10.46.0.25:63507 SIP/2.0
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=9ca6b699
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=djrrgmkpB4
Call-ID: c062b07143ceba33@10.46.0.24
CSeq: 2 PRACK
Max-Forwards: 70
Via: SIP/2.0/TCP 10.46.0.24:49165;branch=z9hG4bK76cf2f5fab3e9456d32a0dc
Content-Length: 0
Proxy-Require: sec-agree
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010019b01
User-Agent: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Require: sec-agree
Supported: sec-agree
RAck: 1 1 INVITE
Session-ID: 606cf15c6fb25a17b1d92ce76c4adcf1
Route: <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;transport=tcp;lr;did=BMO2IKZUFUAKKQY4;r2=on;ue>,<sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;lr;did=BMO2IKZUFUAKKQY4;r2=on>,<sip:mo@10.80.0.5:5080;lr;did=6XHOAZQNUYWJGTEE>,<sip:mt@10.80.0.5:5080;lr;did=PS3JMWKO5I6NRDX2>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;lr;did=FUZBTDHV4H6ZREWF;r2=on>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;transport=tcp;lr;did=FUZBTDHV4H6ZREWF;r2=on;ue>
Security-Verify: ipsec-3gpp;q=0.1;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=null;spi-c=259322710;spi-s=69633574;port-c=5064;port-s=5063

