SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.24:49165;branch=z9hG4bK76cf2f5fab3e9456d32a0dc
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=9ca6b699
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=djrrgmkpB4
Call-ID: c062b07143ceba33@10.46.0.24
CSeq: 2 PRACK
Session-ID: 606cf15c6fb25a17b1d92ce76c4adcf1
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

