SIP/2.0 486 Call Rejected By User
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bK64W7NJ44VHDXZQMS4IJ72WFVSF,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKBCWQZR22RAGQSOX6QSASTBPGBR,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bKPU4XBUHBTZ7W52L4EIGDIGF57G,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKQO2SBQOFTUUSBKTGVNS77DHVJH,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKHMHSYZWZTBHNLUU5N7PAZUJCZ7,SIP/2.0/TCP 10.46.0.24:49165;branch=z9hG4bK1a09435311ed18bbc94f80d
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=9ca6b699
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=djrrgmkpB4
Call-ID: c062b07143ceba33@10.46.0.24
CSeq: 1 INVITE
Record-Route: <sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;did=FUZBTDHV4H6ZREWF;lr;r2=on;transport=tcp;ue>, <sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;did=FUZBTDHV4H6ZREWF;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=PS3JMWKO5I6NRDX2;lr>, <sip:mo@10.80.0.5:5080;did=6XHOAZQNUYWJGTEE;lr>, <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;did=BMO2IKZUFUAKKQY4;lr;r2=on>, <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;did=BMO2IKZUFUAKKQY4;lr;r2=on;transport=tcp;ue>
Session-ID: 606cf15c6fb25a17b1d92ce76c4adcf1
Contact: <sip:10.46.0.25:63507>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Content-Length: 0

