ACK tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=9ca6b699
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=djrrgmkpB4
Call-ID: c062b07143ceba33@10.46.0.24
CSeq: 1 ACK
Max-Forwards: 70
Via: SIP/2.0/TCP 10.46.0.24:49165;branch=z9hG4bK1a09435311ed18bbc94f80d
Content-Length: 0
Session-ID: 606cf15c6fb25a17b1d92ce76c4adcf1
Route: <sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;transport=tcp;lr;did=FUZBTDHV4H6ZREWF;r2=on;ue>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;lr;did=FUZBTDHV4H6ZREWF;r2=on>,<sip:mt@10.80.0.5:5080;lr;did=PS3JMWKO5I6NRDX2>,<sip:mo@10.80.0.5:5080;lr;did=6XHOAZQNUYWJGTEE>,<sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;lr;did=BMO2IKZUFUAKKQY4;r2=on>,<sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;transport=tcp;lr;did=BMO2IKZUFUAKKQY4;r2=on;ue>

