PRACK sip:4542e7f2-bf70-11f1-81ff-2bcf73babbc9@10.0.0.3:35047 SIP/2.0
Via: SIP/2.0/UDP 10.0.0.2:38873;branch=z9hG4bKKMPA55RUJ73P4DIJ44DS4TVJTO;rport
Route: <sip:7qi7n3eiqts4aak3xd3aop3cjh@10.0.0.1:5063;transport=tcp;lr;r2=on;did=DWFKBYMFP6K6MZCN;ue>, <sip:7qi7n3eiqts4aak3xd3aop3cjh@10.0.0.1:5060;lr;r2=on;did=DWFKBYMFP6K6MZCN>, <sip:mo@10.0.0.1:5080;lr;did=Y4MG2YEKOYNRRCID>, <sip:mt@10.0.0.1:5080;lr;did=OMDLE7NNWM5OPZ5U>, <sip:dmigbowgjhlyfhiyff53dy5zs3@10.0.0.1:5060;lr;r2=on;did=PNR5WJJ47OKU2ZFE>, <sip:dmigbowgjhlyfhiyff53dy5zs3@10.0.0.1:5063;transport=tcp;lr;r2=on;did=PNR5WJJ47OKU2ZFE;ue>
Max-Forwards: 70
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=NF6P3SIPZFTE7O6C7FX4UYAMCO
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=SUMK2J5KZ2HXSXFRXVKS5FQGKS
Call-ID: 459358e3-bf70-11f1-81ff-2bcf73babbc9@10.0.0.2
CSeq: 2 PRACK
RAck: 911074050 1 INVITE
Content-Length: 0
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=62156179;spi-s=149231997;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Require: sec-agree
Proxy-Require: sec-agree
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010000001

