SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.0.0.1:5063;branch=z9hG4bKS2LYSI3DS7RTNFV5QJZRJTLTKX
Via: SIP/2.0/UDP 10.0.0.1:5080;branch=z9hG4bKCISNYODQQEAWI33BWL4JFNKXGZ
Via: SIP/2.0/UDP 10.0.0.1:5070;branch=z9hG4bKBV6WQRTBDCHSWXFN2IW6LLBK4G
Via: SIP/2.0/UDP 10.0.0.1:5080;branch=z9hG4bKLSK6Q773QJRQH6ZQ2Y3CHM4WLQ
Via: SIP/2.0/UDP 10.0.0.1:5060;branch=z9hG4bKT5Y7767XIXU3RV4O763VFATI4T
Via: SIP/2.0/TCP 10.0.0.2:38873;branch=z9hG4bKVMFASSMSSZ72WVZSMCN72VYZUK;rport=45067;received=10.0.0.2
Record-Route: <sip:dmigbowgjhlyfhiyff53dy5zs3@10.0.0.1:5063;transport=tcp;lr;r2=on;did=PNR5WJJ47OKU2ZFE;ue>
Record-Route: <sip:dmigbowgjhlyfhiyff53dy5zs3@10.0.0.1:5060;lr;r2=on;did=PNR5WJJ47OKU2ZFE>
Record-Route: <sip:mt@10.0.0.1:5080;lr;did=OMDLE7NNWM5OPZ5U>
Record-Route: <sip:mo@10.0.0.1:5080;lr;did=Y4MG2YEKOYNRRCID>
Record-Route: <sip:7qi7n3eiqts4aak3xd3aop3cjh@10.0.0.1:5060;lr;r2=on;did=DWFKBYMFP6K6MZCN>
Record-Route: <sip:7qi7n3eiqts4aak3xd3aop3cjh@10.0.0.1:5063;transport=tcp;lr;r2=on;did=DWFKBYMFP6K6MZCN;ue>
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=NF6P3SIPZFTE7O6C7FX4UYAMCO
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=SUMK2J5KZ2HXSXFRXVKS5FQGKS
Call-ID: 459358e3-bf70-11f1-81ff-2bcf73babbc9@10.0.0.2
CSeq: 1 INVITE
Content-Length: 0
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010000001
Contact: <sip:4542e7f2-bf70-11f1-81ff-2bcf73babbc9@10.0.0.3:35047>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, PRACK, NOTIFY, MESSAGE
Supported: 100rel, timer, precondition

