SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.0.0.1:5063;branch=z9hG4bKA22ZTX2QX635J5CVR5PJ2JZGJD
Via: SIP/2.0/UDP 10.0.0.1:5080;branch=z9hG4bKEB7RU4UCOQ2KJ4GXDJHFWJWRL6
Via: SIP/2.0/UDP 10.0.0.1:5070;branch=z9hG4bKE7TBWWIGBOITDMJ6UVDTJNOSBW
Via: SIP/2.0/UDP 10.0.0.1:5080;branch=z9hG4bKOIKT2CASFDJRN6SQXPYEOH5SAF
Via: SIP/2.0/UDP 10.0.0.1:5060;branch=z9hG4bKOBZTGQL575LK2YOUIGDPBQBT4P
Via: SIP/2.0/TCP 10.0.0.2:38889;branch=z9hG4bKINLMW37RJDXKJ5BA4QJZKLOTYW;rport=44803;received=10.0.0.2
Record-Route: <sip:zfh2lgtqhm5cnong5mbtqesooq@10.0.0.1:5063;transport=tcp;lr;r2=on;did=Z4VMEM24F5VMZ4VK;ue>
Record-Route: <sip:zfh2lgtqhm5cnong5mbtqesooq@10.0.0.1:5060;lr;r2=on;did=Z4VMEM24F5VMZ4VK>
Record-Route: <sip:mt@10.0.0.1:5080;lr;did=FTRICVE44SP7L6NB>
Record-Route: <sip:mo@10.0.0.1:5080;lr;did=SFJONNCYBBFMED36>
Record-Route: <sip:fch555hos5mgc3rtk3lovlciov@10.0.0.1:5060;lr;r2=on;did=APZ5OSQXGKMJ3GN7>
Record-Route: <sip:fch555hos5mgc3rtk3lovlciov@10.0.0.1:5063;transport=tcp;lr;r2=on;did=APZ5OSQXGKMJ3GN7;ue>
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=RC6EN5FGANJVFC6BSN4Q4QOSOW
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=Z754NVCUTCJLSDFBU7CSUROVY2
Call-ID: 65e12d93-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.2
CSeq: 1 INVITE
Content-Length: 0
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010000001
Contact: <sip:656c296f-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.3:46761>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, PRACK, NOTIFY, MESSAGE
Supported: 100rel, timer, precondition
Session-Expires: 1800;refresher=uac
Require: timer

