SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.0.0.2:38889;branch=z9hG4bKINLMW37RJDXKJ5BA4QJZKLOTYW;rport=44803;received=10.0.0.2
Record-Route: <sip:zfh2lgtqhm5cnong5mbtqesooq@10.0.0.1:5063;transport=tcp;lr;r2=on;did=Z4VMEM24F5VMZ4VK;ue>
Record-Route: <sip:zfh2lgtqhm5cnong5mbtqesooq@10.0.0.1:5060;lr;r2=on;did=Z4VMEM24F5VMZ4VK>
Record-Route: <sip:mt@10.0.0.1:5080;lr;did=FTRICVE44SP7L6NB>
Record-Route: <sip:mo@10.0.0.1:5080;lr;did=SFJONNCYBBFMED36>
Record-Route: <sip:fch555hos5mgc3rtk3lovlciov@10.0.0.1:5060;lr;r2=on;did=APZ5OSQXGKMJ3GN7>
Record-Route: <sip:fch555hos5mgc3rtk3lovlciov@10.0.0.1:5063;transport=tcp;lr;r2=on;did=APZ5OSQXGKMJ3GN7;ue>
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=RC6EN5FGANJVFC6BSN4Q4QOSOW
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=Z754NVCUTCJLSDFBU7CSUROVY2
Call-ID: 65e12d93-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.2
CSeq: 1 INVITE
Content-Length: 0
Contact: <sip:656c296f-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.3:46761>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, PRACK, NOTIFY, MESSAGE
Supported: 100rel, timer, precondition
P-Asserted-Identity: <tel:+15550002>
P-Asserted-Identity: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

