BYE sip:656c296f-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.3:46761 SIP/2.0
Via: SIP/2.0/TCP 10.0.0.2:38889;branch=z9hG4bKH2U5S3VYHCJNUGTLEYBIBXOF4E;rport
Route: <sip:fch555hos5mgc3rtk3lovlciov@10.0.0.1:5063;transport=tcp;lr;r2=on;did=APZ5OSQXGKMJ3GN7;ue>, <sip:fch555hos5mgc3rtk3lovlciov@10.0.0.1:5060;lr;r2=on;did=APZ5OSQXGKMJ3GN7>, <sip:mo@10.0.0.1:5080;lr;did=SFJONNCYBBFMED36>, <sip:mt@10.0.0.1:5080;lr;did=FTRICVE44SP7L6NB>, <sip:zfh2lgtqhm5cnong5mbtqesooq@10.0.0.1:5060;lr;r2=on;did=Z4VMEM24F5VMZ4VK>, <sip:zfh2lgtqhm5cnong5mbtqesooq@10.0.0.1:5063;transport=tcp;lr;r2=on;did=Z4VMEM24F5VMZ4VK;ue>
Max-Forwards: 70
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=RC6EN5FGANJVFC6BSN4Q4QOSOW
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=Z754NVCUTCJLSDFBU7CSUROVY2
Call-ID: 65e12d93-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.2
CSeq: 4 BYE
Content-Length: 0
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=239075227;spi-s=42329523;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Require: sec-agree
Proxy-Require: sec-agree
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010000001

