SIP/2.0 401 Unauthorized
From: <sip:001010000000005@ims.mnc001.mcc001.3gppnetwork.org>;tag=2196671
To: <sip:001010000000005@ims.mnc001.mcc001.3gppnetwork.org>;tag=S6RKVOMBNMXW77M27ZLMXGUOWQ
CSeq: 2196665 REGISTER
Call-ID: 2196665_1761188768@10.46.0.8
Via: SIP/2.0/TCP 10.46.0.8:5060;branch=z9hG4bK3818442955
Content-Length: 0
WWW-Authenticate: Digest realm="ims.mnc001.mcc001.3gppnetwork.org", nonce="pKT+F0HTOATM7np0NOM39zwxv8gWpoAAhxNjYm7hDFU=", algorithm=AKAv1-MD5, qop="auth"
Security-Server: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=96869828;spi-s=59842814;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Supported: sec-agree

