SIP/2.0 200 OK
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=lS8LckkC5a
To: <tel:+15550000002>;tag=ff17475
Contact: <sip:15550000002@10.46.0.24:49165>;+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video
Call-ID: lfL6PNmhoTLxV8066vuy5N6Z
CSeq: 1 INVITE
Via: SIP/2.0/TCP 10.46.0.25:63507;received=10.46.0.25;branch=z9hG4bKoXsa8rJWBtOuTm8;rport=64105
Content-Length: 0
Supported: timer
Allow: INVITE,CANCEL,UPDATE,PRACK,BYE,ACK,MESSAGE,SUBSCRIBE,NOTIFY,PUBLISH,REFER,INFO,OPTIONS
Session-Expires: 1800;refresher=uac
Server: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Require: timer
Record-Route: <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;transport=tcp;lr;did=7CIA77CNYADYJMIR;ob;r2=on;ue>,<sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;lr;did=7CIA77CNYADYJMIR;ob;r2=on>,<sip:mt@10.80.0.5:5080;lr;did=OFE4UUYDMOQSPUN4>,<sip:mo@10.80.0.5:5080;lr;did=HEVSEEELGHF4VVIO>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;lr;did=PT6TEW2SCZHAUG5T;r2=on>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;transport=tcp;lr;did=PT6TEW2SCZHAUG5T;r2=on;ue>
Session-ID: 3409143487ce4c36db1c6754249bde48
P-Asserted-Identity: <tel:+15550000002>
P-Asserted-Identity: <sip:+15550000002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

