ACK sip:15550000002@10.46.0.24:49165 SIP/2.0
To: <tel:+15550000002>;tag=ff17475
Route: <sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;did=PT6TEW2SCZHAUG5T;lr;r2=on;transport=tcp;ue>, <sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;did=PT6TEW2SCZHAUG5T;lr;r2=on>, <sip:mo@10.80.0.5:5080;did=HEVSEEELGHF4VVIO;lr>, <sip:mt@10.80.0.5:5080;did=OFE4UUYDMOQSPUN4;lr>, <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;did=7CIA77CNYADYJMIR;lr;ob;r2=on>, <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;did=7CIA77CNYADYJMIR;lr;ob;r2=on;transport=tcp;ue>
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=lS8LckkC5a
Call-ID: lfL6PNmhoTLxV8066vuy5N6Z
Session-ID: 3409143487ce4c36db1c6754249bde48
Contact: <sip:10.46.0.25:63507>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 1 ACK
Via: SIP/2.0/TCP 10.46.0.25:63507;branch=z9hG4bKxa9D96zmiZRKfab;rport
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5064;port-s=5063;prot=esp;q=0.1;spi-c=8430301;spi-s=114600604
Require: sec-agree
Proxy-Require: sec-agree
Content-Length: 0

