BYE sip:10.46.0.25:63507 SIP/2.0
From: <tel:+15550000002>;tag=ff17475
To: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=lS8LckkC5a
Contact: <sip:15550000002@10.46.0.24:49165>;+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video
Call-ID: lfL6PNmhoTLxV8066vuy5N6Z
CSeq: 1 BYE
Max-Forwards: 70
Via: SIP/2.0/TCP 10.46.0.24:49165;branch=z9hG4bKf4d6f44ba0cc145a90939cb6
Content-Length: 0
Reason: RELEASE_CAUSE;cause=1;text="User ends call"
Require: sec-agree
P-Preferred-Identity: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>
Proxy-Require: sec-agree
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010019b01
User-Agent: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Route: <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;transport=tcp;lr;did=7CIA77CNYADYJMIR;ob;r2=on;ue>,<sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;lr;did=7CIA77CNYADYJMIR;ob;r2=on>,<sip:mt@10.80.0.5:5080;lr;did=OFE4UUYDMOQSPUN4>,<sip:mo@10.80.0.5:5080;lr;did=HEVSEEELGHF4VVIO>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;lr;did=PT6TEW2SCZHAUG5T;r2=on>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;transport=tcp;lr;did=PT6TEW2SCZHAUG5T;r2=on;ue>
Security-Verify: ipsec-3gpp;q=0.1;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=null;spi-c=259322710;spi-s=69633574;port-c=5064;port-s=5063
Session-ID: 3409143487ce4c36db1c6754249bde48

