SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.3:49165;branch=z9hG4bKc85c037a1ad739c814fedd4b
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=8b4182f4
To: <tel:15550000005;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=102907630
Call-ID: f234da03b74dd2e5@10.46.0.3
CSeq: 1 INVITE
Record-Route: <sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5063;transport=tcp;lr;r2=on;did=VF2DKULG7AK3QLVK;ue>,<sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5060;lr;r2=on;did=VF2DKULG7AK3QLVK>,<sip:mt@10.80.0.5:5080;lr;did=T5NLXQ2TIB2VD72Z>,<sip:mo@10.80.0.5:5080;lr;did=UKBWOZWSS4TOTU2S>,<sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5060;lr;r2=on;did=I25F2O4WA3UDJRBO>,<sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5063;transport=tcp;lr;r2=on;did=I25F2O4WA3UDJRBO;ue>
Content-Length: 0
Session-Expires: 1800;refresher=uac
Session-ID: 2f535e1210995f73ba5ff1bb6bda34d5
Server: Core-Z5 N1982U.6.02.09.FR00
Require: timer,100rel
Contact: <sip:b394eba0-c3ed-4e54-adf4-83d317ca2979@10.46.0.2:43300>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Supported: 100rel,from-change,tdialog
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
P-Asserted-Identity: <tel:+15550000005>
P-Asserted-Identity: <sip:+15550000005@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

