BYE sip:15550000002@10.46.0.3:49165 SIP/2.0
To: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=8b4182f4
From: <tel:15550000005;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=102907630
Call-ID: f234da03b74dd2e5@10.46.0.3
CSeq: 2 BYE
Via: SIP/2.0/TCP 10.46.0.2:43300;branch=z9hG4bK628409088
Max-Forwards: 70
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=0010100000100066C000
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=191483176;spi-s=53304908;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Route: <sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5063;transport=tcp;lr;r2=on;did=VF2DKULG7AK3QLVK;ue>,<sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5060;lr;r2=on;did=VF2DKULG7AK3QLVK>,<sip:mt@10.80.0.5:5080;lr;did=T5NLXQ2TIB2VD72Z>,<sip:mo@10.80.0.5:5080;lr;did=UKBWOZWSS4TOTU2S>,<sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5060;lr;r2=on;did=I25F2O4WA3UDJRBO>,<sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5063;transport=tcp;lr;r2=on;did=I25F2O4WA3UDJRBO;ue>
P-Preferred-Identity: <sip:15550000005@ims.mnc001.mcc001.3gppnetwork.org>
Require: sec-agree
Proxy-Require: sec-agree
Reason: RELEASE_CAUSE ;cause=1 ;text="User ends call"
User-Agent: Core-Z5 N1982U.6.02.09.FR00
Session-ID: 2f535e1210995f73ba5ff1bb6bda34d5
Content-Length: 0

