SIP/2.0 200 OK
From: <tel:15550000005;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=102907630
To: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=8b4182f4
Contact: <sip:15550000002@10.46.0.3:49165>;+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video
Call-ID: f234da03b74dd2e5@10.46.0.3
CSeq: 2 BYE
Max-Forwards: 70
Via: SIP/2.0/TCP 10.46.0.2:43300;branch=z9hG4bK628409088
Accept-Contact: *;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel"
Content-Length: 0
Server: Google_Pixel10a_Android 16_BD6A.251031.001.A4

