SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKQNNOAOIA75FV3NWZBYT5LBXZ6D,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK4VFOMVTEONZ4O66NL4RTWPREH3,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bKVVVHFXVIWOJK3EVBHLKVBMZWQ7,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKYKZH2FJCBWX4WL76BCP4GYZJIO,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKSE25V5FUV4QGAG62FWKHJMNZSU,SIP/2.0/TCP 10.46.0.5:6100;branch=z9hG4bK-524287-1---308562a050de63c6;rport=6101;transport=TCP;received=10.46.0.5
Record-Route: <sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5063;transport=tcp;lr;r2=on;did=3UVFE7TGRX4IMJJ2;ue>,<sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5060;lr;r2=on;did=3UVFE7TGRX4IMJJ2>,<sip:mt@10.80.0.5:5080;lr;did=PVUCXWWT3NOWZVAR>,<sip:mo@10.80.0.5:5080;lr;did=PXZFFJC7HFBRHS6O>,<sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5060;lr;r2=on;did=WN2QGXYIM74URNZW>,<sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5063;transport=tcp;lr;r2=on;did=WN2QGXYIM74URNZW;ue>
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=6567771
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=799bc610
Call-ID: M7fI0X_bWWJ8IkGXKd2qGg..@10.46.0.5
CSeq: 1 INVITE
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
RSeq: 2
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=9990100010019B01
Contact: <sip:8476f6db-5c6a-4256-a0dd-69db67bd85bd@10.46.0.10:44417>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

