PRACK sip:8476f6db-5c6a-4256-a0dd-69db67bd85bd@10.46.0.10:44417 SIP/2.0
Via: SIP/2.0/UDP 10.46.0.5:6100;branch=z9hG4bK-524287-1---1266a2ed8d5295a9;rport;transport=UDP
Max-Forwards: 70
Route: <sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5063;transport=tcp;lr;r2=on;did=WN2QGXYIM74URNZW;ue>
Route: <sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5060;lr;r2=on;did=WN2QGXYIM74URNZW>
Route: <sip:mo@10.80.0.5:5080;lr;did=PXZFFJC7HFBRHS6O>
Route: <sip:mt@10.80.0.5:5080;lr;did=PVUCXWWT3NOWZVAR>
Route: <sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5060;lr;r2=on;did=3UVFE7TGRX4IMJJ2>
Route: <sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5063;transport=tcp;lr;r2=on;did=3UVFE7TGRX4IMJJ2;ue>
Proxy-Require: sec-agree
Require: sec-agree
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=6567771
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=799bc610
Call-ID: M7fI0X_bWWJ8IkGXKd2qGg..@10.46.0.5
CSeq: 4 PRACK
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=132102118;spi-s=104856785;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
RAck: 2 1 INVITE
P-Preferred-Identity: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=9990100010019b01
Content-Length: 0

