CANCEL sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone SIP/2.0
Via: SIP/2.0/TCP 10.46.0.5:6100;branch=z9hG4bK-524287-1---308562a050de63c6;rport;transport=TCP
Max-Forwards: 70
Route: <sip:10.80.0.5:5063;lr>
Route: <sip:orig-51@scscf.ims.mnc001.mcc999.3gppnetwork.org:5080;lr>
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=799bc610
Call-ID: M7fI0X_bWWJ8IkGXKd2qGg..@10.46.0.5
CSeq: 1 CANCEL
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=132102118;spi-s=104856785;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
P-Preferred-Identity: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>
Content-Length: 0

