PRACK sip:3b7d83d2-0108-4629-a2dd-0f4c6e59a52d@10.46.0.6:40117 SIP/2.0
Via: SIP/2.0/UDP 10.46.0.5:6500;branch=z9hG4bK-524287-1---211a9f144d1040eb;rport;transport=UDP
Max-Forwards: 70
Route: <sip:yuvey7vgymc2aajptku4giz3c7@10.80.0.5:5063;transport=tcp;lr;r2=on;did=RTEXECWX4JG72SOL;ue>
Route: <sip:yuvey7vgymc2aajptku4giz3c7@10.80.0.5:5060;lr;r2=on;did=RTEXECWX4JG72SOL>
Route: <sip:mo@10.80.0.5:5080;lr;did=SFRRWN55URLYEDVY>
Route: <sip:mt@10.80.0.5:5080;lr;did=EHQA36QRI2KJR6G6>
Route: <sip:a4jyxqxxrkgzk5gcxwc37cj5mu@10.80.0.5:5060;lr;r2=on;did=JZKNSMCQQUGFEAX2>
Route: <sip:a4jyxqxxrkgzk5gcxwc37cj5mu@10.80.0.5:5063;transport=tcp;lr;r2=on;did=JZKNSMCQQUGFEAX2;ue>
Proxy-Require: sec-agree
Require: sec-agree
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=98165090
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=f760af74
Call-ID: UABUq-3ZLXm8QvgUlGitfg..@10.46.0.5
CSeq: 2 PRACK
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=32747763;spi-s=218694833;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
RAck: 1 1 INVITE
P-Preferred-Identity: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=9990100000100066c000
Content-Length: 0

