SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.5:6500;branch=z9hG4bK-524287-1---77ed7d620fb58e77;rport=6501;transport=TCP;received=10.46.0.5
Record-Route: <sip:a4jyxqxxrkgzk5gcxwc37cj5mu@10.80.0.5:5063;transport=tcp;lr;r2=on;did=JZKNSMCQQUGFEAX2;ue>,<sip:a4jyxqxxrkgzk5gcxwc37cj5mu@10.80.0.5:5060;lr;r2=on;did=JZKNSMCQQUGFEAX2>,<sip:mt@10.80.0.5:5080;lr;did=EHQA36QRI2KJR6G6>,<sip:mo@10.80.0.5:5080;lr;did=SFRRWN55URLYEDVY>,<sip:yuvey7vgymc2aajptku4giz3c7@10.80.0.5:5060;lr;r2=on;did=RTEXECWX4JG72SOL>,<sip:yuvey7vgymc2aajptku4giz3c7@10.80.0.5:5063;transport=tcp;lr;r2=on;did=RTEXECWX4JG72SOL;ue>
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=98165090
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=f760af74
Call-ID: UABUq-3ZLXm8QvgUlGitfg..@10.46.0.5
CSeq: 1 INVITE
Session-Expires: 1800;refresher=uac
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
Require: timer,100rel
Contact: <sip:3b7d83d2-0108-4629-a2dd-0f4c6e59a52d@10.46.0.6:40117>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Supported: 100rel,from-change,tdialog
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
P-Asserted-Identity: <tel:+15550000008>
P-Asserted-Identity: <sip:+15550000008@ims.mnc001.mcc999.3gppnetwork.org;user=phone>

