BYE sip:3b7d83d2-0108-4629-a2dd-0f4c6e59a52d@10.46.0.6:40117 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKGLXQR2GW3MH6BHCVW55XQP7UXG
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKQ5WXTOJ5RQRRTA4WBCSEMKICLI
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK7SX23WATA5HIHQ472W5XVGUJEG
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKJVWXYSYGMAMPC2LVF3CNBBVHHA
Via: SIP/2.0/UDP 10.46.0.5:6500;branch=z9hG4bK-524287-1---89c91e65dd7d9308;rport=6500;transport=UDP;received=10.46.0.5
Max-Forwards: 66
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=98165090
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=f760af74
Call-ID: UABUq-3ZLXm8QvgUlGitfg..@10.46.0.5
CSeq: 5 BYE
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
Content-Length: 0

