SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.46.0.24:49165;branch=z9hG4bK920c56c3fd6211a6bb7dafa8
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=ab18f589
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=bRABJFaV9n
Call-ID: 862e30ad6cde66d6@10.46.0.24
CSeq: 1 INVITE
Record-Route: <sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;did=RYBXHCUN44B7UCES;lr;r2=on;transport=tcp;ue>, <sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;did=RYBXHCUN44B7UCES;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=4MURNPCV7TJ66XLJ;lr>, <sip:mo@10.80.0.5:5080;did=4EXJF5HUSGZY2TMH;lr>, <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;did=TIVIL3N3DS2ATHZL;lr;r2=on>, <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;did=TIVIL3N3DS2ATHZL;lr;r2=on;transport=tcp;ue>
Session-ID: 7004bf312be752b0a38251f15d339a70
Contact: <sip:10.46.0.25:63507>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.srvcc-alerting;audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0
P-Asserted-Identity: <tel:+15550000006>
P-Asserted-Identity: <sip:+15550000006@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

