SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKD4NXODPFM3353ZZQOWSVBHGYPI,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKPBIWESNKA2V7Z6SBTUUAFHBZAL,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bKW244VG5HZGWLEFHA3G6AW5LYGD,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKQBT2NYC5W6VE7QSQEKTHSA33SU,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKGSGL2BLMJF42NYICJ6ZI5MLZK6,SIP/2.0/TCP 10.46.0.24:49165;branch=z9hG4bK920c56c3fd6211a6bb7dafa8
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=ab18f589
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=bRABJFaV9n
Call-ID: 862e30ad6cde66d6@10.46.0.24
CSeq: 1 INVITE
Record-Route: <sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;did=RYBXHCUN44B7UCES;lr;r2=on;transport=tcp;ue>, <sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;did=RYBXHCUN44B7UCES;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=4MURNPCV7TJ66XLJ;lr>, <sip:mo@10.80.0.5:5080;did=4EXJF5HUSGZY2TMH;lr>, <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;did=TIVIL3N3DS2ATHZL;lr;r2=on>, <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;did=TIVIL3N3DS2ATHZL;lr;r2=on;transport=tcp;ue>
Session-ID: 7004bf312be752b0a38251f15d339a70
Supported: 100rel,path,replaces,timer
Session-Expires: 1800;refresher=uac
Require: timer
Contact: <sip:10.46.0.25:63507>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Content-Length: 0

