BYE sip:10.46.0.25:63507 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKHQHVNS4RZMVM4B3LF3GCOSPMUM
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKWPAX3IMKLABB6RF2FXWVFVP424
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK2QN5DJCLZP3SJPVMKSTMSWDPCS
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKOUUKEKQG23BN5DEQBTZWXCRIDL
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=ab18f589
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=bRABJFaV9n
Contact: <sip:15550000002@10.46.0.24:49165>;+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video
Call-ID: 862e30ad6cde66d6@10.46.0.24
CSeq: 4 BYE
Max-Forwards: 66
Via: SIP/2.0/TCP 10.46.0.24:49165;branch=z9hG4bK52793d0fc857c91fdfbd5fa8
Content-Length: 0
Reason: RELEASE_CAUSE;cause=1;text="User ends call"
User-Agent: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Session-ID: 7004bf312be752b0a38251f15d339a70

