SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.24:49165;branch=z9hG4bK52793d0fc857c91fdfbd5fa8
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=ab18f589
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=bRABJFaV9n
Call-ID: 862e30ad6cde66d6@10.46.0.24
CSeq: 4 BYE
Session-ID: 7004bf312be752b0a38251f15d339a70
Contact: <sip:10.46.0.25:63507>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

