SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKGVBNCB4FZLUSESWMPGUNDIOCBR
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKE2J33PXQ4V5OJNNOMPNOD5ZLR3
Via: SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bKYJR7FPIHFTITQVVANI4XEGO7BV
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKQ55TNKVOQPL6OZIOBTZ4RDYJK4
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKGRNVHYQOFGAYB432XH622THRL7
Via: SIP/2.0/TCP 10.46.0.8:41989;branch=z9hG4bK3629178243
Max-Forwards: 70
Record-Route: <sip:3iqp554vb5dijnjmjo2u3xbt2t@10.80.0.5:5063;transport=tcp;lr;r2=on;did=FLUIUSQENRDFGD2K;ue>
Record-Route: <sip:3iqp554vb5dijnjmjo2u3xbt2t@10.80.0.5:5060;lr;r2=on;did=FLUIUSQENRDFGD2K>
Record-Route: <sip:mt@10.80.0.5:5080;lr;did=Q6G6GKCZOK2FLXON>
Record-Route: <sip:mo@10.80.0.5:5080;lr;did=EVNTE6S5UQASFCPT>
Record-Route: <sip:75xi5p5r4lmyujqtijnkhr24d7@10.80.0.5:5060;lr;r2=on;did=OFUBLLFGBYHHRK5W>
Record-Route: <sip:75xi5p5r4lmyujqtijnkhr24d7@10.80.0.5:5063;transport=tcp;lr;r2=on;did=OFUBLLFGBYHHRK5W;ue>
Require: 100rel
Contact: <sip:15550000007@10.46.0.7:6600>;+sip.instance="<urn:gsma:imei:00000000-000007-0>";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting
To: <tel:15550000007;phone-context=ims.mnc001.mcc999.3gppnetwork.org>;tag=23426e4a
From: <sip:15550000008@ims.mnc001.mcc999.3gppnetwork.org>;tag=100699893
Call-ID: 100699886_3068622352@10.46.0.8
CSeq: 100699886 INVITE
Supported: timer, 100rel, precondition
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
RSeq: 2
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=9990100000100066c000
Content-Length: 0

