BYE sip:15550000002@10.46.0.24:49165 SIP/2.0
Reason: SIP;cause=200;text="User Triggered"
To: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=5dbd15fa
Route: <sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;did=BP4ZIIWE7C4BAQTB;lr;r2=on;transport=tcp;ue>, <sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;did=BP4ZIIWE7C4BAQTB;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=GPUBPJIVDZ5BJCZ4;lr>, <sip:mo@10.80.0.5:5080;did=NDT3AW34I34W4GUJ;lr>, <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;did=IDI2ZWJH2JYXERQO;lr;r2=on>, <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;did=IDI2ZWJH2JYXERQO;lr;r2=on;transport=tcp;ue>
From: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=4OowVpBWzJ
Call-ID: 2fe61b022ddfe082@10.46.0.24
Session-ID: 7f855f9310a1594980f338b8521adda3
Contact: <sip:10.46.0.25:63507>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 1 BYE
Via: SIP/2.0/TCP 10.46.0.25:63507;branch=z9hG4bKVV1OQLRVgOWhi7y;rport
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
P-Preferred-Identity: sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5064;port-s=5063;prot=esp;q=0.1;spi-c=8430301;spi-s=114600604
Require: sec-agree
Proxy-Require: sec-agree
Content-Length: 0

