BYE sip:15550000002@10.46.0.24:49165 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bK6LCV42K6N4OB72WJI4WMLTOP7K
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKFVHREKNBB5JF4WNVIPRADKIAY7
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKS5HHDCNWYIKECUCQZBDLRWM3LO
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKFG7AKCBKGYV3UD3SHCCODYT2GK
Reason: SIP;cause=200;text="User Triggered"
To: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=5dbd15fa
From: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=4OowVpBWzJ
Call-ID: 2fe61b022ddfe082@10.46.0.24
Session-ID: 7f855f9310a1594980f338b8521adda3
Contact: <sip:10.46.0.25:63507>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 1 BYE
Via: SIP/2.0/TCP 10.46.0.25:63507;branch=z9hG4bKVV1OQLRVgOWhi7y;rport=64105;received=10.46.0.25
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

