SIP/2.0 200 OK
From: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=4OowVpBWzJ
To: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=5dbd15fa
Contact: <sip:15550000002@10.46.0.24:49165>;+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video
Call-ID: 2fe61b022ddfe082@10.46.0.24
CSeq: 1 BYE
Max-Forwards: 70
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bK6LCV42K6N4OB72WJI4WMLTOP7K,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKFVHREKNBB5JF4WNVIPRADKIAY7,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKS5HHDCNWYIKECUCQZBDLRWM3LO,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKFG7AKCBKGYV3UD3SHCCODYT2GK,SIP/2.0/TCP 10.46.0.25:63507;received=10.46.0.25;branch=z9hG4bKVV1OQLRVgOWhi7y;rport=64105
Accept-Contact: *;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel"
Content-Length: 0
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010019b01
Server: Google_Pixel10a_Android 16_BD6A.251031.001.A4

