SIP/2.0 401 Unauthorized
To: <sip:001010000000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=NC2JAQMX6D74T53EJLYDJVYPDT
From: <sip:001010000000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=zlZYXDYSk9
Call-ID: UzMyDuSCJFHdwcWqjUtQI3Mr
CSeq: 1 REGISTER
Via: SIP/2.0/TCP 10.46.0.16:5060;branch=z9hG4bK30hKnwNchlF7YGD;rport=49168;received=10.46.0.16
Content-Length: 0
WWW-Authenticate: Digest realm="ims.mnc001.mcc001.3gppnetwork.org", nonce="u9RzEbqPR056xWPdNz3VWpdWKVnbAoAADVpbFM2RT4w=", algorithm=AKAv1-MD5, qop="auth"
Security-Server: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=243438823;spi-s=105173783;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Supported: sec-agree

