SIP/2.0 200 OK
To: <sip:001010000000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=RPQ4WQB5HYSECXML7LAME2MZQP
From: <sip:001010000000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=LpxKkN42b0
Call-ID: UzMyDuSCJFHdwcWqjUtQI3Mr
CSeq: 2 REGISTER
Via: SIP/2.0/TCP 10.46.0.16:56059;branch=z9hG4bK0lITMsuMHYuAT1t;rport=59928;received=10.46.0.16
Content-Length: 0
Path: <sip:vseahg6apgnxmea47cvubdhxct@10.80.0.5:5060;lr>
Service-Route: <sip:orig-25@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
P-Associated-URI: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>, <tel:+15550000006>
Contact: <sip:10.46.0.16:56059>;+g.3gpp.accesstype="cellular2";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.smsip;+g.3gpp.srvcc-alerting;+sip.instance="<urn:gsma:imei:00000000-000004-0>";audio;expires=3599

