SUBSCRIBE sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
Expires: 600000
Event: reg
Accept: application/reginfo+xml
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=8GWk4Q80C1
To: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>
Call-ID: 9SvyIm5YAlAUC3wh5ZpFS5Pp
Session-ID: fcd4611ab35605ddc7b34c3df4e5df50
Contact: sip:10.46.0.16:56059
CSeq: 1 SUBSCRIBE
Via: SIP/2.0/UDP 10.46.0.16:56059;branch=z9hG4bKXkjagsYQBmZzr8F;rport
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
P-Preferred-Identity: sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5064;port-s=5063;prot=esp;q=0.1;spi-c=243438823;spi-s=105173783
Require: sec-agree
Proxy-Require: sec-agree
Route: <sip:10.80.0.5:5063;lr>, <sip:orig-25@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
Content-Length: 0

