SIP/2.0 200 OK
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=8GWk4Q80C1
To: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=P2IWRFJEQLYGKIJA3256LS7SEH
Call-ID: 9SvyIm5YAlAUC3wh5ZpFS5Pp
CSeq: 1 SUBSCRIBE
Via: SIP/2.0/UDP 10.46.0.16:56059;branch=z9hG4bKXkjagsYQBmZzr8F;rport=56059;received=10.46.0.16
Record-Route: <sip:vseahg6apgnxmea47cvubdhxct@10.80.0.5:5060;lr;r2=on>
Record-Route: <sip:vseahg6apgnxmea47cvubdhxct@10.80.0.5:5063;lr;r2=on;ue>
Content-Length: 0
Expires: 600000
Contact: <sip:10.80.0.5:5080>

