SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKQAGMXX2XPB5UWIFE3S34F4KRLB,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKDBQIBFPF5ESDTMK2CIX5Y4AP3Y
Record-Route: <sip:vseahg6apgnxmea47cvubdhxct@10.80.0.5:5063;lr;r2=on;ue>, <sip:vseahg6apgnxmea47cvubdhxct@10.80.0.5:5060;lr;r2=on>
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=P2IWRFJEQLYGKIJA3256LS7SEH
To: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=8GWk4Q80C1
Call-ID: 9SvyIm5YAlAUC3wh5ZpFS5Pp
CSeq: 392697014 NOTIFY
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Content-Length: 0

