REGISTER sip:ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
From: <sip:001010000000001@ims.mnc001.mcc001.3gppnetwork.org>;tag=2180907
To: <sip:001010000000001@ims.mnc001.mcc001.3gppnetwork.org>
CSeq: 2180901 REGISTER
Call-ID: 2180901_4111866560@10.46.0.7
Max-Forwards: 70
Contact: <sip:1b4261b8-485f-4f9e-a1af-589ac5cae854@10.46.0.7:5060>;+g.3gpp.accesstype="cellular2";+g.3gpp.ps-data-off="inactive";audio;+g.3gpp.nw-init-ussi;+g.3gpp.smsip;video;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+sip.instance="<urn:gsma:imei:00000000-000001-0>"
Via: SIP/2.0/TCP 10.46.0.7:5060;branch=z9hG4bK3048422452
Expires: 600000
Require: sec-agree
Proxy-Require: sec-agree
Supported: path,sec-agree
Allow: INVITE,BYE,CANCEL,ACK,NOTIFY,UPDATE,PRACK,INFO,MESSAGE,OPTIONS
Authorization: Digest uri="sip:ims.mnc001.mcc001.3gppnetwork.org",username="001010000000001@ims.mnc001.mcc001.3gppnetwork.org",response="",realm="ims.mnc001.mcc001.3gppnetwork.org",nonce=""
User-Agent: PRD-IR92/12 term-Motorola/XT2417-1-V1UFN35H.193-20 device-type/smart-phone
Security-Client: ipsec-3gpp; alg=hmac-md5-96; ealg=des-ede3-cbc; spi-c=2504075683; spi-s=3546675808; port-c=43623; port-s=41498,ipsec-3gpp; alg=hmac-md5-96; ealg=aes-cbc; spi-c=2504075683; spi-s=3546675808; port-c=43623; port-s=41498,ipsec-3gpp; alg=hmac-md5-96; ealg=null; spi-c=2504075683; spi-s=3546675808; port-c=43623; port-s=41498,ipsec-3gpp; alg=hmac-sha-1-96; ealg=des-ede3-cbc; spi-c=2504075683; spi-s=3546675808; port-c=43623; port-s=41498,ipsec-3gpp; alg=hmac-sha-1-96; ealg=aes-cbc; spi-c=2504075683; spi-s=3546675808; port-c=43623; port-s=41498,ipsec-3gpp; alg=hmac-sha-1-96; ealg=null; spi-c=2504075683; spi-s=3546675808; port-c=43623; port-s=41498
Content-Length: 0

