SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKWUYEU5YSNXBYKNZ5WNM3W5KB7U,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKO6XTRE6UFKPZUYQSI6RONQZILA,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bK543ST254DOO4WEUSBRKYNJNIJI,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKQHKRSFTSTTFNPUU5YRV3BRHYTZ,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKDZ37U3T456Z6MVWT5YCFHCLX4U,SIP/2.0/TCP 10.46.0.15:43435;branch=z9hG4bK833306649
From: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>;tag=2338394
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=pKDAwsLQsF
CSeq: 2338387 INVITE
Call-ID: 2338387_3069112144@10.46.0.15
Record-Route: <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=UA6GW5KBATBM63DW;lr;r2=on;transport=tcp;ue>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=UA6GW5KBATBM63DW;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=PB5JDLZ373UDY2NT;lr>, <sip:mo@10.80.0.5:5080;did=KEAATBOI7DZVIHM3;lr>, <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;did=5KMZ6TICTZ77OVZG;lr;r2=on>, <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;did=5KMZ6TICTZ77OVZG;lr;r2=on;transport=tcp;ue>
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.srvcc-alerting;audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Content-Length: 0

