SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.15:43435;branch=z9hG4bK833306649
From: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>;tag=2338394
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=pKDAwsLQsF
CSeq: 2338387 INVITE
Call-ID: 2338387_3069112144@10.46.0.15
Record-Route: <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=UA6GW5KBATBM63DW;lr;r2=on;transport=tcp;ue>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=UA6GW5KBATBM63DW;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=PB5JDLZ373UDY2NT;lr>, <sip:mo@10.80.0.5:5080;did=KEAATBOI7DZVIHM3;lr>, <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;did=5KMZ6TICTZ77OVZG;lr;r2=on>, <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;did=5KMZ6TICTZ77OVZG;lr;r2=on;transport=tcp;ue>
Supported: 100rel,path,replaces,timer
Session-Expires: 1800;refresher=uac
Require: timer
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
User-Agent: iOS/27.0 iPhone
Content-Length: 0
P-Asserted-Identity: <tel:+15550000006>
P-Asserted-Identity: <sip:+15550000006@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

