BYE sip:10.46.0.17:61189 SIP/2.0
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=pKDAwsLQsF
From: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>;tag=2338394
Call-ID: 2338387_3069112144@10.46.0.15
CSeq: 2338390 BYE
Via: SIP/2.0/TCP 10.46.0.15:43435;branch=z9hG4bK3984999586
Max-Forwards: 70
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015EE0000
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=113224940;spi-s=105724704;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Content-Length: 0
Route: <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;did=5KMZ6TICTZ77OVZG;lr;r2=on;transport=tcp;ue>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;did=5KMZ6TICTZ77OVZG;lr;r2=on>,<sip:mo@10.80.0.5:5080;did=KEAATBOI7DZVIHM3;lr>,<sip:mt@10.80.0.5:5080;did=PB5JDLZ373UDY2NT;lr>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=UA6GW5KBATBM63DW;lr;r2=on>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=UA6GW5KBATBM63DW;lr;r2=on;transport=tcp;ue>
P-Preferred-Identity: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>
Reason: RELEASE_CAUSE ;cause=1 ;text="User ends call"
User-Agent: Core-Z5 N1982U.6.02.09.FR00
Require: sec-agree
Proxy-Require: sec-agree

