SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bK1h5AIvUotTPeSMn;rport=57130;received=10.46.0.17
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=0gspRBhnpF
To: <tel:+15550000004>;tag=2226378
Call-ID: THOnWNLR7VIfZr9dHlVFUbGr
Session-ID: f8add290e4f735fa54c3199eda201cbc
CSeq: 1 INVITE
Record-Route: <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;transport=tcp;lr;r2=on;did=KSPJ46SRNXXX3GOS;ue>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;lr;r2=on;did=KSPJ46SRNXXX3GOS>,<sip:mt@10.80.0.5:5080;lr;did=K7K44XPFOB6SDUWX>,<sip:mo@10.80.0.5:5080;lr;did=3PHXBD5AX6VHYDGQ>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;lr;r2=on;did=V6XZ6C4O6D62QQZL>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;transport=tcp;lr;r2=on;did=V6XZ6C4O6D62QQZL;ue>
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
RSeq: 2
Contact: <sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
P-Asserted-Identity: <tel:+15550000004>
P-Asserted-Identity: <sip:+15550000004@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

