PRACK sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKHB55RZGIS3DVLKTBQNPKIYK6JL
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKC5O2NJSV4JTUSLJAYSO56BVOQP
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKLZ75IAODYM6S3TQ6YBXSKIMLA3
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKIFT2SF6BCBAX6JWWITMMENMYXM
RAck: 2 1 INVITE
To: <tel:+15550000004>;tag=2226378
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=0gspRBhnpF
Call-ID: THOnWNLR7VIfZr9dHlVFUbGr
Session-ID: f8add290e4f735fa54c3199eda201cbc
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 4 PRACK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKtxd3mO4LYTovOCa;rport=57130;received=10.46.0.17
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

