PRACK sip:cbcd92dc-db6f-4aea-a207-e26b95efb9f2@10.46.0.8:41989 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKRX5EGOG7BECI7BXRM2LKWSMG2R
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKDKRZQMQ7WX4NEQXZF4ELU3EAQP
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKEZLJGZ5EXWFJM6PZ4Z3DEC4JVT
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKV2WA22HGCZ3Y2CBZDC6ZB5HXGN
Via: SIP/2.0/UDP 10.46.0.7:6600;branch=z9hG4bK-524287-1---07d4a1890468b591;rport=6600;transport=UDP;received=10.46.0.7
Max-Forwards: 66
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=100223009
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=14031060
Call-ID: o9voWSJ5T_Wr2ef6EsB2vg..@10.46.0.7
CSeq: 2 PRACK
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
RAck: 1 1 INVITE
Content-Length: 0

