SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKMC4VNTEGFF3WH72PSOYQCYDQLG,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKOJTHPRWSYTBKHTVLK4JBA2YQC7,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bKDXDXID7DZSI4GSZFZYFFAHYTIJ,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKFILYCZNH6CIEIMP6C2I7U3PJX6,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bK2HR6ITURCMKQUHGPY4IIMMRF57,SIP/2.0/TCP 10.46.0.7:6600;branch=z9hG4bK-524287-1---dd4018ba1020543f;rport=6601;transport=TCP;received=10.46.0.7
Record-Route: <sip:75xi5p5r4lmyujqtijnkhr24d7@10.80.0.5:5063;transport=tcp;lr;r2=on;did=2AXOPYHCFZJCPDGI;ue>,<sip:75xi5p5r4lmyujqtijnkhr24d7@10.80.0.5:5060;lr;r2=on;did=2AXOPYHCFZJCPDGI>,<sip:mt@10.80.0.5:5080;lr;did=LMFV3M434C4WGM5L>,<sip:mo@10.80.0.5:5080;lr;did=PRWHK5F2LTQVRP77>,<sip:3iqp554vb5dijnjmjo2u3xbt2t@10.80.0.5:5060;lr;r2=on;did=W4LQBCOD7YORI5O7>,<sip:3iqp554vb5dijnjmjo2u3xbt2t@10.80.0.5:5063;transport=tcp;lr;r2=on;did=W4LQBCOD7YORI5O7;ue>
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=100223009
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=14031060
Call-ID: o9voWSJ5T_Wr2ef6EsB2vg..@10.46.0.7
CSeq: 1 INVITE
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
RSeq: 2
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=9990100000100066C000
Contact: <sip:cbcd92dc-db6f-4aea-a207-e26b95efb9f2@10.46.0.8:41989>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

