SIP/2.0 200 OK
Via: SIP/2.0/UDP 10.46.0.7:6600;branch=z9hG4bK-524287-1---e041363065bdb708;rport=6600;transport=UDP;received=10.46.0.7
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=100223009
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=14031060
Call-ID: o9voWSJ5T_Wr2ef6EsB2vg..@10.46.0.7
CSeq: 4 PRACK
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
Supported: 100rel,from-change,tdialog
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

