SIP/2.0 486 Busy Here
Via: SIP/2.0/TCP 10.46.0.7:6600;branch=z9hG4bK-524287-1---dd4018ba1020543f;rport=6601;transport=TCP;received=10.46.0.7
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=100223009
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=14031060
Call-ID: o9voWSJ5T_Wr2ef6EsB2vg..@10.46.0.7
CSeq: 1 INVITE
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

