SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bK5SGJJMTJVDTAYK2NASWRTMJUL2,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKRSWOY6CS7LHD4NP5QBBBMKQH6A,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKJOABFTRADNZXGOMOZWQFICCMBD,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKLRUHGQKIAOVHY4YYU5VEUICF5M,SIP/2.0/UDP 10.46.0.5:6100;branch=z9hG4bK-524287-1---d0abca3efc57c8d1;rport=6100;transport=UDP;received=10.46.0.5
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=6108878
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=d9d80d7e
Call-ID: pFnJ7GJsA1lFS6RnnqR7OQ..@10.46.0.5
CSeq: 2 PRACK
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=9990100010019B01
Supported: 100rel,from-change,tdialog
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

