PRACK sip:8476f6db-5c6a-4256-a0dd-69db67bd85bd@10.46.0.10:44417 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKKQJUDJTLFNYDDNKABVX3MCYW5T
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKKO6HD4KRN63GH6UJE6VJLGUMWQ
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKYH2M2YIZ5F4DTXIRNANX4OSMP5
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKDWCEXM7I5BL2N25OXNCIXLBE27
Via: SIP/2.0/UDP 10.46.0.5:6100;branch=z9hG4bK-524287-1---cd93611682b345ef;rport=6100;transport=UDP;received=10.46.0.5
Max-Forwards: 66
To: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=6108878
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=d9d80d7e
Call-ID: pFnJ7GJsA1lFS6RnnqR7OQ..@10.46.0.5
CSeq: 4 PRACK
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
RAck: 2 1 INVITE
Content-Length: 0

