BYE sip:15550000007@10.46.0.5:6100 SIP/2.0
To: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=d9d80d7e
From: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=6108878
Call-ID: pFnJ7GJsA1lFS6RnnqR7OQ..@10.46.0.5
CSeq: 2 BYE
Via: SIP/2.0/TCP 10.46.0.10:44417;branch=z9hG4bK3662726415
Max-Forwards: 70
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=9990100010019B01
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=117444731;spi-s=130227876;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Route: <sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5063;transport=tcp;lr;r2=on;did=HC5EY7BWG6YB5UOG;ue>,<sip:hgmaj5sms7v54nx74sze7jdv7u@10.80.0.5:5060;lr;r2=on;did=HC5EY7BWG6YB5UOG>,<sip:mt@10.80.0.5:5080;lr;did=GNKPSO4B7POZXKIF>,<sip:mo@10.80.0.5:5080;lr;did=RBO6VKZFIRV3QACV>,<sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5060;lr;r2=on;did=QA7Y3HXXOAMMSW7Y>,<sip:xecajs2762idoehm7nsyclb72l@10.80.0.5:5063;transport=tcp;lr;r2=on;did=QA7Y3HXXOAMMSW7Y;ue>
P-Preferred-Identity: <sip:15550000008@ims.mnc001.mcc999.3gppnetwork.org>
Require: sec-agree
Proxy-Require: sec-agree
Reason: RELEASE_CAUSE ;cause=1 ;text="User ends call"
User-Agent: Core-Z5 N1982U.6.02.09.FR00
Content-Length: 0

