SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKDBJZUHOJ7XE2G6KRHIUHRF3ZXG
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK4724WGVKXCLDY355EJYGPKDMZB
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKD4XAL4GSJE7ZKO3X2TM5V5GXAI
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKKYB4PNE6QHTKEDNARTZOJXNCZN
Via: SIP/2.0/TCP 10.46.0.10:44417;branch=z9hG4bK3662726415
Max-Forwards: 70
Contact: <sip:15550000007@10.46.0.5:6100>;+sip.instance="<urn:gsma:imei:00000000-000007-0>";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting
To: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=d9d80d7e
From: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=6108878
Call-ID: pFnJ7GJsA1lFS6RnnqR7OQ..@10.46.0.5
CSeq: 2 BYE
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=9990100010019b01
Content-Length: 0

