SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.10:44417;branch=z9hG4bK3662726415
Max-Forwards: 70
Contact: <sip:15550000007@10.46.0.5:6100>;+sip.instance="<urn:gsma:imei:00000000-000007-0>";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting
To: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=d9d80d7e
From: <sip:15550000008;phone-context=ims.mnc001.mcc999.3gppnetwork.org@ims.mnc001.mcc999.3gppnetwork.org;user=phone>;tag=6108878
Call-ID: pFnJ7GJsA1lFS6RnnqR7OQ..@10.46.0.5
CSeq: 2 BYE
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
Content-Length: 0

