SUBSCRIBE sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
Expires: 600000
Event: reg
Accept: application/reginfo+xml
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=4OB0Or6gpc
To: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>
Call-ID: Q8wzXBzzXqvcMgXwAoCmyTRC
Session-ID: 7325f76804175e3ddb54b6205c5e91c8
Contact: sip:10.46.0.18:52940
CSeq: 1 SUBSCRIBE
Via: SIP/2.0/UDP 10.46.0.18:52940;branch=z9hG4bKaHifs436yn7k2TR;rport
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
P-Preferred-Identity: sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5064;port-s=5063;prot=esp;q=0.1;spi-c=27476008;spi-s=116450528
Require: sec-agree
Proxy-Require: sec-agree
Route: <sip:10.80.0.5:5063;lr>, <sip:orig-30@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
Content-Length: 0

