SIP/2.0 200 OK
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=4OB0Or6gpc
To: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=4CLR6DFKWRTXAJT7JVLTI6QTSN
Call-ID: Q8wzXBzzXqvcMgXwAoCmyTRC
CSeq: 1 SUBSCRIBE
Via: SIP/2.0/UDP 10.46.0.18:52940;branch=z9hG4bKaHifs436yn7k2TR;rport=52940;received=10.46.0.18
Record-Route: <sip:fyxtj42nm6sntngnwgvzyhnijx@10.80.0.5:5060;lr;r2=on>
Record-Route: <sip:fyxtj42nm6sntngnwgvzyhnijx@10.80.0.5:5063;lr;r2=on;ue>
Content-Length: 0
Expires: 600000
Contact: <sip:10.80.0.5:5080>

