SIP/2.0 200 OK
To: <sip:001010000000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=ZNSCBMH2BGI5JOR6OLLRT5BG4X
From: <sip:001010000000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=e7b0WZmIJm
Call-ID: TANy8spWzCOaV9CNalFUtERF
CSeq: 3 REGISTER
Via: SIP/2.0/UDP 10.46.0.18:52940;branch=z9hG4bKXu5LiK8n7NyGA1L;rport=52940;received=10.46.0.18
Content-Length: 0
Path: <sip:fyxtj42nm6sntngnwgvzyhnijx@10.80.0.5:5060;lr>
Contact: <sip:10.46.0.18:52940>;+g.3gpp.accesstype="cellular2";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.smsip;+g.3gpp.srvcc-alerting;+sip.instance="<urn:gsma:imei:00000000-000005-0>";audio;expires=0

