SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bK7BCHVMEMOCNHTEZ6ZFZKSNH562,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKER7JBXO475AJ6LCFTO4IQAH3V3
Record-Route: <sip:fyxtj42nm6sntngnwgvzyhnijx@10.80.0.5:5063;lr;r2=on;ue>, <sip:fyxtj42nm6sntngnwgvzyhnijx@10.80.0.5:5060;lr;r2=on>
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=4CLR6DFKWRTXAJT7JVLTI6QTSN
To: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=4OB0Or6gpc
Call-ID: Q8wzXBzzXqvcMgXwAoCmyTRC
CSeq: 602598106 NOTIFY
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Content-Length: 0

