SIP/2.0 401 Unauthorized
To: <sip:001010000000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=NU5VYRNOLTRKFHF6EG32XV5FXV
From: <sip:001010000000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=LQboDuYeCZ
Call-ID: TANy8spWzCOaV9CNalFUtERF
CSeq: 4 REGISTER
Via: SIP/2.0/UDP 10.46.0.18:5060;branch=z9hG4bKuQLmEo1FnRE2kaa;rport=5060;received=10.46.0.18
Content-Length: 0
WWW-Authenticate: Digest realm="ims.mnc001.mcc001.3gppnetwork.org", nonce="xO9lYYjpKqsTdTUdEw6PcQ0E06HUGIAAuameNIQpze4=", algorithm=AKAv1-MD5, qop="auth"
Security-Server: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=155682339;spi-s=251587190;port-c=5065;port-s=5063;alg=hmac-sha-1-96;ealg=null
Supported: sec-agree

