SIP/2.0 200 OK
To: <sip:001010000000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=WDLJQNNP7JORBIVUZQFF5Y3CKL
From: <sip:001010000000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=Mcov4FzzIt
Call-ID: TANy8spWzCOaV9CNalFUtERF
CSeq: 5 REGISTER
Via: SIP/2.0/UDP 10.46.0.18:65006;branch=z9hG4bKZ7yb4wOVJ9l8piN;rport=65006;received=10.46.0.18
Content-Length: 0
Path: <sip:yc5wf6oncq2vusfgsof6ihohf4@10.80.0.5:5060;lr>
Service-Route: <sip:orig-31@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
P-Associated-URI: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>, <tel:+15550000003>
Contact: <sip:10.46.0.18:65006>;+g.3gpp.accesstype="cellular2";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.smsip;+g.3gpp.srvcc-alerting;+sip.instance="<urn:gsma:imei:00000000-000005-0>";audio;expires=3599

