SUBSCRIBE sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
Expires: 600000
Event: reg
Accept: application/reginfo+xml
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=OYydV8vFjq
To: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>
Call-ID: 8cSVSgCYrMpfjV4wfob0tiz1
Session-ID: 1deae2237eb224279ab68d916dd5e13f
Contact: sip:10.46.0.18:65006
CSeq: 1 SUBSCRIBE
Via: SIP/2.0/UDP 10.46.0.18:65006;branch=z9hG4bKhKCBLIuP6WqhIGI;rport
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
P-Preferred-Identity: sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5065;port-s=5063;prot=esp;q=0.1;spi-c=155682339;spi-s=251587190
Require: sec-agree
Proxy-Require: sec-agree
Route: <sip:10.80.0.5:5063;lr>, <sip:orig-31@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
Content-Length: 0

