SIP/2.0 200 OK
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=OYydV8vFjq
To: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=NMTON7U7YM654HLIXUFNTWDWQ7
Call-ID: 8cSVSgCYrMpfjV4wfob0tiz1
CSeq: 1 SUBSCRIBE
Via: SIP/2.0/UDP 10.46.0.18:65006;branch=z9hG4bKhKCBLIuP6WqhIGI;rport=65006;received=10.46.0.18
Record-Route: <sip:yc5wf6oncq2vusfgsof6ihohf4@10.80.0.5:5060;lr;r2=on>
Record-Route: <sip:yc5wf6oncq2vusfgsof6ihohf4@10.80.0.5:5063;lr;r2=on;ue>
Content-Length: 0
Expires: 600000
Contact: <sip:10.80.0.5:5080>

