SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKD3NYHZACTBQSAPRZHE34PBDQ4Q,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKHVDC7JZNNKZBTAC5AX7JN4NLNK
Record-Route: <sip:yc5wf6oncq2vusfgsof6ihohf4@10.80.0.5:5063;lr;r2=on;ue>, <sip:yc5wf6oncq2vusfgsof6ihohf4@10.80.0.5:5060;lr;r2=on>
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=NMTON7U7YM654HLIXUFNTWDWQ7
To: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=OYydV8vFjq
Call-ID: 8cSVSgCYrMpfjV4wfob0tiz1
CSeq: 79029421 NOTIFY
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Content-Length: 0

