SIP/2.0 401 Unauthorized
To: <sip:001010000000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=KY3GB64VT6AWZ6WEBYP3JGTBU5
From: <sip:001010000000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=zwv34Uxvik
Call-ID: TANy8spWzCOaV9CNalFUtERF
CSeq: 6 REGISTER
Via: SIP/2.0/UDP 10.46.0.19:5060;branch=z9hG4bK0DGDwVavfknpbrI;rport=5060;received=10.46.0.19
Content-Length: 0
WWW-Authenticate: Digest realm="ims.mnc001.mcc001.3gppnetwork.org", nonce="qlU4NZ7AboHBRnmWVvJQY+LMDjmiSoAAH5Q6PRwKFdw=", algorithm=AKAv1-MD5, qop="auth"
Security-Server: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=227428419;spi-s=59663401;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Supported: sec-agree

