SIP/2.0 200 OK
To: <sip:001010000000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=JH7X5IDJHH3FBV7S2SEZCIJ5VW
From: <sip:001010000000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=BPV8YrEF5Y
Call-ID: TANy8spWzCOaV9CNalFUtERF
CSeq: 7 REGISTER
Via: SIP/2.0/UDP 10.46.0.19:54286;branch=z9hG4bKGxOCtj6Q9HgkAFP;rport=54286;received=10.46.0.19
Content-Length: 0
Path: <sip:x32syljhtyphttpzlk7ukklwna@10.80.0.5:5060;lr>
Service-Route: <sip:orig-32@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
P-Associated-URI: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>, <tel:+15550000003>
Contact: <sip:10.46.0.19:54286>;+g.3gpp.accesstype="cellular2";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.smsip;+g.3gpp.srvcc-alerting;+sip.instance="<urn:gsma:imei:00000000-000005-0>";audio;expires=3599

