SUBSCRIBE sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
Expires: 600000
Event: reg
Accept: application/reginfo+xml
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=KCuONVO9KX
To: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>
Call-ID: 9Ehg6rgeycBKJAXGHus6bmJF
Session-ID: 1cb33489f222b806e03ac41abde1f72f
Contact: sip:10.46.0.19:54286
CSeq: 1 SUBSCRIBE
Via: SIP/2.0/UDP 10.46.0.19:54286;branch=z9hG4bKSiqm1VKwLuOnD81;rport
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
P-Preferred-Identity: sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5064;port-s=5063;prot=esp;q=0.1;spi-c=227428419;spi-s=59663401
Require: sec-agree
Proxy-Require: sec-agree
Route: <sip:10.80.0.5:5063;lr>, <sip:orig-32@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
Content-Length: 0

