SIP/2.0 200 OK
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=KCuONVO9KX
To: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=BMKUZL35SNNKWTM7DPIIB5ZGNK
Call-ID: 9Ehg6rgeycBKJAXGHus6bmJF
CSeq: 1 SUBSCRIBE
Via: SIP/2.0/UDP 10.46.0.19:54286;branch=z9hG4bKSiqm1VKwLuOnD81;rport=54286;received=10.46.0.19
Record-Route: <sip:x32syljhtyphttpzlk7ukklwna@10.80.0.5:5060;lr;r2=on>
Record-Route: <sip:x32syljhtyphttpzlk7ukklwna@10.80.0.5:5063;lr;r2=on;ue>
Content-Length: 0
Expires: 600000
Contact: <sip:10.80.0.5:5080>

