SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKQ7QFP72TVB63TDS2REM4SYSBRV,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKUYM6ITUW63PJXQ5LEWXN633DSS
Record-Route: <sip:x32syljhtyphttpzlk7ukklwna@10.80.0.5:5063;lr;r2=on;ue>, <sip:x32syljhtyphttpzlk7ukklwna@10.80.0.5:5060;lr;r2=on>
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=BMKUZL35SNNKWTM7DPIIB5ZGNK
To: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=KCuONVO9KX
Call-ID: 9Ehg6rgeycBKJAXGHus6bmJF
CSeq: 1231556965 NOTIFY
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Content-Length: 0

