SIP/2.0 200 OK
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=EOBHXAMMB2
To: <tel:+15550000002>;tag=99df5ff6
Contact: <sip:15550000002@10.46.0.24:49165>;+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video
Call-ID: qfbVCVt6QJ54MV64hnH5NzAf
CSeq: 2 PRACK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKWDCMKWXZ2I3V7ADINR43MTGKOL,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK4YYLZBKGG7VLG3FNPOJ2LD5M5H,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK4GP5ELLHC27B3PMP6EBIKKMYER,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bK2QYAJF2ANA4JGFWOJCADGNP6QC,SIP/2.0/TCP 10.46.0.25:63507;received=10.46.0.25;branch=z9hG4bKkTWWgkVAbVVKvOH;rport=64105
Content-Length: 0
Allow: INVITE,CANCEL,UPDATE,PRACK,BYE,ACK,MESSAGE,SUBSCRIBE,NOTIFY,PUBLISH,REFER,INFO,OPTIONS
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010019b01
Server: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Require: precondition
Record-Route: <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;transport=tcp;lr;r2=on;ob;did=QVL5T7W4UAKQEF5C;ue>,<sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;lr;r2=on;ob;did=QVL5T7W4UAKQEF5C>,<sip:mt@10.80.0.5:5080;lr;did=2F5U5JWSV44XQ5KE>,<sip:mo@10.80.0.5:5080;lr;did=A6WQHUKUTBVHHHJN>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;lr;r2=on;did=CPNLDKUQZRYHEPCG>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;transport=tcp;lr;r2=on;did=CPNLDKUQZRYHEPCG;ue>
Session-ID: 184f160cbf8bcce60fb030aaf370cb20

