SIP/2.0 180 Ringing
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=EOBHXAMMB2
To: <tel:+15550000002>;tag=99df5ff6
Contact: <sip:15550000002@10.46.0.24:49165>;+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video
Call-ID: qfbVCVt6QJ54MV64hnH5NzAf
CSeq: 1 INVITE
Via: SIP/2.0/TCP 10.46.0.25:63507;received=10.46.0.25;branch=z9hG4bKBxL22BDuuUvZ2YY;rport=64105
Content-Length: 0
Supported: 100rel,timer
Allow: INVITE,CANCEL,UPDATE,PRACK,BYE,ACK,MESSAGE,SUBSCRIBE,NOTIFY,PUBLISH,REFER,INFO,OPTIONS
Server: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Record-Route: <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;transport=tcp;lr;did=QVL5T7W4UAKQEF5C;ob;r2=on;ue>,<sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;lr;did=QVL5T7W4UAKQEF5C;ob;r2=on>,<sip:mt@10.80.0.5:5080;lr;did=2F5U5JWSV44XQ5KE>,<sip:mo@10.80.0.5:5080;lr;did=A6WQHUKUTBVHHHJN>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;lr;did=CPNLDKUQZRYHEPCG;r2=on>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;transport=tcp;lr;did=CPNLDKUQZRYHEPCG;r2=on;ue>
Session-ID: 184f160cbf8bcce60fb030aaf370cb20
P-Asserted-Identity: <tel:+15550000002>
P-Asserted-Identity: <sip:+15550000002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

