SIP/2.0 486 Busy Here
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=EOBHXAMMB2
To: <tel:+15550000002>;tag=99df5ff6
Call-ID: qfbVCVt6QJ54MV64hnH5NzAf
CSeq: 1 INVITE
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKDISUITVTNX47644VN572JCBNC7,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK5PJ7GTOL3NDM7R3P4RXF7JJGKZ,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bKH3DB7URCRUZJGZBQWEGHFTUGFO,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKSJAJQYO3E25JHOR2KEPWSM34UN,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bK3HDEXKFK37WGLMOOUVAEBWAREF,SIP/2.0/TCP 10.46.0.25:63507;received=10.46.0.25;branch=z9hG4bKBxL22BDuuUvZ2YY;rport=64105
Content-Length: 0
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010019b01
Server: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Record-Route: <sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5063;transport=tcp;lr;did=QVL5T7W4UAKQEF5C;ob;r2=on;ue>,<sip:kieypu6ghclrut4m5ob2zhojji@10.80.0.5:5060;lr;did=QVL5T7W4UAKQEF5C;ob;r2=on>,<sip:mt@10.80.0.5:5080;lr;did=2F5U5JWSV44XQ5KE>,<sip:mo@10.80.0.5:5080;lr;did=A6WQHUKUTBVHHHJN>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5060;lr;did=CPNLDKUQZRYHEPCG;r2=on>,<sip:f3o7bgwjgdlapb2kgsbgpxeghm@10.80.0.5:5063;transport=tcp;lr;did=CPNLDKUQZRYHEPCG;r2=on;ue>
Session-ID: 184f160cbf8bcce60fb030aaf370cb20

