ACK tel:+15550000002 SIP/2.0
Call-ID: qfbVCVt6QJ54MV64hnH5NzAf
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=EOBHXAMMB2
Route: <sip:10.80.0.5:5063;lr>, <sip:orig-44@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
CSeq: 1 ACK
Via: SIP/2.0/TCP 10.46.0.25:63507;branch=z9hG4bKBxL22BDuuUvZ2YY;rport
To: <tel:+15550000002>;tag=99df5ff6
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5064;port-s=5063;prot=esp;q=0.1;spi-c=8430301;spi-s=114600604
Require: sec-agree
Proxy-Require: sec-agree
Content-Length: 0

