PRACK sip:10.46.0.17:61189 SIP/2.0
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKTJZHB6X3ZPUPOWNDAIULRH2XO2
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bK2H6S4323QBS2PYI36ZQ64MXJ42
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKEFG2YUXENMK3LUIJAAWF5ZRPIX
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKPRLYJHT3JELNKGB73XLSK3R4IR
RAck: 1 1 INVITE
To: <tel:+15550000006>;tag=rd6Yef0EEf
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=tJdvmTarUV
Call-ID: o6CM3VVHNjCGofUWCFekH1sz
Session-ID: 43533c297b74e8be3905d8c790314a9e
Contact: <sip:10.46.0.20:53718>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 2 PRACK
Via: SIP/2.0/UDP 10.46.0.20:53718;branch=z9hG4bKSpyNK0FNYal9xHl;rport=53718;received=10.46.0.20
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

