SIP/2.0 200 OK
Via: SIP/2.0/UDP 10.46.0.20:53718;branch=z9hG4bKSpyNK0FNYal9xHl;received=10.46.0.20;rport=53718
To: <tel:+15550000006>;tag=rd6Yef0EEf
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=tJdvmTarUV
Call-ID: o6CM3VVHNjCGofUWCFekH1sz
Session-ID: 43533c297b74e8be3905d8c790314a9e
CSeq: 2 PRACK
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

