SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.9:43885;branch=z9hG4bK3439066730
From: <sip:15550000008@ims.mnc001.mcc001.3gppnetwork.org>;tag=110381187
To: <sip:15550000005;phone-context=ims.mnc001.mcc001.3gppnetwork.org@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=110381076
CSeq: 110381182 INVITE
Call-ID: 110381182_4109868208@10.46.0.9
Record-Route: <sip:l2aykhrmqrls3wwcj6g7e6j3yy@10.80.0.5:5063;transport=tcp;lr;r2=on;did=5AX5VLJIYKXJI5TD;ue>,<sip:l2aykhrmqrls3wwcj6g7e6j3yy@10.80.0.5:5060;lr;r2=on;did=5AX5VLJIYKXJI5TD>,<sip:mt@10.80.0.5:5080;lr;did=UBVOTASGC3S2Q5JR>,<sip:mo@10.80.0.5:5080;lr;did=S3IWEBVY7OHMTTVY>,<sip:nsbgwhufa64gwwi7ngbk7jry6d@10.80.0.5:5060;lr;r2=on;did=7D5MQKY37NSIRTAU>,<sip:nsbgwhufa64gwwi7ngbk7jry6d@10.80.0.5:5063;transport=tcp;lr;r2=on;did=7D5MQKY37NSIRTAU;ue>
Content-Length: 0
Session-Expires: 1800;refresher=uac
Server: Core-Z5 N1982U.6.02.09.FR00
Require: timer,100rel
Contact: <sip:2da86196-c8f7-4939-af8b-fbdac4e983f2@10.46.0.8:42225>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Supported: 100rel,from-change,tdialog
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
P-Asserted-Identity: <tel:+15550000005>
P-Asserted-Identity: <sip:+15550000005@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

