SIP/2.0 100 Trying
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKK5PEBWCQZZY6VPRMJL3JKCNX4O,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKQE2JFQ6ZTJIAK4ETHNZIMYHDHC,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bKF5G625JB4QSW3RHOHB5WS2N2QN,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKJBTW6R5G6ACY4TV2A6PZSE36SS,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKIUU3QJL44WAOX7BZBLFLHAMS22,SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKX59VYrjOdi1yVnv;received=10.46.0.17;rport=57130
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=pWfyXiyFJx
To: <tel:+15550000003>
Call-ID: M49i6CXTtFhysg2iGjLihPpr
Session-ID: cc18799e4f5527507d850f597916c35b
CSeq: 1 INVITE
Record-Route: <sip:yxlpwprxmpbiklyoarggpjtb5s@10.80.0.5:5063;did=7JHJXPSACJEWNFTK;lr;r2=on;ue>, <sip:yxlpwprxmpbiklyoarggpjtb5s@10.80.0.5:5060;did=7JHJXPSACJEWNFTK;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=HIOSYATSLNSYBV6K;lr>, <sip:mo@10.80.0.5:5080;did=5QYZOYQBM4D4FTHW;lr>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=HTW2JOZARLRVSYAA;lr;r2=on>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=HTW2JOZARLRVSYAA;lr;r2=on;transport=tcp;ue>
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Content-Length: 0

