PRACK sip:10.46.0.20:53718 SIP/2.0
Via: SIP/2.0/UDP 10.80.0.5:5063;branch=z9hG4bKMAI7ZJFM5GPI6EGZPRWTMQTTSG
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKPMJWMRZUIUGM2HUNI2LHIN6JDT
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKXR4UJ7PXNJUBQKAEUUZH6CQDOC
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bK6SODTC5OLCGI24QEI7RV5GBAHX
RAck: 1 1 INVITE
To: <tel:+15550000003>;tag=pn7gRZj1q7
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=pWfyXiyFJx
Call-ID: M49i6CXTtFhysg2iGjLihPpr
Session-ID: cc18799e4f5527507d850f597916c35b
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 2 PRACK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKoDrb34VyRwj0JD6;rport=57130;received=10.46.0.17
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

