PRACK sip:10.46.0.20:53718 SIP/2.0
Via: SIP/2.0/UDP 10.80.0.5:5063;branch=z9hG4bKKBCSLYN7FZY3MHBOEKQFCVOAP4
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKK2MBE23RQ4YFSJC6FFQI6PFT32
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKOC3R7JJNGWRH6W74MHDTLU7UD7
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKXO7XE724MBX66KVILBJCYRTFM7
RAck: 2 1 INVITE
To: <tel:+15550000003>;tag=pn7gRZj1q7
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=pWfyXiyFJx
Call-ID: M49i6CXTtFhysg2iGjLihPpr
Session-ID: cc18799e4f5527507d850f597916c35b
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 4 PRACK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKcJxyL7gVIS0AGgf;rport=57130;received=10.46.0.17
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

