SUBSCRIBE tel:0398765432100 SIP/2.0
Via: SIP/2.0/UDP 192.168.101.5:6300;branch=z9hG4bK-524287-1---ca4faf42ed5e79aa;rport;transport=UDP
Max-Forwards: 70
Route: <sip:10.4.128.21:6100;lr>
Route: <sip:orig@scscf.ims.mnc001.mcc001.3gppnetwork.org:6060;lr>
Proxy-Require: sec-agree
Require: sec-agree
Contact: <sip:0398765432100@192.168.101.5:6300>;+sip.instance="<urn:gsma:imei:35622410-483840-0>";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.smsip
To: <tel:0398765432100>
From: <tel:0398765432100>;tag=6197e96a
Call-ID: yQFjFiHYzbfiJeASucHAGQ..@192.168.101.5
CSeq: 1 SUBSCRIBE
Expires: 600000
Accept: application/reginfo+xml
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, INFO, REFER, NOTIFY, MESSAGE, PRACK
Supported: sec-agree
User-Agent: SM-T515-TB4 Samsung IMS 6.0
Event: reg
Security-Verify: ipsec-3gpp;prot=esp;mod=trans;spi-c=100;spi-s=101;port-c=5100;port-s=6100;alg=hmac-md5-96;ealg=null
P-Preferred-Identity: <tel:0398765432100>
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=001010001000019b
Content-Length: 0

