PRACK sip:10.46.0.20:53718 SIP/2.0
Via: SIP/2.0/UDP 10.80.0.5:5063;branch=z9hG4bKKZJS4SPBYKGT6VUS4ROUQKY7HM
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKZGKNXUQAKXGLFJPFCPT2P3IQE4
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKJ2DKEQGHB52XPHLY7QDEBUKA2K
Via: SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKNZVJSMVCADT2NLGQ6RWLNRYX2B
RAck: 2 1 INVITE
To: <tel:+15550000003>;tag=6Zi2atuHsl
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=lqrC6ZCHZP
Call-ID: I20FO7fKKvBIvQMv2eVJjemL
Session-ID: ceb30349f3222f86ed022861c59032f8
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 4 PRACK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKpglvtGCUN7Nvx1s;rport=57130;received=10.46.0.17
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 66
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

