SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKpglvtGCUN7Nvx1s;received=10.46.0.17;rport=57130
To: <tel:+15550000003>;tag=6Zi2atuHsl
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=lqrC6ZCHZP
Call-ID: I20FO7fKKvBIvQMv2eVJjemL
Session-ID: ceb30349f3222f86ed022861c59032f8
CSeq: 4 PRACK
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

