SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.17:61189;branch=z9hG4bKNpFx0WSmhe5c2kG;received=10.46.0.17;rport=57130
From: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=lqrC6ZCHZP
To: <tel:+15550000003>;tag=6Zi2atuHsl
Call-ID: I20FO7fKKvBIvQMv2eVJjemL
Session-ID: ceb30349f3222f86ed022861c59032f8
CSeq: 1 INVITE
Record-Route: <sip:yxlpwprxmpbiklyoarggpjtb5s@10.80.0.5:5063;did=YJ4WZXIYMBHBE7K6;lr;r2=on;ue>, <sip:yxlpwprxmpbiklyoarggpjtb5s@10.80.0.5:5060;did=YJ4WZXIYMBHBE7K6;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=SYCHFOIZPH4EIYC7;lr>, <sip:mo@10.80.0.5:5080;did=NSSPSE7GI5UD2PLW;lr>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=G72XAUFBKDXPVFBV;lr;r2=on>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=G72XAUFBKDXPVFBV;lr;r2=on;transport=tcp;ue>
Supported: 100rel,path,replaces,timer
Session-Expires: 1800;refresher=uac
Require: timer
Contact: <sip:10.46.0.20:53718>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
User-Agent: iOS/27.0 iPhone
Content-Length: 0
P-Asserted-Identity: <tel:+15550000003>
P-Asserted-Identity: <sip:+15550000003@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

