BYE sip:10.46.0.17:61189 SIP/2.0
Reason: SIP;cause=200;text="User Triggered"
To: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=lqrC6ZCHZP
Route: <sip:yxlpwprxmpbiklyoarggpjtb5s@10.80.0.5:5063;did=YJ4WZXIYMBHBE7K6;lr;r2=on;ue>, <sip:yxlpwprxmpbiklyoarggpjtb5s@10.80.0.5:5060;did=YJ4WZXIYMBHBE7K6;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=SYCHFOIZPH4EIYC7;lr>, <sip:mo@10.80.0.5:5080;did=NSSPSE7GI5UD2PLW;lr>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=G72XAUFBKDXPVFBV;lr;r2=on>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=G72XAUFBKDXPVFBV;lr;r2=on;transport=tcp;ue>
From: <tel:+15550000003>;tag=6Zi2atuHsl
Call-ID: I20FO7fKKvBIvQMv2eVJjemL
Session-ID: ceb30349f3222f86ed022861c59032f8
Contact: <sip:10.46.0.20:53718>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 1 BYE
Via: SIP/2.0/UDP 10.46.0.20:53718;branch=z9hG4bKFAzjSQs2w1sqAv1;rport
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
P-Preferred-Identity: sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Require: sec-agree
Proxy-Require: sec-agree
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5064;port-s=5063;prot=esp;q=0.1;spi-c=77986854;spi-s=238201135
Content-Length: 0

