SIP/2.0 200 OK
Via: SIP/2.0/UDP 10.46.0.20:53718;branch=z9hG4bKFAzjSQs2w1sqAv1;received=10.46.0.20;rport=53718
To: <sip:15550000006@ims.mnc001.mcc001.3gppnetwork.org>;tag=lqrC6ZCHZP
From: <tel:+15550000003>;tag=6Zi2atuHsl
Call-ID: I20FO7fKKvBIvQMv2eVJjemL
Session-ID: ceb30349f3222f86ed022861c59032f8
CSeq: 1 BYE
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

