ACK sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone SIP/2.0
Via: SIP/2.0/TCP 10.0.0.2:46783;branch=z9hG4bKJMPUUOA4GX7IYWWPQTS6ENQFHC;rport
Route: <sip:10.0.0.1:5063;lr>
Route: <sip:orig-1@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
Max-Forwards: 70
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=J4IVCPB7UVBINWC2XLZ3S6QSXJ
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=4ZASNUTZY4MOFXESBBBI6UMKGP
Call-ID: 662fec69-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.2
CSeq: 1 ACK
Content-Length: 0

