SIP/2.0 401 Unauthorized
Via: SIP/2.0/TCP 10.46.0.2:5060;branch=z9hG4bK-524287-1---ba7d7ef7a718e060;rport=42749;keep;transport=TCP;received=10.46.0.2
To: <sip:999010000000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=TDTWHOLWFPPXNVNHD3MJ4KJU4E
From: <sip:999010000000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=4fdf2453
Call-ID: Z2DA--Y-Vm1l6HrBSerjCw..@10.46.0.2
CSeq: 1 REGISTER
Content-Length: 0
WWW-Authenticate: Digest realm="ims.mnc001.mcc999.3gppnetwork.org", nonce="jo2BY8bGSrWCrj42HC3Fu1W6h/vnY4AAMD0WPL+Egb8=", algorithm=AKAv1-MD5, qop="auth"
Security-Server: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=30560604;spi-s=41880514;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Supported: sec-agree

