SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bK7JRMONGHK7PCDTN6TKM7LTHGF4
Via: SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKBAF2DF3WTEA6DAWQOMWNLIHCYH
Max-Forwards: 70
Record-Route: <sip:5zdnqhmykiyb4kz7gkmqhsd4pk@10.80.0.5:5063;lr;r2=on;ue>
Record-Route: <sip:5zdnqhmykiyb4kz7gkmqhsd4pk@10.80.0.5:5060;lr;r2=on>
Contact: <sip:15550000007@10.46.0.2:6400>;+sip.instance="<urn:gsma:imei:00000000-000007-0>";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.smsip
To: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=6a038016
From: <sip:15550000007@ims.mnc001.mcc999.3gppnetwork.org>;tag=JHLBU3KHV2J7JHLINUKCFSED2Z
Call-ID: am-R1q6C4oM-Zpsmbic-_w..@10.46.0.2
CSeq: 715365327 NOTIFY
User-Agent: SM-A566W-A566WVLS6BZB7 Samsung IMS 6.0
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=9990100000100066c000
Content-Length: 0

