BYE sip:b394eba0-c3ed-4e54-adf4-83d317ca2979@10.46.0.2:43300 SIP/2.0
From: <tel:15550000002;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=5c8299b5
To: <sip:15550000005@ims.mnc001.mcc001.3gppnetwork.org>;tag=103226179
Contact: <sip:15550000002@10.46.0.3:49165>;+g.3gpp.mid-call;+g.3gpp.srvcc-alerting;+g.3gpp.ps2cs-srvcc-orig-pre-alerting;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video
Call-ID: 103226171_1760455216@10.46.0.2
CSeq: 1 BYE
Max-Forwards: 70
Via: SIP/2.0/TCP 10.46.0.3:49165;branch=z9hG4bKbb18cdba3168b646b68e5ef8
Content-Length: 0
Reason: RELEASE_CAUSE;cause=1;text="User ends call"
Require: sec-agree
P-Preferred-Identity: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>
Proxy-Require: sec-agree
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=0010100000100066c000
User-Agent: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Route: <sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5063;transport=tcp;lr;r2=on;ob;did=S6VRSB3XEKUJSGRP;ue>,<sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5060;lr;r2=on;ob;did=S6VRSB3XEKUJSGRP>,<sip:mt@10.80.0.5:5080;lr;did=ZSFH365MXCMK6S6R>,<sip:mo@10.80.0.5:5080;lr;did=AFZUARVXGVYCAC6E>,<sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5060;lr;r2=on;did=PPKZDRPPJIR3IS4W>,<sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5063;transport=tcp;lr;r2=on;did=PPKZDRPPJIR3IS4W;ue>
Security-Verify: ipsec-3gpp;q=0.1;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=null;spi-c=6454639;spi-s=197865269;port-c=5064;port-s=5063

