PRACK sip:b394eba0-c3ed-4e54-adf4-83d317ca2979@10.46.0.2:43300 SIP/2.0
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=f3fba2c9
To: <tel:15550000005;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=103140307
Call-ID: 328a0d67c51df36c@10.46.0.3
CSeq: 2 PRACK
Max-Forwards: 70
Via: SIP/2.0/TCP 10.46.0.3:49165;branch=z9hG4bKcb350e989ef34db868a3fa85
Content-Length: 0
Proxy-Require: sec-agree
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=0010100000100066c000
User-Agent: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Require: sec-agree
Supported: sec-agree
RAck: 1 1 INVITE
Session-ID: 9bc41936e65d546181bf36c36d83457b
Route: <sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5063;transport=tcp;lr;r2=on;did=QQPRLPCU4YQ4EQ6B;ue>,<sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5060;lr;r2=on;did=QQPRLPCU4YQ4EQ6B>,<sip:mo@10.80.0.5:5080;lr;did=MDAACB6W7KGDQU5I>,<sip:mt@10.80.0.5:5080;lr;did=CKZF4B4Q4KNTJFU3>,<sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5060;lr;r2=on;did=LANHD46HRCZAIJHW>,<sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5063;transport=tcp;lr;r2=on;did=LANHD46HRCZAIJHW;ue>
Security-Verify: ipsec-3gpp;q=0.1;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=null;spi-c=6454639;spi-s=197865269;port-c=5064;port-s=5063

