SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.46.0.3:49165;branch=z9hG4bK28e0a92c52375804a2dd347c
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=f3fba2c9
To: <tel:15550000005;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=103140307
Call-ID: 328a0d67c51df36c@10.46.0.3
CSeq: 1 INVITE
Record-Route: <sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5063;transport=tcp;lr;r2=on;did=LANHD46HRCZAIJHW;ue>,<sip:tmmgbfsyubr4jlhnlazmeepxie@10.80.0.5:5060;lr;r2=on;did=LANHD46HRCZAIJHW>,<sip:mt@10.80.0.5:5080;lr;did=CKZF4B4Q4KNTJFU3>,<sip:mo@10.80.0.5:5080;lr;did=MDAACB6W7KGDQU5I>,<sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5060;lr;r2=on;did=QQPRLPCU4YQ4EQ6B>,<sip:tkgtix7rbcrrsrqosvtxrd7mao@10.80.0.5:5063;transport=tcp;lr;r2=on;did=QQPRLPCU4YQ4EQ6B;ue>
Content-Length: 0
Session-ID: 9bc41936e65d546181bf36c36d83457b
Server: Core-Z5 N1982U.6.02.09.FR00
RSeq: 2
Contact: <sip:b394eba0-c3ed-4e54-adf4-83d317ca2979@10.46.0.2:43300>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
P-Asserted-Identity: <tel:+15550000005>
P-Asserted-Identity: <sip:+15550000005@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

