PRACK sip:10.46.0.17:61189 SIP/2.0
RAck: 1 1 INVITE
To: <tel:+15550000006>;tag=TIx1YlH5tS
Route: <sip:yxlpwprxmpbiklyoarggpjtb5s@10.80.0.5:5063;did=L5AXLJJDTGNLRPMO;lr;r2=on;ue>, <sip:yxlpwprxmpbiklyoarggpjtb5s@10.80.0.5:5060;did=L5AXLJJDTGNLRPMO;lr;r2=on>, <sip:mo@10.80.0.5:5080;did=JHBFDAGIDSRNIHSH;lr>, <sip:mt@10.80.0.5:5080;did=TRDMZTJYDTFUPYID;lr>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=3LADSZ64ZU26ZDNN;lr;r2=on>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=3LADSZ64ZU26ZDNN;lr;r2=on;transport=tcp;ue>
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=rDu5XCAcI7
Call-ID: 6CNYuJw7CaT0ZgcdFudaAnfo
Session-ID: 31f0475347d59a334a5b0300fe887c23
Contact: <sip:10.46.0.20:53718>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
CSeq: 2 PRACK
Via: SIP/2.0/UDP 10.46.0.20:53718;branch=z9hG4bKscB4hsaLKFF0E7M;rport
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015ee0000
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5064;port-s=5063;prot=esp;q=0.1;spi-c=77986854;spi-s=238201135
Require: sec-agree
Proxy-Require: sec-agree
Content-Length: 0

