SIP/2.0 200 OK
Via: SIP/2.0/UDP 10.46.0.20:53718;branch=z9hG4bKscB4hsaLKFF0E7M;received=10.46.0.20;rport=53718
To: <tel:+15550000006>;tag=TIx1YlH5tS
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=rDu5XCAcI7
Call-ID: 6CNYuJw7CaT0ZgcdFudaAnfo
Session-ID: 31f0475347d59a334a5b0300fe887c23
CSeq: 2 PRACK
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

