ACK tel:+15550000006 SIP/2.0
Call-ID: 6CNYuJw7CaT0ZgcdFudaAnfo
From: <sip:15550000003@ims.mnc001.mcc001.3gppnetwork.org>;tag=rDu5XCAcI7
Route: <sip:10.80.0.5:5063;lr>, <sip:orig-33@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
CSeq: 1 ACK
Via: SIP/2.0/UDP 10.46.0.20:53718;branch=z9hG4bK0r8tMtEYMwTwe3G;rport
To: <tel:+15550000006>;tag=TIx1YlH5tS
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Max-Forwards: 70
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Security-Verify: ipsec-3gpp;alg=hmac-sha-1-96;ealg=null;mod=trans;port-c=5064;port-s=5063;prot=esp;q=0.1;spi-c=77986854;spi-s=238201135
Require: sec-agree
Proxy-Require: sec-agree
Content-Length: 0

