SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.46.0.13:40279;branch=z9hG4bK398496443
From: <sip:15550000005@ims.mnc001.mcc001.3gppnetwork.org>;tag=263747
To: <tel:15550000004;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=264142
CSeq: 263739 INVITE
Call-ID: 263739_1760018656@10.46.0.13
Record-Route: <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;transport=tcp;lr;r2=on;did=QEKL32EPKUOGABT6;ue>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;lr;r2=on;did=QEKL32EPKUOGABT6>,<sip:mt@10.80.0.5:5080;lr;did=T7CQDBYIE5L6JSN5>,<sip:mo@10.80.0.5:5080;lr;did=NZYATJZMBQ5NAF66>,<sip:mwfvpmdjn5gmmwmnbhkzroke5x@10.80.0.5:5060;lr;r2=on;did=QSWJH7JYD4HQGDRM>,<sip:mwfvpmdjn5gmmwmnbhkzroke5x@10.80.0.5:5063;transport=tcp;lr;r2=on;did=QSWJH7JYD4HQGDRM;ue>
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
RSeq: 2
Contact: <sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
P-Asserted-Identity: <tel:+15550000004>
P-Asserted-Identity: <sip:+15550000004@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

