PRACK sip:45c5aa86-bf70-11f1-81ff-2bcf73babbc9@10.0.0.3:33445 SIP/2.0
Via: SIP/2.0/UDP 10.0.0.2:34253;branch=z9hG4bKXVZLANTGQGBCUXOARFNICCWHH3;rport
Route: <sip:lcvkhad6e5wvnlost4ata7aziz@10.0.0.1:5063;transport=tcp;lr;r2=on;did=QEDC7Q3R6DODPSC2;ue>, <sip:lcvkhad6e5wvnlost4ata7aziz@10.0.0.1:5060;lr;r2=on;did=QEDC7Q3R6DODPSC2>, <sip:mo@10.0.0.1:5080;lr;did=Q7XI4HBWGPYVE24E>, <sip:mt@10.0.0.1:5080;lr;did=NTSNXLUHGL6PY5EB>, <sip:vnr7bmqfxnmbaexcy6fhcmncpf@10.0.0.1:5060;lr;r2=on;did=X7OUUNZPLUMJ362N>, <sip:vnr7bmqfxnmbaexcy6fhcmncpf@10.0.0.1:5063;transport=tcp;lr;r2=on;did=X7OUUNZPLUMJ362N;ue>
Max-Forwards: 70
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=NHPSGW3YBBMNXVJDHW53XDVNGU
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=TQJTDMFPY33VWNCTMH3QOXSNZH
Call-ID: 4603afff-bf70-11f1-81ff-2bcf73babbc9@10.0.0.2
CSeq: 2 PRACK
RAck: 837482279 1 INVITE
Content-Length: 0
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=122230114;spi-s=108696944;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Require: sec-agree
Proxy-Require: sec-agree
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010000001

