PRACK sip:66200811-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.3:45849 SIP/2.0
Via: SIP/2.0/TCP 10.0.0.2:46783;branch=z9hG4bKMPZTFBJSTKWFCUIZDD6WLY252E;rport
Route: <sip:u6ko3qca5otjtdr7t5r6mykajq@10.0.0.1:5063;transport=tcp;lr;r2=on;did=KFLV5UAV3AZWW6BJ;ue>, <sip:u6ko3qca5otjtdr7t5r6mykajq@10.0.0.1:5060;lr;r2=on;did=KFLV5UAV3AZWW6BJ>, <sip:mo@10.0.0.1:5080;lr;did=32X5K3MYKIO55BCA>, <sip:mt@10.0.0.1:5080;lr;did=MUBYW3Z3FNLTPYPU>, <sip:mzi3nxmn2cruqeuuhfm6h74r7b@10.0.0.1:5060;lr;r2=on;did=XISKBLPJNSXSUBHY>, <sip:mzi3nxmn2cruqeuuhfm6h74r7b@10.0.0.1:5063;transport=tcp;lr;r2=on;did=XISKBLPJNSXSUBHY;ue>
Max-Forwards: 70
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=FDVPAJ22ZGPUS67COMQ6HW7A5T
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=RVR5ABTUD7VHHB527SCXES5CWA
Call-ID: 665e1dd8-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.2
CSeq: 2 PRACK
RAck: 406976770 1 INVITE
Content-Length: 0
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=103162097;spi-s=212027648;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Require: sec-agree
Proxy-Require: sec-agree
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100010000001

