CANCEL sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone SIP/2.0
Via: SIP/2.0/TCP 10.0.0.2:34253;branch=z9hG4bKAV4K5HH6JF7JUTE7WJHJPCNG5A;rport
Route: <sip:10.0.0.1:5063;lr>
Route: <sip:orig-1@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
Max-Forwards: 70
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=NHPSGW3YBBMNXVJDHW53XDVNGU
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>
Call-ID: 4603afff-bf70-11f1-81ff-2bcf73babbc9@10.0.0.2
CSeq: 1 CANCEL
Content-Length: 0

