SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.0.0.2:34253;branch=z9hG4bKAV4K5HH6JF7JUTE7WJHJPCNG5A;rport=38225;received=10.0.0.2
Record-Route: <sip:vnr7bmqfxnmbaexcy6fhcmncpf@10.0.0.1:5063;transport=tcp;lr;r2=on;did=X7OUUNZPLUMJ362N;ue>
Record-Route: <sip:vnr7bmqfxnmbaexcy6fhcmncpf@10.0.0.1:5060;lr;r2=on;did=X7OUUNZPLUMJ362N>
Record-Route: <sip:mt@10.0.0.1:5080;lr;did=NTSNXLUHGL6PY5EB>
Record-Route: <sip:mo@10.0.0.1:5080;lr;did=Q7XI4HBWGPYVE24E>
Record-Route: <sip:lcvkhad6e5wvnlost4ata7aziz@10.0.0.1:5060;lr;r2=on;did=QEDC7Q3R6DODPSC2>
Record-Route: <sip:lcvkhad6e5wvnlost4ata7aziz@10.0.0.1:5063;transport=tcp;lr;r2=on;did=QEDC7Q3R6DODPSC2;ue>
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=NHPSGW3YBBMNXVJDHW53XDVNGU
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=TQJTDMFPY33VWNCTMH3QOXSNZH
Call-ID: 4603afff-bf70-11f1-81ff-2bcf73babbc9@10.0.0.2
CSeq: 1 INVITE
Content-Length: 0
Contact: <sip:45c5aa86-bf70-11f1-81ff-2bcf73babbc9@10.0.0.3:33445>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, UPDATE, PRACK, NOTIFY, MESSAGE
Supported: 100rel, timer, precondition
P-Asserted-Identity: <tel:+15550002>
P-Asserted-Identity: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

