ACK sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone SIP/2.0
Via: SIP/2.0/TCP 10.0.0.2:46783;branch=z9hG4bKWWB2JEAIVIOONJKWBW4B7F4VCX;rport
Route: <sip:10.0.0.1:5063;lr>
Route: <sip:orig-1@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
Max-Forwards: 70
From: <sip:+15550001@ims.mnc001.mcc001.3gppnetwork.org>;tag=FDVPAJ22ZGPUS67COMQ6HW7A5T
To: <sip:+15550002@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=RVR5ABTUD7VHHB527SCXES5CWA
Call-ID: 665e1dd8-bf75-11f1-86b4-4d6ade81ba5e@10.0.0.2
CSeq: 1 ACK
Content-Length: 0

