PRACK sip:10.46.0.17:61189 SIP/2.0
From: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>;tag=2709695
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=GdQCQwRQqj
CSeq: 2709689 PRACK
Call-ID: 2709688_3069114096@10.46.0.15
Content-Length: 0
Via: SIP/2.0/TCP 10.46.0.15:43435;branch=z9hG4bK2050260451
Max-Forwards: 70
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015EE0000
Security-Verify: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=113224940;spi-s=105724704;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
RAck: 1 2709688 INVITE
Route: <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;did=2IGOGQRNOJOD6PWC;lr;r2=on;transport=tcp;ue>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;did=2IGOGQRNOJOD6PWC;lr;r2=on>,<sip:mo@10.80.0.5:5080;did=JYUGX4TC663PQD5G;lr>,<sip:mt@10.80.0.5:5080;did=WYR7FTS4PGQYBJFH;lr>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=WPUGTEUSZUEI3WKZ;lr;r2=on>,<sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=WPUGTEUSZUEI3WKZ;lr;r2=on;transport=tcp;ue>
User-Agent: Core-Z5 N1982U.6.02.09.FR00
Proxy-Require: sec-agree
Require: sec-agree
Supported: timer

