SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.15:43435;branch=z9hG4bK2050260451
From: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>;tag=2709695
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=GdQCQwRQqj
CSeq: 2709689 PRACK
Call-ID: 2709688_3069114096@10.46.0.15
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

