SIP/2.0 486 Call Rejected By User
Via: SIP/2.0/TCP 10.46.0.15:43435;branch=z9hG4bK2540163860
From: <sip:15550000004@ims.mnc001.mcc001.3gppnetwork.org>;tag=2709695
To: <tel:15550000006;phone-context=ims.mnc001.mcc001.3gppnetwork.org>;tag=GdQCQwRQqj
CSeq: 2709688 INVITE
Call-ID: 2709688_3069114096@10.46.0.15
Record-Route: <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5063;did=WPUGTEUSZUEI3WKZ;lr;r2=on;transport=tcp;ue>, <sip:byfnpmnrebl3w4rtfu7vl6aath@10.80.0.5:5060;did=WPUGTEUSZUEI3WKZ;lr;r2=on>, <sip:mt@10.80.0.5:5080;did=WYR7FTS4PGQYBJFH;lr>, <sip:mo@10.80.0.5:5080;did=JYUGX4TC663PQD5G;lr>, <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;did=2IGOGQRNOJOD6PWC;lr;r2=on>, <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;did=2IGOGQRNOJOD6PWC;lr;r2=on;transport=tcp;ue>
Contact: <sip:10.46.0.17:61189>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio
Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,UPDATE
Supported: 100rel,path,replaces
User-Agent: iOS/27.0 iPhone
Content-Length: 0

