REGISTER sip:ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
From: <sip:001010000000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=7b921eb8
To: <sip:001010000000002@ims.mnc001.mcc001.3gppnetwork.org>
Contact: <sip:1ca9266b-5791-f0ca-9a23-92da316d71a9@10.46.0.3:5060>;audio;+g.3gpp.nw-init-ussi;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";video;+g.3gpp.accesstype="cellular2";+g.3gpp.smsip;reg-id=1;+sip.instance="<urn:gsma:imei:00000000-000006-0>"
Call-ID: bed67b5899ddd8f7@10.46.0.3
CSeq: 1 REGISTER
Max-Forwards: 70
Via: SIP/2.0/TCP 10.46.0.3:5060;branch=z9hG4bK6f788b4e5775d72896f237c6
Expires: 600000
Allow: INVITE,CANCEL,UPDATE,PRACK,BYE,ACK,MESSAGE,SUBSCRIBE,NOTIFY,PUBLISH,REFER,INFO,OPTIONS
Content-Length: 0
User-Agent: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Authorization: Digest username="001010000000002@ims.mnc001.mcc001.3gppnetwork.org",realm="ims.mnc001.mcc001.3gppnetwork.org",uri="sip:ims.mnc001.mcc001.3gppnetwork.org",nonce="",response=""
Privacy: none
Require: sec-agree
Proxy-Require: sec-agree
Security-Client: ipsec-3gpp;alg=hmac-md5-96;prot=esp;mod=trans;ealg=aes-cbc;spi-c=2306;spi-s=2307;port-c=49164;port-s=49165,ipsec-3gpp;alg=hmac-md5-96;prot=esp;mod=trans;ealg=des-ede3-cbc;spi-c=2306;spi-s=2307;port-c=49164;port-s=49165,ipsec-3gpp;alg=hmac-md5-96;prot=esp;mod=trans;ealg=null;spi-c=2306;spi-s=2307;port-c=49164;port-s=49165,ipsec-3gpp;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=aes-cbc;spi-c=2306;spi-s=2307;port-c=49164;port-s=49165,ipsec-3gpp;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=des-ede3-cbc;spi-c=2306;spi-s=2307;port-c=49164;port-s=49165,ipsec-3gpp;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=null;spi-c=2306;spi-s=2307;port-c=49164;port-s=49165
Supported: path,sec-agree

