SIP/2.0 401 Unauthorized
From: <sip:001010000000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=7b921eb8
To: <sip:001010000000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=6M4ZLUBFRCABCF3HHQJA2ZHCTE
Call-ID: bed67b5899ddd8f7@10.46.0.3
CSeq: 1 REGISTER
Via: SIP/2.0/TCP 10.46.0.3:5060;branch=z9hG4bK6f788b4e5775d72896f237c6
Content-Length: 0
WWW-Authenticate: Digest realm="ims.mnc001.mcc001.3gppnetwork.org", nonce="MPPqH7S50zBKAQP4h8kFCgZnIbpZA4AAzwyjgZJA30U=", algorithm=AKAv1-MD5, qop="auth"
Security-Server: ipsec-3gpp;q=0.1;prot=esp;mod=trans;spi-c=6454639;spi-s=197865269;port-c=5064;port-s=5063;alg=hmac-sha-1-96;ealg=null
Supported: sec-agree

