REGISTER sip:ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
From: <sip:001010000000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=7b921eb8
To: <sip:001010000000002@ims.mnc001.mcc001.3gppnetwork.org>
Contact: <sip:1ca9266b-5791-f0ca-9a23-92da316d71a9@10.46.0.3:49165>;audio;+g.3gpp.nw-init-ussi;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";video;+g.3gpp.accesstype="cellular2";+g.3gpp.smsip;reg-id=1;+sip.instance="<urn:gsma:imei:00000000-000006-0>"
Call-ID: bed67b5899ddd8f7@10.46.0.3
CSeq: 2 REGISTER
Max-Forwards: 70
Via: SIP/2.0/TCP 10.46.0.3:49165;branch=z9hG4bK453caab0e8aab14036c480dc
Expires: 600000
Allow: INVITE,CANCEL,UPDATE,PRACK,BYE,ACK,MESSAGE,SUBSCRIBE,NOTIFY,PUBLISH,REFER,INFO,OPTIONS
Content-Length: 0
User-Agent: Google_Pixel10a_Android 16_BD6A.251031.001.A4
Authorization: Digest username="001010000000002@ims.mnc001.mcc001.3gppnetwork.org",realm="ims.mnc001.mcc001.3gppnetwork.org",algorithm=AKAv1-MD5,uri="sip:ims.mnc001.mcc001.3gppnetwork.org",nonce="MPPqH7S50zBKAQP4h8kFCgZnIbpZA4AAzwyjgZJA30U=",response="b928a52dd7faff509c7a3e584a470628",qop=auth,nc=00000001,cnonce="8e8f390c38987cf9ad224d96db0465e"
Privacy: none
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=0010100000100066c000
Require: sec-agree
Proxy-Require: sec-agree
Security-Client: ipsec-3gpp;alg=hmac-md5-96;prot=esp;mod=trans;ealg=aes-cbc;spi-c=2306;spi-s=2307;port-c=49164;port-s=49165,ipsec-3gpp;alg=hmac-md5-96;prot=esp;mod=trans;ealg=des-ede3-cbc;spi-c=2306;spi-s=2307;port-c=49164;port-s=49165,ipsec-3gpp;alg=hmac-md5-96;prot=esp;mod=trans;ealg=null;spi-c=2306;spi-s=2307;port-c=49164;port-s=49165,ipsec-3gpp;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=aes-cbc;spi-c=2306;spi-s=2307;port-c=49164;port-s=49165,ipsec-3gpp;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=des-ede3-cbc;spi-c=2306;spi-s=2307;port-c=49164;port-s=49165,ipsec-3gpp;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=null;spi-c=2306;spi-s=2307;port-c=49164;port-s=49165
Supported: path,sec-agree
Security-Verify: ipsec-3gpp;q=0.1;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=null;spi-c=6454639;spi-s=197865269;port-c=5064;port-s=5063

