SUBSCRIBE sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
From: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>;tag=991a32fe
To: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>
Contact: <sip:1ca9266b-5791-f0ca-9a23-92da316d71a9@10.46.0.3:49165>;audio;+g.3gpp.nw-init-ussi;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";video;+g.3gpp.smsip;+sip.instance="<urn:gsma:imei:00000000-000006-0>"
Call-ID: 7aea4c93342fa70@10.46.0.3
CSeq: 1 SUBSCRIBE
Max-Forwards: 70
Via: SIP/2.0/TCP 10.46.0.3:49165;branch=z9hG4bKccc56a88b056827fc15891
Expires: 600000
Content-Length: 0
Allow: INVITE,CANCEL,UPDATE,PRACK,BYE,ACK,MESSAGE,SUBSCRIBE,NOTIFY,PUBLISH,REFER,INFO,OPTIONS
P-Preferred-Identity: <sip:15550000002@ims.mnc001.mcc001.3gppnetwork.org>
User-Agent: Google_Pixel10a_Android 16_BD6A.251031.001.A4
P-Access-Network-Info: 3GPP-NR-TDD;utran-cell-id-3gpp=0010100000100066c000
Require: sec-agree
Proxy-Require: sec-agree
Event: reg
Route: <sip:10.80.0.5:5063;lr>,<sip:orig-7@scscf.ims.mnc001.mcc001.3gppnetwork.org:5080;lr>
Security-Verify: ipsec-3gpp;q=0.1;alg=hmac-sha-1-96;prot=esp;mod=trans;ealg=null;spi-c=6454639;spi-s=197865269;port-c=5064;port-s=5063
Accept: application/reginfo+xml

