SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.80.0.5:5063;branch=z9hG4bKFHOVJ5FFADSGGGOGEFIW44AKYZ,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKL2WZHVMMSC7C7ZC3NJRFYPZOBR,SIP/2.0/UDP 10.80.0.5:5070;branch=z9hG4bK7GLSN4VDTLDQC7MOLPZBKV4ZZY,SIP/2.0/UDP 10.80.0.5:5080;branch=z9hG4bKDWZ7JL3CVK3QZLGKZPO2W56XDI,SIP/2.0/UDP 10.80.0.5:5060;branch=z9hG4bKAH2C4Y6OZST4MANHAQI6X5BWY6,SIP/2.0/TCP 10.46.0.14:40265;branch=z9hG4bK1442902918
From: <sip:15550000001@ims.mnc001.mcc001.3gppnetwork.org>;tag=783166
To: <sip:15550000004;phone-context=ims.mnc001.mcc001.3gppnetwork.org@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=783471
CSeq: 783160 INVITE
Call-ID: 783160_4111218192@10.46.0.14
Record-Route: <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;transport=tcp;lr;r2=on;did=2SKLSZIK7BAOI2ED;ue>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;lr;r2=on;did=2SKLSZIK7BAOI2ED>,<sip:mt@10.80.0.5:5080;lr;did=5VVWDAZQ3SKV2LSA>,<sip:mo@10.80.0.5:5080;lr;did=BL5YC3Z366BQXNXG>,<sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5060;lr;r2=on;did=WZXMYJTSBXRSVS7Z>,<sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5063;transport=tcp;lr;r2=on;did=WZXMYJTSBXRSVS7Z;ue>
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
RSeq: 2
P-Access-Network-Info: 3GPP-E-UTRAN-FDD;utran-cell-id-3gpp=0010100015EE0000
Contact: <sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS

