SIP/2.0 200 OK
Via: SIP/2.0/TCP 10.46.0.14:40265;branch=z9hG4bK1442902918
From: <sip:15550000001@ims.mnc001.mcc001.3gppnetwork.org>;tag=783166
To: <sip:15550000004;phone-context=ims.mnc001.mcc001.3gppnetwork.org@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=783471
CSeq: 783160 INVITE
Call-ID: 783160_4111218192@10.46.0.14
Record-Route: <sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5063;transport=tcp;lr;r2=on;did=2SKLSZIK7BAOI2ED;ue>,<sip:de3wrydi5e3hcnhjmlpzs4qzn5@10.80.0.5:5060;lr;r2=on;did=2SKLSZIK7BAOI2ED>,<sip:mt@10.80.0.5:5080;lr;did=5VVWDAZQ3SKV2LSA>,<sip:mo@10.80.0.5:5080;lr;did=BL5YC3Z366BQXNXG>,<sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5060;lr;r2=on;did=WZXMYJTSBXRSVS7Z>,<sip:glnc67uf4gsp6g6ksmjaiyh4mr@10.80.0.5:5063;transport=tcp;lr;r2=on;did=WZXMYJTSBXRSVS7Z;ue>
Content-Length: 0
Session-Expires: 1800;refresher=uac
Server: Core-Z5 N1982U.6.02.09.FR00
Require: timer,100rel
Contact: <sip:ca20d2b6-2524-424e-ac97-40fff9783fc4@10.46.0.15:43435>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Supported: 100rel,from-change,tdialog
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
P-Asserted-Identity: <tel:+15550000004>
P-Asserted-Identity: <sip:+15550000004@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

