SIP/2.0 180 Ringing
Via: SIP/2.0/TCP 10.46.0.9:43885;branch=z9hG4bK1835656863
From: <sip:15550000008@ims.mnc001.mcc001.3gppnetwork.org>;tag=111029920
To: <sip:15550000005;phone-context=ims.mnc001.mcc001.3gppnetwork.org@ims.mnc001.mcc001.3gppnetwork.org;user=phone>;tag=111029801
CSeq: 111029915 INVITE
Call-ID: 111029915_4111788112@10.46.0.9
Record-Route: <sip:l2aykhrmqrls3wwcj6g7e6j3yy@10.80.0.5:5063;transport=tcp;lr;r2=on;did=C725EFD2JDSZBPQS;ue>,<sip:l2aykhrmqrls3wwcj6g7e6j3yy@10.80.0.5:5060;lr;r2=on;did=C725EFD2JDSZBPQS>,<sip:mt@10.80.0.5:5080;lr;did=2DY5Z3WCIO7VAYXD>,<sip:mo@10.80.0.5:5080;lr;did=SWJUHAP3GZ3D2HK3>,<sip:nsbgwhufa64gwwi7ngbk7jry6d@10.80.0.5:5060;lr;r2=on;did=FNGZKABHB256OCUW>,<sip:nsbgwhufa64gwwi7ngbk7jry6d@10.80.0.5:5063;transport=tcp;lr;r2=on;did=FNGZKABHB256OCUW;ue>
Content-Length: 0
Server: Core-Z5 N1982U.6.02.09.FR00
RSeq: 2
Contact: <sip:2da86196-c8f7-4939-af8b-fbdac4e983f2@10.46.0.8:42225>;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";audio;video;+g.3gpp.nw-init-ussi
Require: 100rel
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,PRACK,MESSAGE,REFER,NOTIFY,INFO,OPTIONS
P-Asserted-Identity: <tel:+15550000005>
P-Asserted-Identity: <sip:+15550000005@ims.mnc001.mcc001.3gppnetwork.org;user=phone>

